bootstrap-vue/bootstrap-vue

components/breadcrumb.vue

I modify breadcrumb for latest Bootstrap v4 cssclass. 
[http://v4-alpha.getbootstrap.com/components/breadcrumb/](http://v4-alpha.getbootstrap.com/components/breadcrumb/)
followings are my changes.
* add `breadcrumb-item` css class to `li` tag.
* change to reverse  `active` css class condition.

modify breadcrumb for latest BootstrapV4 class

---

components/index.js

This would allow us to import individual components instead of "using" the plugin on the main `Vue` instance.
So, in addition of being able to use the whole plugin like before:
```js
// index.js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
Vue.use('BootstrapVue')
```
We could also instead import and use components individually.
```js
// components/Hello.vue
<template>
<b-button-group vertical>
<b-button>Left</b-button>
<b-button>Middle</b-button>
<b-button>Right</b-button>
</b-button-group>
</template>
<script>
import { bButtonGroup, bButton } from 'bootstrap-vue'
export default {
components: {
bButtonGroup,
bButton
}
}
</script>
```

Export individual components

---

components/components.js
components/index.js
scripts/build

Fixes the issues reported in https://github.com/bootstrap-vue/bootstrap-vue/pull/26#issuecomment-261690614.
Moved all components export into it's own `components.js` file because it was a lot of duplication otherwise, not the cleanest solution (having a file that just import/export) but it works.
@pi0 @sourcec0de this would result in `v0.3.9` if your good with these changes, or do you have another approach to suggest ?

Fixed default export of plugin

---

components/tab.vue
components/tabs.vue

[https://vuejs.org/v2/guide/migration.html#vm-set-changed](https://vuejs.org/v2/guide/migration.html#vm-set-changed)
I also moved `active` from props to data because : 
> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "active" (found in component <bTab>)

Fixed issues on tabs/tab #34

---

components/form-input.vue

`inputClass` and `labelClass` are presented in `<template>` field, but both missing in `props`, and also missing `v-bind` in `<template>` field.

Fixed missing "labelClass" and "inputClass"

---

components/button-radio.vue

I fixed `:class` issue, `btnVariant` and `btnSize` were not interpreted. 
I also moved `model` into data because : 
>[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value.

Fixed b-button-radio issues

---

components/dropdown.vue

I fixed the dropdown issue and i adapted the template to the actual bootstrap 4 documentation.
Before merging, my question is about `$emit` methods in this component, i'm not really sure that they are usefull here, but if i'm wrong, please tell me why and i'll adapt my merge request.
Edit: If this pull request is valid, i'll update dropdows documention to : 
`
<b-dropdown text="action" size="md" variant="primary" :caret="true">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<a class="dropdown-item" href="#">Something else here</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="#">Separated link</a>
</b-dropdown>
`
Thanks by advance

Fixed dropdown issue #24

---

components/alert.vue

According to #58, we have the same name `show` between props and computed parts.
I analysed your code and i decided to remove the `show` computed part because `localShow` already return the `show` value in `data` part.
The component works on 2.1.8 and 2.1.7 without any error code now ;)

Fixed issue #58

---

components/collapse-toggle.vue

Hi, I needed an "active" class toggle when the trigger for collapse is clicked.
Thought it may be helpful to keep track of open/close status there as well as in the actual collapsible item.

Added active status handling for collapse-trigger

---

package.json

As far as I understand, the Vue, Tether and Bootstrap dependencies should be in the "dependencies" group, not the "devDependencies" group. The dev group is meant for dependencies required only when developing on THIS package. When another package pulls this one in to extend it or use it in its own project, as far as this package is concerned that is a production environment. If these compilation-required dependencies are in the "dev" packages group then NPM or Yarn will not pull them down to the parent project as required and expected. In my particular experience, I found I had to add Tether as a dependency in my own packages.json, which shouldn't be required.
I may misunderstand your intention here, and I'm comparatively novice so feel to ignore this if you disagree.

Move production dependencies out of devDependencies

---

components/popover.vue
package.json

This is a proposed major re-write for Popover. This makes breaking changes but given that it seems there has been little work on it since early on, it seemed worthwhile.
I tried to adopt as much of the official Bootstrap functionality as makes sense in a Vue framework context. This includes making changes to some of the property names to align with Bootstrap.
Previously, if both a property and a slot of the same name (either 'title' or 'content') is provided, then displaying the slot takes priority. This is more consistent with typical default VueJS behavior.
External control of the popover is provided, and appropriate events are provided parent code to respond to changes.
Determination of how to respond to events is simplified. When multiple event types are being monitored, a simple …

Popover re-design

---

package.json

webpack understands the native import syntax, and uses it for [tree shaking](https://webpack.js.org/guides/hmr-react/#babel-config)
Don't use
use

support tree-shaking

---

components/modal.vue

I've used multiple modals in one page and need listen to their shown and hidden events. Wondering if the specific modal id could be added to payload so that I can respond to these events dispatched from different modals respectively.
Thanks for your time.

Add modal id to shown::modal and hidden::modal event payload

---

components/modal.vue

Attention: I did very little testing on this, but "it works for me". I don't know where the "in" class originally came from (Bootstrap 3?). But in the documentation for Bootstrap 4 this class is never mentioned. Switching to "show" immediately fixed the modals for me.

Switch CSS class 'in' for 'show', fixes #63

---

components/carousel.vue

Carousel indicators are not updating properly, because the same variable "index" is used in the loop and in the data property

Fix carousel indicators

---

components/form-input.vue

As discussed in #64 the prop validation should allow for Numbers as well.

Allow numbers as values for form inputs, closes #64

---

components/form-input.vue

When formatting on input event, the input field loses focus and makes it really difficult to enter the desired value. Formatting on change feels much more natural.

Format form input on change

---

components/form-input.vue

Now the form-input component can have nice keyup events, just like stated in the documentation: https://vuejs.org/v2/guide/events.html#Key-Modifiers

Emit keyup event in form-input component

---

components/table.vue

As an extension of #115 we needed to be able to access the `<td>`, so this uses the `field.class`.
Just a quick question, potentially this should have been a ternary that checks if field.class exists? Or is this simplistic method ok?

Add option to get class onto td of table

---

components/nav-item.vue

If you use an object in to prop without using the href prop (for example if you use named routes) you will get href="[object Object]" in your html.
My pull request will fix this.

href prop isnt needed if object in to prop

---

components/modal.vue

When modal is not shown the ESC keypress does the following:
```
bootstrap-vue.common.js:1 Uncaught TypeError: Cannot read property 'classList' of undefined
at bootstrap-vue.common.js:1
(anonymous) @ bootstrap-vue.common.js:1
```

do not trigger on key events when modal is not visible

---

components/dropdown.vue

another instance where we need to import the dependent components directly. similar to #99 and #98

added explicit import of button to dropdown.vue

---

components/modal.vue
components/nav-item-dropdown.vue

Add .bind(this) to hub.$on event listeners because without this modification at the moment of receving event "this" points to root element instead of current.
If I'm wrong, tell me how to use modal without his mod, pls :)

Update modal.vue 

---

components/modal.vue

This PR is for issue #147 
1. Added and properly configured global vue transition-group to cover both modal and backdrop. 
2. Made small local fix to Bootstrap's `.modal` class.
3. Added transition callback on after-enter event to modal stay showed.
4. chanded emmited event to `hidden ` at the hide method.

Enhancement of modal open/close transitions

---

lib/components/popover.vue

I used this library to show small forms on the click of a button and
overwriting the max-width that was set via CSS does not work for me, 
so I forked the repo and added these small changes. 
The only change is a small property 'maxwidth' that accepts the values 'v-sm', 'sm', 'md', 'lg' and 'v-lg'.
It's still only the max-width that changes and not the width itself and the default is still set to 276px, as per constraint, so the impact on users who do not want anything changed, will be nonexistant.

Added maxwidth property to popover

---

lib/components/dropdown-item.vue
lib/components/link.vue
lib/components/modal.vue
lib/components/nav-item-dropdown.vue

`modal.vue`
moved onclick handler "onlickOut" from modal to modal-backdrop as it more logical place IMHO
`dropdown-item.vue`
`link.vue`
changes to make possible attach @click handlers
`nav-item-dropdown`
clickout behaviour like dropdown component
some minor changes

API improvements

---

docs/components/index.js
docs/components/tabs/README.md
docs/components/tabs/index.js
docs/components/tabs/meta.json
docs/nuxt/pages/play.vue
examples/tabs/demo.css
examples/tabs/demo.details
examples/tabs/demo.html
examples/tabs/demo.js
lib/components/tab.vue
lib/components/tabs.vue

Hi @pi0, there is my refactor attempt of Tabs. Please check code b4 merge :) I've tested already,  but just for sure :)

Tabs refactoring

---

lib/components/tabs.vue

Check if $slots.default exists before init this.tabs array.
test case: realtime creation of tabs based on user actions, init with undefined or empty tabs iteractor.

[Tabs] Not Null check

---

lib/components/tab.vue
lib/components/tabs.vue
package.json

There use cases when you need custom tab heads that are not <a>.

Add an option for a custom tab-head

---

lib/components/tab.vue

Fix bug of tab component removing 'show' css class prematurely

---

lib/components/table.vue

Fixed pagination by adding v-model to table, so it can throw outside count of filtered items, then we can pass this data to pagination as totalrows.
The another approach may be using `this.$root` as event bus for `table.emit('filtered', items.count)` and `pagination.on('filtered', function(totalrows){....})`.

[Table] Fixed pagination when filtered table

---

lib/components/modal.vue

I'm submitting two fixes:
- ~~Added the `id` prop to b-form-input. This is not necessary but it prevents Vue from complaining that the property is not defined~~
- I changed the behavior of b-modal's click events so that `closeOnBackdrop` has the intended behaviour. In particular:
* I removed the `id` check is I want to use modals without setting any id
* I capture click events on the modal's content. That way the modal only closes when the user clicks on the backdrop; not on the modal itself

Two minor fixes

---

lib/components/collapse.vue

Since css animation does not support 0 to auto, using max-height does not look perfectly, the transition time seems less than expected.
I add a wrapper div to detect the height of content, and add the height dynamically to the transition element's style.

better collapse animation

---

lib/components/popover.vue

This implements two features:
- Smooth fade transition on show and fade. This is identical to that in native Bootstrap 4
- The CSS classes added by Tether to the target element and now cleaned up on unloading. Note the current implementation looks for all classes with the prefix "tether-" and removes them, so any custom classes should not also start with "tether-". I consider this to be very unlikely and therefore safe.

Popover: Transition animal, CSS cleanup on dismiss

---

lib/components/modal.vue

When the show class is added in the after-enter handler of the vue
transition group it gets lost if an update is made asynchronously
in the modal shown handler: https://jsfiddle.net/bw7socb3/

Add show class when visible.

---

lib/components/modal.vue

Added option for disabling close on ESC (prop: closeOnEsc, defaults to true) and switched to using @keyup.esc handler.
Added option to hide header close button (prop: hideHeaderClose, defaults to false)
Added in the enforceFocus handler to make sure focus never leaves dialog while it is open.  This provides better ARIA compliance as some screen readers (and browsers) will let you tab through document even though a dialog is open.
Also added aria-labeledby and aria-describedby attributes, as well as switched the modal header and footer to semantic elements for better ARIA accessibility.

Added closeOnEsc, hideHeaderClose & enforceFocus

---

lib/components/form-checkbox.vue
lib/components/form-file.vue
lib/components/form-select.vue

This behavior already exists in the form-input and will ensure
a valid id exists for the label to reference when using the
form-fieldset component.

Use default id (b_UID) for checkbox, file and select.

---

lib/components/dropdown.vue

Changed feedback text block from class 'form-text' to 'form-control-feedback' to convey state.
Added ARIA role="alert" to feedback div.
Changed the target select from first child of content to querySelector() of first input element in content. This selector is  configurable as a prop inputSelector and defaults to 'input, select, textarea'

b-form-field fixed feedback class, & change choosing 'for' target ID

---

lib/components/tabs.vue

now tabs can be positioned below the tab-content. Styling has to be overridden because bootstrap doesn't support for tabs at bottom of tab-content.
new prop: position supports two options only, top and bottom

added tab position option

---

docs/components/dropdown/README.md
lib/components/dropdown-header.vue
lib/components/index.js

Adds a  `dropdown-header` component:
```html
<b-drop-down>
<b-dropdown-header>Header using h6 (dafault)</b-dropdown-header>
<b-dropdown-item>Some Item</b-dropdown-item>
<b-dropdown-header tag="h5">Header using h5</b-dropdown-header>
<b-dropdown-item>Some other Item</b-dropdown-item>
<b-drop-down>
```

Add dropdown-header component

---

lib/components/button.vue
lib/components/dropdown-item.vue
lib/components/link.vue

I noticed that `dropdown-item`s were not reflecting the disabled state. See this fiddle for an example: https://jsfiddle.net/oeotafg1/2/
This PR adds in disabled handling in `b-dropdown-item`, `b-link` and `b-button`.
For items rendered as an `a` tag, it also prevents the click handler from firing, making it truly disabled.
Check it out and see if it makes sense.

Disabled  dropdown item fix

---

lib/components/dropdown-divider.vue
lib/components/dropdown-header.vue
lib/components/dropdown-item.vue
lib/components/dropdown.vue
lib/components/nav-item-dropdown.vue
lib/mixins/dropdown.js

Adds in keyboard navigation to dropdown menus (and navbar dropdowns), suitable for both keyboard-only users and screen reader-users.
Keyboard handling based on boostrap's V4 code for dropdown at:
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js
and closely follows the W3 ARIA best practices standard:
https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_within
This works similar to native `<select>` elements and OS menus:
- When the menu is opened, the first `.dropdown-item` or `.dropdown-header` is focused (`.dropdown-divider`s are ignored)
- Pressing cursor up/down will navigate the enabled menu items. Disabled items will be skipped.
- Pressing `ESC` while the menu is open/focused will close the menu and return focus to the menu toggle button.
- Hitting `TAB` while …

Dropdown ARIA keyboard nav

---

lib/components/carousel-slide.vue

Two fixes here for b-carousel-slide:
- The class carousel-caption was used even when caption was not set. Now it checks for it.
- The association of d-none and d-md-block used to make the content disappear on small viewport. This is taken from bootstrap's documentation and was intentional in there. The intent was to hide the *caption* on small viewport. As it's very specific and also affects the content I removed it. If you want the intended behaviour back I can work on it.

b-carousel-slide: Trim down classes

---

lib/components/jumbotron.vue

Adds Boolean prop `container-fluid` to allow for fluid container inside jumbotron
http://v4-alpha.getbootstrap.com/components/jumbotron/

Allow container-fluid inside jumbotron

---

lib/components/dropdown-item.vue
lib/mixins/dropdown.js

Better workaround for #284, which handles closing the dropdown when the clicked `<router-link>` is also the current route.
Previous iteration of this fix used a `$route` watcher. This uses the `@click.native="click"` handler to listen for the click event.  `@click="click"` is still needed for non `<router-link>` dropdown items
This solution appears a bit cleaner,
Hacked together example: https://jsfiddle.net/tmorehouse/fv6btm53/

Better dropdown router-link click handling

---

lib/components/form-fieldset.vue
lib/components/form-input.vue

Allows form-input to be rendered as a `p.form-control-static` via the addition of a new Boolean prop `static` (default `false`)
Switching the prop `static` to `true` will re-render the input as a bootstrap `form-control-static`:
```html
<p id="..." class="form-control-static ...">
formatted value
</p>
```
Changing `static` back to `false` will re-render the original input element. Handy if you need to "lock" an input, but don't want to do a bunch of `v-if`s  (and don't like the bootstrap disabled/readonly stylings).

Form input:  Add form-control-static support

---

lib/components/nav-item-dropdown.vue

The use of v-html on the element wrapping the text slot prevents
it from being used, even when v-html is bound to null. Move the
v-html to a span inside the slot to fix.

Fix text slot on nav-item-dropdown.

---

lib/components/carousel-slide.vue

I didn't meet the timeline I promised but here is the feature you requested!
I went for the most descriptive property name I could think of. If you want me to put `visible-size` as you suggested feel free to ask and I'll change it.
The setting is given for each slide. This may be unoptimal performance-wise but the implementation is very straightforward and, would a user want it for some reason, it allows to set different sizes for different slides in the same carousel.
Also, if you explain to me how to edit the documentation, I'd be happy to do so.

b-carousel-slide: Hiding content for some viewport

---

lib/components/modal.vue

Revert back the change from https://github.com/bootstrap-vue/bootstrap-vue/commit/eaf42348ea3808f290c75ef0a662d6685d55a598 and its previous commit.
I don't know what was the rationale for setting `!important` but it definitely caused a bug.
The modal's div was indeed hidden but overlayed the whole page content as `display` couldn't be set to `none`. In my particular case it caused every mouse input over it to be silently captured. This is one of the unintended behaviours it may have caused.
Paging @mosinve to discuss this.

b-modal: Remove !important in display: block

---

examples/modals/demo.js

The `clearName()` method is declared but not used.

Declared but Unused Method

---

lib/components/modal.vue

Moved focusFirst to run when enter transition is complete.
Tests to ensure focusable element exists and can be focused.
Addressing issue #352

[modal] focusFirst timing tweak

---

lib/components/dropdown-item.vue

[dropdown-item] Explicit component reference (fixes #360)

---

lib/components/pagination.vue

Added ARIA attributes:
- `aria-label`
- `aria-current` (set to `"true"` on the current page button)
- `aria-posinset` reflects the page number the button represents
- `aria-setsize` reflects the total number of pages (appears on each button with an `aria-posinset`)
Enabled keyboard navigation of buttons:
- `LEFT` focus previous button
- `RIGHT` focus next button
- `SHIFT+LEFT` will focus first non-disabled button
- `SHIFT+RIGHT` fill focus last non-disabled button
- When pagination widget is tabbed into, the current page button is focused
New props for localisation of button `aria-label`s:
- `labelPrev` defaults to `'Previous Page'`
- `labelNext` defaults to `'Next Page'`
- `labelPage` defaults to `'Page'`. used on page number buttons (i.e. "Page 1", "Page 2", etc)
- `ariaLabel` will …

[pagination] ARIA attributes + Keyboard navigation

---

lib/components/link.vue

In some cases one would like to have both regular links (i.e. links to an in-page ID) and router links (routed by vue-router).
If `to` is not specified, then assume a regular local link (not handled by router).
Addresses #362 and #363  (I think... discussion is welcome)

[link] Allow both router links and regular links to co-exist in same document

---

lib/components/button-group.vue

A couple of capslock typo fixes.

[button-group] Toolbar keynav fixes

---

lib/components/button-group.vue
lib/components/button-toolbar.vue
lib/components/index.js

Wrapper component for creating toolbars comprised of button-groups and/or input-groups.
Direct children elements should be `b-button-group` and `b-input-group` components.
Allows for optional keyboard navigation by setting prop `keyNav` to `true` (defaults to `false`)

New component b-button-toolbar

---

lib/components/pagination.vue

Computed properties cannot take arguments. As-is, pagination
component is entirely broken and will not render.

Make isActive a method.

---

lib/components/modal.vue

This allows focus to be set in @shown handler of a modal without
the focusFirst handler overriding.

[modal] Do not change focus if activeComponent is in modal content.

---

lib/components/table.vue

Allow user to enable duplicating table thead in tfoot (prop `footClone`
ARIA attributes on header
Additional table style options, and header/footer style variants

[table] allow tfoot clone of thead + ARIA for sorting

---

lib/components/modal.vue

There are no issue about it (but i think we can discus this little fix here)
The chain of events in hide method of modal now looks like this:
`click smth (ok / cancel) -> trigger(change, hidden) -> trigger(ok/cancel)`
It means that 'hidden' (or 'change') is triggered even before we start to process the 'ok' or 'cancel' methods. (so if we e.cancel() in ok, we will anyway see hidden trigger)
After commit it will be work in this way:
`click smth (ok / cancel ) -> trigger(ok / cancel) -> trigger(change) -> trigger(hidden) (if event not canceled)`
Also, can i add "beforechange" emit, that triggers before "ok" / "cancel" ?

modal: change event order

---

__tests__/components/table.spec.js
__tests__/helpers.js
docs/components/table/README.md
docs/components/table/meta.json
examples/table/demo.html
examples/table/demo.js
lib/components/table.vue

Adds async provider function support (callback and Promise based)
Deprecates `items-provider` in favour of passing function to `items` prop
Adds scoped slot support for table header and footers
Added `busy` prop for triggering table "busy" state (via `aria-busy="true" attribute).
Emits `head-clicked` event when header cells are clicked (when not busy), and a `refreshed` event when the provider function has completed/resolved.
Added `sort-changed` event when sorting criteria has changed
Added extra documentation.
A working prototype example can be found here: https://jsfiddle.net/dyzs5txk/ (complete with header/footer scoped slots). You can select how the items are provided to `b-table` (view the console for the various stages of data retrieval). The example requires a browser that …

[table] Async providers, events, and enhancements

---

__tests__/components/breadcrumb.spec.js
lib/components/breadcrumb.vue

Removed role="navigation" per https://github.com/bootstrap-vue/bootstrap-vue/issues/333#issuecomment-309303101
Added `aria-current` attribute on active item. Allow user to specify `aria-current` value via prop (defaults to `"location"`)
Updated unit tests to reflect changes

[breadcrumb] ARIA changes

---

lib/components/modal.vue

Provides more robust element visibility checks.
May address issue #537 (where user has hidden the modal content tabs button via style sheet)

[modal] better element visibility checking

---

docs/components/form-file/README.md
lib/components/form-file.vue

Allow user to reset() `b-form-file` to clear the file input without resetting the entire form
Workaround for issue #493 
Users can call the component's `reset()` method to clear the input, by making a reference to the component:
i.e. `this.$refs.fileinput.reset()`
Includes workaround for IE 10 (file inputs are read-only on IE 8 to IE 10) https://stackoverflow.com/a/35323290/2744776

[form-file] reset() method for clearing file value

---

lib/components/button.vue

Adds new prop `type` which defaults to "button".
Only applied if neither `href` or `to` prop are provided.
Addresses issue #548

[button] Add support for button type attribute

---

package.json

This is trivial PR
The Yarn is not explicit dependency to the library.
Users are free to user Yarn or NPM, but adding Yarn into script made
it dependency. This fixes this issue while still offering both solutions to the users.
Thanks!

Remove implicit Yarn dependency

---

lib/components/navbar.vue

The sticky property could/should be just a boolean, now you have to type `sticky="blalal"` but just `sticky` should be sufficient. Looking at the bootstrap docs there is no other implementation then `sticky-top` at the moment.

[navbar] sticky property should be a boolean, not a string

---

lib/components/tooltip.vue

Adds class `d-inline-block` to the outer wrapper and trigger element wrapper as to not interfere with in-line elements/layout.
May address issue #571

[tooltip] fix - inline-block element for wrappers (issue #571)

---

lib/components/modal.vue

Uses new listenOnRoot mixin by @alexsasharegan to ensure `$root` event listeners are removed on destroy

fix(modal): use listenOnRoot mixin

---

docs/components/form-fieldset/README.md
docs/components/form-fieldset/meta.json
lib/components/form-fieldset.vue

Add named slot support for label, feedback, and description.
Deprecate `label-size` in favour of `label-cols`
Will help prevent confusion of size (being columns, not text size), as per issue #594
Addresses issue #597

feat(form-fieldset): label, description, and feedback slots, deprecate label-size

---

docs/nuxt/components/componentdoc.vue
docs/nuxt/pages/docs/components/_component.vue

Moved b-card from `componentdoc.vue` to `_component.vue`, so that it will only appear once per page, rather than one per component (for multi-component pages)

feat(docs): Native event capturing docs

---

docs/components/form-input/README.md
lib/components/form-input.vue

Adds `aria-invalid` attribute support to `b-form-input`
Addresses issue #546

feat(form-input): support aria-invalid attribute

---

docs/components/form-input/README.md
docs/components/form-radio/README.md
lib/components/form-radio.vue

Adds  a new prop `invalid` to control the `aria-invalid` attribute

feat(form-radio): Add support for aria-invalid

---

docs/components/form-select/README.md

Typos have no place in a readme.

fix(docs): form-select docs typo fix

---

lib/components/form-checkbox.vue
lib/components/form-radio.vue

Some browsers, when a user has pressed the back button the checkboxes and radio might get pre-checked when they shouldn't be.  Adding `autocomplete="off"` to the radio and checkboxes prevents this behavior.

fix(form-radio, form-checkbox): Set autocomplete off

---

lib/mixins/form-options.js

fix(form-options mixin): Pull out custom text field for object notation

---

docs/components/form-checkbox/README.md
lib/components/form-checkbox.vue

Fix for issue  #623
`isChecked` computed prop now tests for array (multiple checkboxes bound to same `v-model`) or non-array (single checkbox bound to `v-model`)
Added extra documentation as well

fix(form-radio): isChecked to work with arrays & non-arrays.

---

lib/components/form.vue

Fix for issue #588
Prevent the need to use `.native` modifier markup on submit event.

fix(form): Emit native submit event on component

---

docs/nuxt/layouts/docs.vue

Fixes  #639
"Edit this page" link broken for /docs/setup
Also when on '/docs/components/' links to erroneous `/docs/components//README.md`

fix(docs.vue): Fix link to edit setup doc

---

lib/directives/scrollspy.js

Adjustments to the resizeThrottle scheduler and additional scheduled event just in case elements are not in document yet.
This may help when elements/components are take out of document and later placed back in, and also recalculate offsets on resize.

fix(scrollspy): Adjustments to the resizeThrottle scheduler

---

lib/directives/_target.js
lib/directives/modal.js
lib/directives/toggle.js

sketch to test:
<div>
<p>
<b-btn v-b-toggle.collapse1 variant="primary">Toggle Collapse</b-btn>
</p>
<p v-b-toggle.collapse1 >
i can open collapse too
</p>
<b-collapse id="collapse1">
<b-card>
Collapse contents Here
</b-card>
</b-collapse>
</div>

feat(toggle directives): allow simple elements to use directive

---

docs/components/table/README.md
docs/components/table/meta.json
lib/components/table.vue

Addresses issue #650 
When local filtering causes the number of pages to change, emits a `repaginate` event with a single argument of the total number of records after filtering (and before pagination slices the data).
Can be used to re-set an associated `<b-pagination>` so that it adjusts to the new number of pages.
This PR includes documentation of the new event in `meta.json`, and updates live example in docs

feat(table): Emit event when local filtering changes number of result items - issue #650

---

docs/nuxt/components/componentdoc.vue
nuxt.config.js

Reduces the amount of padding in the tables to make more information fit on the screen at once (less scrolling)
This is just a personal taste, but I find it more pleasing to the eye when reading.
Feel free to comment :smile:

docs: render markdown, props, events, slots tables with class 'table-sm'

---

__tests__/components/table.spec.js
lib/components/table.vue

Roles `grid` and `row` are implied automatically by current table semantic markup, and not necessary.
Based on chrome Accessibility Plugin Audit  of renderd `<b-table>`.

fix(table): Remove redundant ARIA roles from b-table

---

docs/nuxt/pages/docs/components/_component.vue

fix(docs): Fix typo in  _component.vue

---

lib/directives/toggle.js

Add an unbind handler to remove root listener.
The handler is stored on the element in a private property
Addresses issue #680

fix(toggle): Remove $root listener on unbind (Issue #680)

---

lib/mixins/listen-on-root.js

Minor adjustment to use a constant to define the private property name used for storing the root listeners array.

feat(listen-on-root): Use a constant for private property name

---

lib/components/tab.vue
lib/components/tabs.vue

Value defaulted to 0, which prevented tab with `active` prop from being shown by default.
Fixes issue #687

fix(tabs): Default current tab to null (issue #687)

---

lib/components/modal.vue

In our project, we needed to launch a secondary modal with some form inputs from a Bootstrap-Vue Modal. Due to the "enforceFocus", this was not possible.
If we make this feature configurable, we can use the <b-modal> also when used with a secondary form modal launched from within the first modal.

feat(modal) Make enforceFocus configurable

---

docs/components/navbar/README.md
docs/components/navbar/meta.json
lib/components/index.js
lib/components/navbar-brand.vue

New component for rendering navbar brand content.
Setting props `to` or `href` will render a `b-link`. 
If both `to` and `href` are not present, then the navbar-brand will be resndered as a `div` by default (configurable via the `tag` prop)

feat(navbar-brand): New component <b-navbar-brand>

---

__tests__/components/collapse.spec.js
docs/components/collapse/meta.json
lib/components/collapse.vue
lib/directives/toggle.js

Use the `collapse`, `collapsing` and `show` classes during transition states (issue #565), aligning more closely with Bootstrap V4.alpha.6 _(**Bonus**: removes need for custom scoped CSS)_
`v-b-toggle` directive now adds or removes `collapsed` class to trigger element based on collapse state, to align with Bootstrap V4 alpha.6 (handy for reflecting state on the button/trigger via CSS)
Addresses issue #565

feat(collapse): apply bootstrap classes during transition stages (issue #565)

---

lib/components/dropdown.vue
lib/components/nav-item-dropdown.vue
lib/mixins/dropdown.js
lib/mixins/listen-on-root.js

Changes the highlighting method of focused items (instead of using `active` class state).
Slight tweaks to the `:hover` and `:focus` states CSS to remove ugly blue-line outline on focus and add slightly darker background color (default BS V4 contrast ratio is waaay too low to notice the hover/focus state)

fix(dropdowns): Change how dropdown items are highlighted

---

docs/components/form-checkbox/README.md
lib/components/form-checkbox.vue

Adds support for visual `indeterminate` state of checkbox via the prop `indeterminate`.
This prop can be synced with the checkbox's `indeterminate` state by using the `.sync` modifier.
Includes updated documentation and examples

feat(checkbox): Add indeterminate state prop

---

__tests__/components/button.spec.js
docs/components/button/README.md
examples/button/demo.html
examples/button/demo.js
lib/components/button.vue
lib/components/navbar-brand.vue

Adds a new prop `pressed`, which defaults to null.
- If `pressed === true` then the `.active` class is added to the button and sets `aria-pressed="true"` attribute.
- If `pressed === false` then  the attribute `aria-pressed="false"` is set.
- If `pressed === null` (the default, or any other value) then neither the class `.active` nor the attribute `aria-pressed` are set.
Useful when creating toggleable buttons.
The pressed state can be synced by setting the `.sync` modifier on the prop:
```html
<template>
<b-btn :pressed.sync="myPressedState">Toggle Me</b-btn>
</template>
<script>
export default {
data: {
myPressedState: false
}
}
</script>
```

feat(button): Add pressed prop to place button in active state

---

lib/components/button.vue

Minor change to focus handler for toggle style buttons.
Uses `@focus(in|out).native` handler now.

feat(button): refactor toggle button focus handler

---

__tests__/components/alert.spec.js
__tests__/helpers.js
examples/alert/demo.html
examples/alert/demo.js
lib/components/alert.vue

Fix for issue #718 
My initial work on the idea of using v-model. I haven't run my bug test on this yet because things are really busy for me. 
**Edit:** This does clear up my bug.
**Note:** ~~This may need to be tweaked as doing `<b-alert show dismissible>` doesn't allow the alert to be dismissed. The addition of `v-model` becomes necessary. It might be necessary to have an initial show either as a prop or as a data value local to alert. But if you think about it, it's fundamentally flawed to declare both `show` and `dismissible` at the same time while also making alerts reusable.~~
Feel free to contribute on this branch.

fix(alert): use v-model to update show value

---

docs/components/form-radio/README.md
lib/components/form-radio.vue

Adds new Boolean prop `buttons` (defaults to `false`) that wil enable the radios to be rendered with the look of buttons.
http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons
Currently the buttons can only be rendered with the same variant specified by the prop `button-variant`.  Different variants for each radio button ar currently not supported (not without altering the `form-options.js` mixin).
`stacked` button radios are supported,, but `state` is not supported for button radios

feat(form-radio): Support button style radios

---

docs/components/form-checkbox/README.md
lib/components/form-checkbox.vue

Support rending checkbox in button style, by setting the prop `button`.
http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons
Button variant style can be set via the prop `button-variant`. Defaults to `secondary`.
`button` prop has precedence over `plain` prop

feat(form-checkbox): Support button style checkbox

---

lib/mixins/popover.js

Addresses issue #735 
Prevents console warning:
`[Vue warn]: Error in beforeDestroy hook: "TypeError: this.$data._trigger.className.replace is not a function" found in ---> <BPopover>`

fix(popover.js): destroy check for trigger & classes (issue #735)

---

docs/components/pagination/README.md
lib/components/pagination.vue

Adds ew prop `align` which allows the pagination to be `left`, `center`, or `end` (`right`) alignment.
Default is `left`.

feat(pagination): Add alignment prop

---

docs/components/table/README.md
lib/components/table.vue

Adds two new props to allow user to specify sorting column and direction.
The new props can be made two way by adding the `.sync` modifier, and will be updated whenever sorting column or direction changes.
These props complement (or can be used instead of) the `sort-changed` event.
Includes documentation updates

feat(table): Add syncable sort-by and sort-desc props

---

docs/components/form-select/README.md
lib/components/form-select.vue
lib/mixins/form-options.js

Adds multiple select support to form-select (addresses issue #619)
new props:
- `multiple` enabled multiple select support when set to `true`
- `multiple-size` set the number of rows displayed in multiple select. Defaults to browser default size
`form-options.js` mixin updated to support multiple select.
Updated documentation

feat(form-select): Add multiple select support (issue #619)

---

lib/components/form-input.vue

It would be nice to be able to control browsers autocomplete features with an `autocomplete` prop on form inputs.

feat(form-input): Add autocomplete prop

---

docs/README.md
docs/nuxt/assets/css/styles.css
docs/nuxt/components/componentdoc.vue
docs/nuxt/layouts/docs.vue
docs/nuxt/pages/docs/components/_component.vue
docs/nuxt/pages/docs/contributing.vue
docs/nuxt/pages/docs/directives/_directive.vue
docs/nuxt/pages/docs/index.vue
docs/nuxt/pages/docs/setup.vue

Minor adjustment to CSS to target only top level `<H#>` tags within `README.md` so that docs custom CSS does not affect live examples.
Addresses issue #753

fix(docs): Adjust header tags CSS specificity (issue #753)

---

lib/mixins/dropdown.js

Dropdowns were not emitting `hidden` or `shown` events on the component as documented.
Addresses issue #757

fix(dropdown): Emit shown and hidden events (issue #757)

---

lib/components/navbar-brand.vue

After working on documentation for `b-navbar` I discovered a few issues with `b-navbar-brand`. So I have refactored the template and props (and made it work more like `b-button`)

fix(navbar-brand): Refactored component logic

---

docs/components/form-select/README.md
lib/components/form-select.vue

Allows the select native `size` attribute to be set (via the prop `select-size`), even when not in multiple mode.  Only has any effect when `select-size > 1`.  Custom select styling is removed when in `multiple` mode or `select-size > 1`.
Changes `multiple-size` attribute to `select-size` (`multiple-size` was not available in v0.18.0, so deprecation is not needed)
Addresses issue #761

feat(form-select): Allow selectSize to be set when not in multiple mode (Issue #761)

---

lib/components/alert.vue

I think this place maybe forget colon to bind attribute `aria-label` . So I make this PR.

fix(alert): add colon for binding `aria-label`

---

lib/components/carousel.vue

Prevents index from being updated if current slide is transitioning.
Specifically when controls are clicked in quick succession (possible fix for issue #764)

fix(carousel): Prevent going to slide if transitioning (issue #764)

---

lib/utils/BvEvent.js
lib/utils/object.js

Stripped down version of browser `Event` object for use in component events that offer some kind of `preventDefault` behavior implemented by BootstrapVue.
- Adds a `BvEvent` class.
```js
// Inside modal.vue
{
methods: {
handleOkayClick(e) {
this.$emit("ok", new BvEvent("ok", {
nativeEvent: e,
target: e.target,
vueTarget: this,
}))
}
}
}
// Listener
function handleOkay(e) {
if (someCondition) {
// Stops modal from closing
e.preventDefault()
}
}
```

feat(Event): standard evt obj emulates native Event

---

docs/components/form-input/README.md
lib/components/form-input-static.vue
lib/components/form-input.vue

Add second argument of input reference to `formatter` function.
Addresses issue #772

feat(form-input): Pass input element to formatter (issue #772)

---

docs/components/table/meta.json
lib/components/table.vue

Emit a `row-dblclicked` event when a row is double clicked.
Event has same argument signature as `row-clicked`

feat(table): Add row-dblclicked event

---

docs/components/form-input/README.md
docs/components/navbar/README.md
docs/components/table/meta.json
lib/components/form-radio.vue
lib/components/table.vue

"navbar" was misspelled "narbar" in a number of places in the Navbar documentation. This fixes those typos.

Fix "narbar" typo in Navbar docs

---

docs/components/alert/README.md
examples/alert/demo.html
lib/components/alert.vue

When rendering an auto-dismissing alert, hide the dismiss button.
Quick workaround for issue #718

feat(alert): Hide dismiss button for auto-dismissing alerts

---

lib/components/form-radio.vue

Better focus handling when in buttons mode

fix(form-radio): Better focus handling in button mode

---

lib/components/collapse.vue

Closes the collapse when link/dropdown-item clicked in nav/navbar mode.
Addresses issue #712

fix(collapse): Close collapse when clicked in navbar (Issue #712)

---

docs/components/card/README.md
examples/card/demo.html
lib/components/card.vue
lib/components/carousel.vue
tests/components/card.spec.js

Adds new prop `bordered` to gt a bordered variant (replaces outline variants)
Needs test suite (and demo.html) to be updated to handle expected class names (test currently fail)

fix(card): Fix classes, variants, borders [v4-beta]

---

package.json

I am getting this output, while installing:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "jquery@>=3.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

fix: jquery dependency version in package.json

---

lib/components/dropdown-header.vue
lib/components/dropdown.vue
lib/components/nav-item-dropdown.vue
lib/mixins/dropdown.js

Prevent two items from visually having the focus/hover states.
Also removed focusing of dropdown-header elements, as per discussion in https://github.com/twbs/bootstrap/issues/23336 (users should add an `aria-describedby` attribute on dropdown-items that point to their header element, if the dropdown-item needs context from the header)
Also name-spaced custom CSS (adding class `.b-dropdown` and `b-navdropdown` on the root elements)

fix(dropdowns): Focus dropdown item on hover

---

docs/components/alert/README.md
lib/components/alert.vue
tests/components/alert.spec.js
tests/fixtures/alert/demo.html

Alert never emitted a `dismiss-count-down` event at zero seconds. This PR remedies that.
Updated docs example
Updated tests

fix(alert): Emit dismiss-count-down at 0 seconds

---

lib/components/pagination-nav.vue
lib/components/pagination.vue

V4.beta has removed the `.hidden-*` classes, so we must use the `.d-*` classes for hiding on XS screens.
For pagination and pagination-nav we replaced `.hidden-sx-down` with `.d-none` + `.d-sm-flex`

fix(pagination): Change classes from .hidden-* to .d-*

---

docs/components/form/meta.json
lib/components/form-text.js
lib/components/index.js
tests/components/form-text.spec.js
tests/fixtures/form-text/demo.html
tests/fixtures/form-text/demo.js

New `b-form-text` (AKA form-help) functional component
Defaults to tag `<small`> and `text-muted` variant
Can be placed in inline mode (`inline` prop) which removed the `.form-text` class

feat(form-text): New functional component

---

package.json

Change dependency from `^4.0.0.alpha.6` to `4.0.0.alpha.6`
As there are no further alpha releases

fix(package.json): Set bootstrap dependency to 4.0.0.alpha.6

---

lib/components/form-checkbox.vue
lib/components/form-file.vue
lib/components/form-group.vue
lib/components/form-input.vue
lib/components/form-radio.vue
lib/components/form-select.vue
lib/components/form-textarea.vue
lib/mixins/id.js

This is a client side only ID generator, which supplies an ID attribute on form control when no ID prop is provided.
ID generation only runs on client side, during the mounted() hook (after SSR rehydration, if applicable).
The presence if IDs, even if not in the initial SSR rendered HTML will greatly improve accessibility.
Other components that can take advantage of IDs (i.e. dropdowns, carousel, etc) can use the new `id.js` mixin

feat(forms): Auto ID generation client side if no id prop provided

---

docs/components/progress/README.md
docs/components/progress/meta.json
lib/components/form-input.vue
lib/components/index.js
lib/components/progress-bar.vue
lib/components/progress.vue
tests/fixtures/progress/demo.html

Adds support for multiple progress bars by introducing a new `b-progress-bar` sub component.
sub component b-progress-bar will inherit many of the props from the parent b-progress component, but my be overridden at the sub component level.
PR includes updated docs and examples

feat(progress): Support for multiple progress bars

---

docs/components/table/README.md
lib/components/table.vue

A `1.x` version of PR #881 
Add automatic busy state during items provider updating, as well as 2-way sync status of the `busy` prop

feat(table) busy state self-handling

---

docs/components/table/meta.json
lib/components/table.vue
tests/components/table.spec.js

Adds native event object as last arg for the row-* and head-* events
Addresses issue #855

feat(table): Include native event object with row-* and head-* events

---

lib/mixins/dropdown.js

fix(dropdown.js): import clickout as a mixin

---

docs/components/alert/README.md
docs/components/alert/meta.json
lib/components/alert.vue

Also adds v-model support for `show` prop and named slot for close button content

fix(alert): Fix auto-dimissing alert "bug"

---

docs/directives/scrollspy/README.md
lib/directives/scrollspy.js

Before, elements with class `.nav-link` had a compoent VM on their parent element, but `nav-link`s no longer have  associated VMs, so we set the `active` class directly on them rather than setting the prop on the parent element VM

fix(scrollspy): Make work with new nav-link functional component

---

lib/components/tab.vue

fix(tabs): Show first tab when set to active

---

docs/components/table/meta.json
lib/components/dropdown.vue
lib/components/table.vue

Allows user to provide `TD` cells across the top and/or bottom of the table.  The user must supply the correct number of `TD` cells (or `TD`s spanned to the correct number of columns)
Scoped slots are 'top-row' and 'bottom-row'.  Both slots (rendered inside a `TR`)receive two properties on the scoped data variable: `columns` (number of `TD` cells the user needs to render) and `fields` (a reference to the fields object)
Addresses issue #682

feat(table): Scoped slots for fixed top/bottom rows

---

docs/components/dropdown/README.md
lib/components/dropdown.vue
lib/components/nav-item-dropdown.vue
lib/mixins/dropdown.js

Migration of dropdown and nav-item-dropdown to use popper.js
Migration wasn't too bad.  a couple of new optional props (`offset` & `no-flip`), but I was able to make it work with our existing props (`dropup` & `right`)
By design, popper is disabled for menus in navbars (because of collapsing behavior of navbars)

fix(dropdowns): Migration to popper.js positioning

---

lib/mixins/dropdown.js

IF Popper.js not found, fallback gracefully to dropdown that is always dropdown, left aligned, with no positioning available

fix(dropdowns): Allow gracefull fallback if Popper.js not defined

---

docs/components/table/README.md
lib/components/table.vue
lib/utils/identity.js
lib/utils/lowerFirst.js
package.json
yarn.lock

While working on tables on some quick cases, the current API is little hard to use and some times there are really some extra works for easy tasks (like changing column titles for each field or even when need a quick representation of data) The solution was using computed props.
Example of new usage:
```vue
<template>
<b-table :items="logs"/>
</templte>
<script>
export default {
data: () => ({
logs: [
{log_type: 'CHECK_IN', deviceId: '123', user: 'A'},
{log_type: 'CHECK_OUT', deviceId: '44', user: 'B'},
{log_type: 'CHECK_IN', deviceId: '3343434', user: 'C'}
]
})
}
```
Renders:
Actually, with example above, fields is auto sampled from first record and it's column names are auto formatted using [startCase](https://lodash.com/docs/4.17.4#startCase)
Fields property can now be either an array …

[wip] feat(table): easier usage

---

docs/components/carousel/README.md
docs/components/carousel/meta.json
lib/components/carousel-slide.vue
lib/components/carousel.vue
lib/components/img.js

Incorporate the new `<b-img>` component into `<carousel-slide>`, to allow for easy blank image creation (for maintaining a text only slides aspect ratio)
Incorporate the `id` mixin to auto ID the carousel client side (on mount) if no IDs are provided.
Additional props for setting image sizes.
Updated docs

feat(carousel): Use b-img component and id Mixin

---

lib/components/tab.vue

There is a small type for the attribute `:aria-labelledby`.

fix(tab): typo aria-lablelledby

---

lib/classes/tooltip.js

fix(tooltip): ToolTip.fixTransition undefined value

---

lib/directives/scrollspy.js

Fixes missing reference to `vnode` on initial bind()
Addresses issue #963

fix(scrollspy): Undefined value during bind()

---

lib/components/popover.vue
lib/components/tooltip.vue

Instantiates tooltip/popover on `this.$nextTick(..)` to help ensure trigger element and component are in dom.
Should address issue #968

fix(tooltip+popover components): Delay instantiation on mounted()

---

lib/classes/tooltip.js

fix(tooltip+popover): Hide original element title attribute

---

docs/directives/popover/README.md
docs/directives/tooltip/README.md
lib/classes/tooltip.js
lib/directives/popover.js
lib/directives/tooltip.js

Handy if you want to show tooltip or popover only on `click`, but want to close it on click anywhere in the document (i.e. trigger element loses focus)

feat(tooltips+popovers): Add special blur "exit" trigger

---

lib/classes/tooltip.js
lib/components/popover.vue
lib/components/tooltip.vue

If trigger element becomes hidden (such as in a `<keepalive>`, `<b-tabs>`, etc.), then force hide the tooltip or popover, so that it doesn't linger on the screen (fade animation will be disabled).
This is achieved by adding a visibility watcher that runs every 100ms.  The watcher only runs when the tooltip/popover is visible.
The `hide` event is still emitted, but cannot be cancelled.
Also changed the component version to use the `beforeDestroy()` hook instead of the `destroyed()` hook to remove tooltip/popover, preventing some Vue console log errors and warnings

feat(tooltips+popovers): Automatically hide when trigger element is no longer visible

---

docs/components/popover/README.md
docs/components/tooltip/README.md
lib/components/popover.vue
lib/components/tooltip.vue

For component version of tooltip and popover, allow target to be given as an element or component reference, besides a string ID.
Deprecates the `target-id` prop

feat(tooltip+popover): Allow element and component reference for target

---

docs/components/popover/README.md
docs/components/tooltip/README.md
lib/components/popover.vue
lib/components/tooltip.vue

Adds a new `container` prop to the component version of tooltip and popover, to all user to specify which container to append tooltip/popover to.
Container is specified as an element ID string. if not specified (null), then body is used (default)

feat(tooltip+popover): Add container prop to component versions

---

lib/components/carousel.vue

requesting `el.offsetHight` is needed to trigger a reflow of an element in some browsers. transpilation was optimizing this statement out of the dist compiled files.
This fix should hopefully prevent that from occurring.
Fix for issue #993

fix(carousel): Prevent reflow trigger from being optimised out

---

docs/components/modal/README.md
lib/components/modal.vue

This provides an easy way to have other variants than primary for Ok and secondary for Close without creating a custom modal footer

feat(modal): Add props to change the variant of the default modal buttons

---

docs/components/popover/README.md
docs/components/tooltip/README.md
docs/directives/popover/README.md
docs/directives/tooltip/README.md
lib/classes/tooltip.js

Optimized adding/removing of events.
Only listen/watch to certain events while the tooltip/popover is open
Adds listener for `bv::hide::(popover|tooltip)` event on root to allow user to close all popovers or tooltips via emitting on $root.
address issue #1002

feat(popover/tooltip): Add hide listener on $root events

---

docs/components/table/README.md
lib/components/table.vue
tests/components/table.spec.js

Formatter now doesn't alter item records, allowing a revert back to basic array.slice() shallow copy of items (for speed).
Slight change in how field custom format slots work.  Formatted value is passed to slot as `value`, and unformatted  value as `unformatted`. `item` is the raw row data (no formatted/overwritten values). If no formatter is provided `value` will be the same as `unformatted`.
Basic HTML is supported as output of formatter (no components).
`sort-compare` function will now fall back to built-in defaultSortCompare routine if `sort-compare` returns `null`, allowing users to handle only special case fields in their custom `sort-compare` routine.

feat(table): Refactor field formatter support + optimized sort-compare handling

---

lib/classes/tooltip.js

Addresses issue #1005 
This fix removed the check for `e.target === this.$element`

fix(tooltip+popover): Click not triggered for elements with inner HTML elements in Chrome/WebKit

---

lib/components/popover.vue
lib/components/tooltip.vue
lib/mixins/index.js
lib/mixins/toolpop.js

Migrated common props and methods to mixin for tooltip and popover components.
Also moved storage of tooltip/popover instance to a non-reactive property
Should help reduce final library file size

feat(tooltip+popover): Create mixin for common props and methods

---

package.json

`b-table` requires `lodash.startcase`
Re: issue #1028

fix: Add lodash.startcase to dependancies

---

docs/components/button/meta.json
docs/components/modal/README.md
docs/components/modal/meta.json
lib/classes/popover.js
lib/classes/tooltip.js
lib/components/alert.vue
lib/components/button-close.js
lib/components/index.js
lib/components/modal.vue
lib/directives/modal.js
lib/utils/dom.js
tests/fixtures/modal/demo.html
tests/fixtures/modal/demo.js

Various modal improvements:
_Note: current Bootstrap V4.beta.1 CSS causes header and footer to loose rounded corners when a background variant is applied. This PR includes a fix for that using the `rounded-*` classes_

feat(modal): Improve modal transitions, padding adjustments, and aditional features

---

lib/components/form-file.vue

`b-form-file` doesn't have any focus styling when in custom input mode, which makes it difficult for keyboard-only users to know that the file input has focus.
This fix handles this (using scoped CSS), and also adds better accessibility features in general to `b-form-file`
Addresses issue #333 
The scoped CSS use hard-coded color styles, which could be updated to use SASS variables/mixins to adjust the colors used.

feat(form-file): Add focus styling for custom-file input

---

lib/classes/tooltip.js

Prevents illegal invocation errors when tooltip or popover inside `v-if`'ed elements.
Fixes issue  #1032

fix(tooltip popover): illegal invocation errors when tooltip inside v-if elements

---

lib/components/form-checkbox-group.vue
lib/components/form-checkbox.vue
lib/components/form-radio-group.vue
lib/components/form-radio.vue

The parent wrapper form-radio-group and form-checkbox-group weren't emitting the change event triggered by the child components
Will address #1070 as well

fix(radios checkboxes): Parent group should emit change event

---

lib/components/pagination-nav.vue
lib/components/pagination.vue
lib/mixins/index.js
lib/mixins/pagination.js

Moves common code used in `<b-pagination>` and `<b-pagination-nav>` into a mixin

feat(pagination): Move common code to pagination mixin

---

docs/reference/images/README.md
docs/reference/images/index.js
docs/reference/index.js

Currently vue-loader/webpack only translate project relative asset URLs for `<img>` tags.
This brief document explains how to configure the `transformToRequire` vue-loader option to transform image SRC tags for Bootsrtap-Vue's components that accept image URLs via props.
Feel free to edit the docs.

feat(docs): New reference section wrt project relative urls and image based Bootstrap-Vue components

---

docs/components/table/README.md
docs/components/table/meta.json
docs/nuxt/components/componentdoc.vue
lib/components/table.vue

While most browsers store object keys in the order they were defined, this is not always guaranteed.
This change allows fields to be passed as an array of field objects, to ensure desired field order.

feat(table): Allow fields to be an array of objects

---

docs/components/table/README.md
docs/components/table/meta.json
lib/components/table.vue

Adds new prop `fixed` to render table with equal fixed-width columns.
Adds new prop `no-local-sorting` to disabled local sorting (useful when items is an array and user wants to sort externally)
Emits event `contenxt-changed` with `ctx` object as arg whenever the context of the table changes
Slight adjustments to styling for better sort indicator alignment

feat(table): New fixed prop, allow disable localSort, emit context-changed event, and style tweaks

---

docs/components/popover/README.md
docs/components/tooltip/README.md
docs/directives/popover/README.md
docs/directives/tooltip/README.md
lib/classes/tooltip.js
lib/directives/popover.js
lib/directives/tooltip.js
lib/mixins/toolpop.js

Besides the usual `left`, `right`, `top` and `bottom`, the following 8 new placements are now available:
`topleft`, `topright`, `bottomleft`, `bottomright`, `lefttop`, `leftbottom`, `righttop` and `rightbottom`
Supported in both directive and component versions.
Aligns with the new proposed placements in Bootstrap V4.beta.2

feat(tooltip+popover): Eight new placement options

---

docs/index.js
docs/nuxt/components/toc.vue

This keeps all site navigation information in a single obejct/file, making for easier maintenance when adding or removing sections.

docs(toc): Move toc object to site nav object

---

docs/components/form-input/README.md
lib/components/form-input.vue
tests/fixtures/form-input/demo.html

Trigger `input` event event when lazy-formatter is set to true. Addresses issue #1085
Also adds proper styling to color and range inputs

feat(form-input): fire input event when lazy-formatter is true

---

lib/classes/tooltip.js

I was wondering why `this.$root.$emit('bv::hide::tooltip')` wasn't working and found this typo.

fix(tooltip): Emit correct $root event name

---

lib/classes/tooltip.js

Only applies when the trigger is set to `focus` and/or `blur`
Handy when using interactive popover content

feat(tooltip popover): Don't close if focus moves between trigger element and tip/popover

---

docs/reference/sizes/README.md

Changed `text-ceter` to `text-center`.

docs(sizes): typo fix

---

docs/nuxt/components/search.vue
docs/nuxt/components/sidebar.vue
docs/nuxt/pages/docs/components/_component.vue
docs/nuxt/pages/docs/directives/_directive.vue
docs/nuxt/pages/docs/docs-mixin.js
docs/nuxt/pages/docs/index.vue
docs/nuxt/pages/docs/layout/index.vue
docs/nuxt/pages/docs/misc/_misc.vue
docs/nuxt/pages/docs/reference/_reference.vue

Auto focuses the first header when a route changes and no hash specified
Auto Scrolls to header specified by hash if found, accounting for navbar offset.

feat(docs): Better ARIA when changing routes

---

lib/components/button.js

A user supplied `tabindex` attribut on `b-button` was being overwritten as `null`
This fix preserves the users original tabindex when not disabled
Addresses issue #1119

fix(button): Don't ovrwrite user supplied tabindex if not disabled

---

lib/components/nav-item-dropdown.vue

I couldn't use disabled on b-nav-item-dropdown, because it breaks in toggleClasses computed property. This should fix it. I tested locally using the Playground and it works.
Thanks for this great project!
Amir

Bug: In toggleClasses we expect strings instead of undefined variables.

---

docs/components/popover/README.md
docs/components/tooltip/README.md
lib/mixins/toolpop.js

The `delay` prop now optionally accepts an object in the form `{ show: 123, hide: 123}` to specify the show and hide delays individually.
Addresses issue #1130

feat(tooltip+popover): Allow delay to be object in component versions

---

docs/components/form-input/README.md
docs/components/popover/README.md
docs/components/table/README.md
docs/components/tabs/meta.json
docs/reference/variants/README.md

This commit corrects all misspellings of "the" in the docs.

fix(docs): Correct "the" misspellings

---

lib/components/input-group.vue

Remove unnecessary prop `state` from `b-input-group`

fix(input-group): BS V4.beta CSS no longer has the `has-${state}` classes

---

docs/components/table/README.md
docs/components/table/meta.json
lib/components/table.vue

New prop `caption` and slot `table-caption` for placing content in the table's `<caption>` element.
If neither the prop nor slot are specified, the caption element is not rendered.  The slot takes precedence over the prop.
New slot `table-colgroup` to allow placement of `<colgroup>` and `<col>` elements for more table styling control

 feat(table): Add table caption and colgroup support

---

docs/components/form-group/README.md
lib/components/form-group.vue

Fieldset + label automatically associates with any containing input element.
Also provides better ARIA support when there are multiple inputs (i.e. radio's and checkboxes) in a form-group

feat(form-group): Switch to fieldset+legend for better semantic/ARIA markup

---

docs/components/table/README.md
docs/components/table/meta.json
lib/components/table.vue

Adds new scoped slot `row-details`, and special item record property `_showDetails`, when used in combination will display a "details" row below the item row.  Refer to the update docs for usage and example.
Addresses issue https://github.com/bootstrap-vue/bootstrap-vue/issues/1158#issuecomment-334036004

 feat(table): Add toggleable row details support 

---

lib/components/modal.vue
lib/utils/dom.js

Use case: If a modal is open on a child route and the route is changed, the modal is closed (destroyed), but body scrollbar and navbar/fixed content adjustments (margins/padding) were not being removed.
Note this PR does not address similar issues when modal is inside a `<keep-alive>` component.
Addresses issue #1167

fix(modal): Ensure body scrollbar is removed if modal destroyed before being closed

---

lib/components/modal.vue

Building on #1058...  If the modal dialog's content height changed (e.g., "v-if" conditionally displayed an error message), the `padding-right` could be applied inconsistently.
twbs/bootstrap#23672 fixed this by calling `this.adjustDialog()` during `onBeforeEnter()`, as well

fix(modal): Modal jumps when dialog height changes

---

lib/components/modal.vue

When modal is set to `lazy`, the entire modal is `v-if`'ed out of the document.
This remove's any `$refs` that the user may have of the modal which may prevent them using the `.hide()` and `.show()` methods,
This PR wraps the modal in one extra `<div>` to keep the `$ref` defined.
Addresses issue #1166

fix(modal): Add outer wrapper div to that lazy modal's will still have a $ref when hidden

---

docs/components/modal/README.md

Fixes `clas` typo in first code snippet

Fix typo in modal README

---

docs/components/table/README.md
lib/components/table.vue

Hi,
This pull request allows us to add additional attributes to a `<td>` cell in `<b-table>`
We are converting a plain html table to use `<b-table>`. It's responsive, such that on small screens, the table header is hidden and we use the following css for the td cells
```css
td {
display: block; border:none; padding:6px 10px;
&:first-child {padding-top: .5em;}
&:last-child {padding-bottom: .5em; border-bottom:1px solid #e8e8e8; padding-bottom:15px;}
&:before {
content: attr(data-th)": ";
font-weight: bold;
width: 6.5em; // magic number :( adjust according to your own content
display: inline-block;
@include media-breakpoint-up(md) {
display: none;
}
}
}
```
essentially, placing the header text to the left of the cell and turning the table into a vertical list. it works quite well for our …

feat(table): allow custom attributes in table td cell

---

docs/components/dropdown/README.md
lib/components/dropdown.vue
tests/components/dropdown.spec.js
tests/fixtures/dropdown/demo.html

Hi
This allows the dropdown toggle to be hidden when the dropdown is not set to split. Useful for when the dropdown is just an icon.
usage
```html
<b-dropdown variant="link" hide-toggle size="sm">
<template slot="button-content">
<icon icon="avatar"></icon>
</template>
<b-dropdown-item @click="$store.dispatch('logout')">Logout</b-dropdown-item>
</b-dropdown>
```
thanks!

feat(dropdown): optionally hide the dropdown toggle caret

---

lib/utils/dom.js

`Element.offsetParent`/`offsetHeight`/`offsetWidth` does not work on `<svg>` elements.
Swtching to `Element.getBoundingClientRect().height` and `.width` gets around this limitation

fix(dom utils): use getBoundingClientRect() to determine element visibility

---

lib/components/progress-bar.vue
lib/components/progress.vue

Move height prop from progress-bar to progress according to current Bootstrap4-beta2.
fixes #1216

fix(Progress): Bootstrap V4.beta.2 CSS height prop change

---

lib/classes/tooltip.js

fix(tooltip+popover): Prevent leftover tooltip/popover divs

---

lib/components/button-group.js
tests/components/button-group.spec.js

Having both btn-group and btn-group-vertical applied causes styling issues under Bootstrap V4.beta.2 CSS

fix(button-group): Bootstrap V4.beta.2 CSS changes

---

lib/components/dropdown.vue
lib/components/nav-item-dropdown.vue

Removed custom CSS for focus/hover styling as Bootstrap V4.beta.2 now has better hover/focus styling, although still not ideal.

fix(dropdown): Bootstrap V4.beta.2 now has better hover/focus styling

---

docs/components/badge/README.md
lib/components/badge.js

Import b-link and associated props to allow support for actionable  badges.
Bootstrap V4.beta.2 provides proper styling for badge classes applied to `<a>` tags.

feat(badge): Support actionable (link) badges

---

docs/components/form-select/README.md
lib/components/form-select.vue

Bootstrap V4.beta.2 now supports custom select styling on selects with the `multiple` attribute set.
Addresses issue #747

fix(form-select): Custom select now supports multiple attribute in V4.beta.2 CSS

---

lib/components/form-input.vue
lib/components/form-textarea.vue

This is an interim fix until BS V4.beta.3 is released: https://github.com/twbs/bootstrap/pull/24486

fix(form-input): BS V4.beta.2 is missing width:100% on readonly plaintext

---

docs/components/table/README.md
lib/components/table.vue
tests/components/table.spec.js
tests/fixtures/table/demo.html

Bootstrap-V4-beta.2 adds responsive breakpoint support (`.table-responsive-{sm|md|lg|xl}`), and changes class `table-inverse` to `table-dark` for "inverse" tables.
For backwards compatibility, the `inverse` prop is still available, but the prop `dark` deprecates `inverse`.
Addresses issue #747

feat(table): BS V4.beta.2 New responsive breakpoints and table-dark class

---

docs/components/nav/README.md
docs/components/navbar/README.md
docs/components/navbar/meta.json
lib/components/index.js
lib/components/nav.js
lib/components/navbar-nav.js

The class 'nav' is no longer used in BS V4.beta.2 when the nav is a navbar-nav.
Introduce a new lightweight functional `<b-navbar-nav>` component.
Deprecate `is-nav-bar` prop on `<b-nav>`

feat(navbar-nav): New b-navbar-nav component

---

lib/components/carousel.vue

This fix keeps the carousel paused while focus (activeElement) remains inside the carousel container.
Addresses the second part of issue #1235

fix(carousel): Minor adjustments to focusout/mouseout event handler

---

package.json

As bootstrap is only needed to build the documentation site, move it back to `devDependencies` from `dependencies`, as the final bootstrap-vue JavaScript dist files import nothing from Bootstrap.
We should update the getting started docs to use bootstrap v4.0.0-beta.2, and possibly a few of the examples too.

fix(package.json): Move Bootstrap back to dev deps and update popper.js version

---

docs/components/modal/README.md
lib/components/modal.vue

Vertically centered modals will be coming in Bootstrap V4
https://github.com/twbs/bootstrap/pull/24510
This adds a new prop `centered` which renders the modal centered vertically.
Note vertically centered modals are **not** suited for tall content modals, as there is a potential for the header (or top part of the modal) to become inaccessible.  They are better suited to one or two line content (i.e. confirmation dialogs).
The custom CSS in modal.vue can be removed once V4.beta.3 (or later) arrives

feat(modal): Add Bootstrap V4 anticipated verticaly centered modal

---

lib/components/card-body.js

Similar to header-class and footer-class when using the integrated b-card-body in b-card.
Addresses issue #1249

feat(card): New prop body-class

---

lib/components/tabs.vue

Applying the `small` class to the parent `ul.nav` rather than the individual `nav-links` allows for proper sizing inheritance of items added to the "tabs" named slot.
Addresses issues #1248

fix(tabs): Apply `small` class to parent `ul.nav`

---

src/components/table/README.md
src/components/table/table.vue

This PR adds a fields scoped data property to the optional row details scoped slot.

feat(table): Pass computed fields array to details scoped slot

---

src/components/form-checkbox/README.md

Changes the spelling of checbox to checkbox in several instances

Fix a Typo in README.md for checkboxes

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
docs/components/search.vue
docs/pages/docs/components/_slug.vue
docs/pages/docs/directives/_slug.vue
src/components/collapse/package.json
src/components/form/form-row.js
src/components/form/package.json
src/components/layout/form-row.js
src/components/layout/index.js
src/components/modal/package.json
src/components/nav/package.json
src/components/navbar/index.js
src/components/navbar/package.json
src/directives/popover/README.md
src/directives/popover/package.json
src/directives/scrollspy/README.md
src/directives/scrollspy/package.json
src/directives/tooltip/README.md
src/directives/tooltip/package.json

Adds a new section to component and directive pages describing individual import and plugin use.
Also reduces documentation bundle size by importing only required functions from lodash

docs: Add info on imports

---

src/utils/dom.js

Move polyfill functions into respective dom utility and avoid polyfilling native prototype

perf(dom): Improve DOM utils code for minification & tree-shaking

---

src/components/tabs/README.md
src/components/tabs/tab.vue
src/components/tabs/tabs.vue

Adds two new props to `<b-tab>`:
- `title-item-class` - gets added to the outer `<li class="nav-item">` element
- `title-link-class` - gets added to the inner `<a class="nav-link>` element
Closes issue #1265

feat(tabs): New props for adding classes to nav tab

---

src/components/button/README.md
src/components/button/index.js
src/components/button/link.js
src/components/button/package.json
src/components/link/README.md
src/components/link/package.json

Adds documentation for the `<b-link>` component,
And makes it available as a basic plugin.  Removes the inclusion of `b-link` in the `button` plugin.

docs(link): Document b-link component

---

src/components/form-file/form-file.vue

Bootstrap currently does not support the form-control-size on form-file input.
Removing both the mixin and the and the class reference.

fix(form-file): control size not supported in BS V4

---

src/components/input-group/input-group.js

Found this issue on >=1.0.0, appeared in commit bd4c3c3.

fix(input-group): correct input-group right addon via prop

---

src/utils/tooltip.class.js

Prevents popovers/tooltip from showing empty content when re-opened after emitting `bv::hide::popover/tooltip`
Issue affected both popovers and tooltips
Closes issue: #1322

fix(popover+tooltip): content not restored after hiding all popover with 'bv::hide::popover'

---

src/components/modal/modal.vue

This fixes #1325, preventing `modal-open` class lost on document body when a new modal opens before the previous one's transition is over.
This sets a new custom class `modal-closing` on body during transition, I am not sure if that's appropriate. It could probably be better to use a flag variable on `this.$root`.

fix(modal): modal-open body class lost when switching between modals

---

src/components/link/README.md
src/components/link/link.js

links, even when "disabled" were still in the document tab sequence.
This fix sets `tabindex="-1"` when the link is disabled.
Possible Todo: This fix could optionally be enhanced by adding an `@focus` handler that, when disabled, immediately blurs the link.

fix(link): take link out of tab sequence if disabled

---

src/components/table/README.md
src/components/table/table.vue

Adds a Boolean prop `caption-top`, which when set will move the caption to the top of the table
Since merging this would live update the online documentation, we should wait to merge once we are ready to release v1.0.3

feat(table): caption positioning prop

---

src/components/button/button-close.js

Switching from `children` to `slots().default` appears to fix the original issue with SSR rendering of `&times;`

fix(button-close): switch to slots() from children

---

build/build

Using Uglify's `--mangle` option.
The `--compress` option unfortunately removes the two `import` lines from the ESM build. Because of that we don't include the `--compress` option, unless we individually compress each file with different options. i.e setting the ES level to 6 for the ESM build.

perf: reduce minified code size

---

src/components/pagination-nav/pagination-nav.vue
src/components/pagination/pagination.vue
src/mixins/pagination.js

Also placed optimized common render function to mixin for code footprint efficiency

perf(pagination+pagination-nav): convert templates to render function

---

src/components/form-file/form-file.vue

The original Microsoft Edge bug that affected for inputs wrapped in a label element has been fixed as of May 2017. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/
So we can revert back to using the `<label>` element as the wrapper for the custom file input. Using label provides for better semantic markup and accessibility.
This PR also name-spaces the Bootstrap-Vue custom `custom-file` CSS to negate the need for scoped CSS.

fix(form-file): Use `label` as wrapper element + namespaced custom CSS

---

src/components/table/README.md
src/components/table/table.vue

Adds a new option to draw a border around the table (outline), via the Boolean prop `outlined`.  When enabled the Bootstrap V4 class `bordered` is added to the table

feat(table): add outlined option

---

src/components/form-textarea/form-textarea.js

`<b-form-textarea>` wasn't pre-populating the text area value on mount.
Closes #1368

fix(form-textarea): initial value population

---

src/components/tabs/tab.js

fix(tabs): lazy prop regression

---

src/components/modal/README.md
src/components/modal/modal.vue

Based on changes introduced via https://github.com/twbs/bootstrap/pull/24803
Prevents header from getting cut off when vertically centered modal overflows.
Once Bootstrap V4.beta.3 is released, the custom CSS can be removed from the component.

feat(modal): fix for overflowing centered modal

---

src/components/form-file/form-file.vue

Bootstrap V4.beta.2 is missing the styles to display invalid and valid feedback for plain `form-control-file` inputs.
https://github.com/twbs/bootstrap/issues/24831
Interim fix until addressed in Bootstrap V4 next release

fix(form-file): invalid/valid feedback display for plain file input missing in Bootstrap V4

---

src/components/pagination-nav/pagination-nav.vue
src/components/pagination/pagination.vue

Removing custom style for disabled pagination links, as it is now working in native bootstrap  V4.beta.2 CSS
Custom focus styling is still needed for the active page link.
Also updated script code style to match current code style guidelines.

feat(pagination+pagination-nav): disabled styling now works in BS V4.beta.2

---

src/components/tabs/README.md
src/components/tabs/tab.js
src/components/tabs/tabs.js

Adds support for vertical tabs via the `vertical` prop
Also adds the following new props:
- `container-class` added to the `.tab-container` div
- `nav-class` added to the `.nav` tab controls
- `nav-wrapper-class` added to div wrapper around nav tab controls

feat(tabs): vertical tabs + new props for adding classes to inner elements

---

src/components/button/button.js

Removed the validator for the size prop, so that people can use custom `.btn-{size}` classes

fix(button): allow custom size classes to be passed to the size prop

---

src/components/tabs/README.md
src/components/tabs/tab.js

When `b-tabs` are set to `card` mode, `b-tab` automatically adds the class `card-body` to itself.
This option allows the `card-body` class to not be added to the particular `b-tab`. Handy when using b-tabs to show images when in card mode.

feat(tabs): add no-body prop to b-tab

---

docs/assets/css/styles.css
src/components/popover/README.md
src/components/popover/package.json
src/components/tooltip/README.md
src/components/tooltip/package.json
src/directives/popover/README.md
src/directives/tooltip/README.md
src/mixins/toolpop.js
src/utils/tooltip.class.js

Adds a new syncable prop `disabled` to disabled/enable tooltip/popove componentsr. Defaults to `false`
Also introduces new root events for enabling/disabling all/specific tooltips/popovers (components and directives)
Addresses issue #1065

feat(tooltip+popover): programmatically disable/enable tooltip or popover

---

src/mixins/dropdown.js

Also, we don't bother instantiating Popper if dropdown is in a navbar.
Closes issue #1391

fix(dropdowns): prevent memory leak on destroy

---

src/components/table/table.vue
src/utils/index.js
src/utils/stable-sort.js

Different JavaScript environments implement native array sorting differently, and in some cases are implemented with an unstable/inconsistent routine (Chrome and V8 are examples where native sort is inconsistent/unstable).
This can produce SSR client mismatch errors in different environments when  `sortBy` is preset on initial server render of `<b-table>`, where the server native sort uses one method while the client native sort uses a different algorithm.
This PR introduces a new utility function `stableSort`, of which `<b-table>` will use instead of native sort.
`stableSort` uses the native sort, and will fallback to sorting by index when the entries compare equal. This introduces a performance penalty over native sort, but prevents SSR DOM mismatch errors.

fix(table): use stable sort algorithm to prevent SSR issues

---

src/components/table/README.md
src/components/table/table.vue

Adds a function reference to the row's field scope variable for toggling the display of the row details scoped slot. Uses the `$set` method to ensure reactivity, and negate the need to pre-define `_showDetails` property in the item record for reactivity.

feat(table): add toggleDetails method to scoped item slots

---

src/components/form-group/README.md
src/components/form-group/_form-group.js
src/components/form-input/README.md
src/components/popover/README.md

Adds a new prop `label-class` which allows the user to apply additional classes to the label (i.e. responsive padding or alignment classes)

feat(form-group): new prop for label-class, deprecate prop feedback in favor of invalid-feedback

---

src/mixins/dropdown.js

Moving the Popper.js instance to a non-reactive property will prevent Vue from creating reactive getters/setters on the popper instance.
May address issue #1391

perf(dropdowns): use non reactive property to store popper.js instance

---

src/components/modal/_modal.js

The original bug (https://github.com/twbs/bootstrap/issues/23798) was fixed in Bootstrap V4.beta.2: https://github.com/twbs/bootstrap/pull/23799
Fixes #1432

fix(modal): rounded-top class no longer needed when header variant applied

---

src/components/form-group/README.md
src/components/form-group/form-group.js

Helps ensure that all screen readers associate the feedback and description to the input, when label-for is set.
Preserves any original aria-describedby attributes that may be present on the input.

feat(form-group): set aria-describedby attribute on input if label-for provided

---

src/components/card/card.js
src/components/input-group/input-group.js
src/components/jumbotron/jumbotron.js
src/components/media/media.js

perf: evalute slots() once in functional component render functions

---

src/components/popover/README.md
src/components/popover/fixtures/popover.html
src/components/tooltip/README.md
src/components/tooltip/fixtures/tooltip.html
src/directives/popover/README.md
src/directives/popover/popover.js
src/directives/scrollspy/scrollspy.js
src/directives/tooltip/README.md
src/directives/tooltip/tooltip.js
src/mixins/toolpop.js
src/utils/tooltip.class.js

Adds new prop `boundary` to component versions - can be either `scrollParent` (Popper default), `window`, `viewport`, or an element reference
Adds modifiers `window` and `viewport` to directive versions (if not present defaults to scrollParent)
Addresses #1434 
A similar issue (#1163 and https://github.com/twbs/bootstrap/issues/24251) applies to dropdowns, which will be addressed in a separate PR #1440  PR https://github.com/twbs/bootstrap/pull/24979 addresses the issue in Bootstrap V4 official.

feat(tooltip+popover): add boundary element config option (position constraint)

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js
src/mixins/dropdown.js

New prop `boundary` which can be `scrollParent` (Popper default), `viewport`, `window` or a reference to an HTML element.
Controls how the placement is constrained visually.
Addresses issue #1163 and https://github.com/twbs/bootstrap/issues/24251
Without `boundary` set (default):
> ![image](https://user-images.githubusercontent.com/2781561/33746081-27f2ad6e-db91-11e7-8ae8-c65be9390cfe.png)
Now (with `boundary` set to `window` or `viewport`):
> ![image](https://user-images.githubusercontent.com/2781561/33746040-e1510aa4-db90-11e7-976e-3a7c14ff8bc5.png)
PR https://github.com/twbs/bootstrap/pull/24976 has been opened at Bootstrap Official to address this issue as well.

feat(dropdowns): add boundary prop for controlling placement constraint

---

src/components/list-group/README.md
src/components/list-group/list-group-item.js

When `tag` was set to `'button'` and the `disabled` prop was also set, the rendered button was not being disabled (although it had the disabled class and appeared disabled).  This fix ensures the disabled attribute is set when rendered as a button and the disabled prop is true.
Adds new prop `button`, as a shortcut, to force render as a `button` list-group-item-action
Also extends the documentation with additional examples

fix(list-group): disabled button items

---

src/utils/tooltip.class.js

Ensures that interactive popovers  (i.e. with input(s)) are _inside_ the enforce focus tab ring cycle
Fixes #1464

fix(tooltip+popover): append to `.modal-content` instead of `.modal`

---

src/components/form-group/form-group.js
src/components/progress/progress-bar.js

This commit fixes two misspellings im component props that break Vue.js v2.5.11 compatibility.
Closes #1469

fix(form-group+progress-bar): fix misspellings in component props

---

src/mixins/dropdown.js

fix(dropdown): prevent toggle click from closing in collapsed navbar

---

docs/pages/play.vue

change how key is calculated for console log v-for loop.
Prevents duplicate key warning from Vue

docs(play): prevent duplicate keys in console output

---

src/components/dropdown/dropdown.js

Class `.position-static` should be applied only when boundary is **not** `scrollParent`

fix(dropdown): fix condition for when position-static is applied

---

src/components/dropdown/README.md

Just some minor typos fixed in the dropdown component doc.

docs(dropdown): fix typos

---

src/mixins/id.js

On the first run _uid === 0 and this value fails the check not generating an id for the component.

fix(id): fixed check for _uid in id generator

---

src/components/input-group/input-group-addon.js
src/components/input-group/input-group-button.js
src/components/input-group/input-group.spec.js

This addresses changes introduced in https://github.com/twbs/bootstrap/pull/25020
* drops the `.input-group-addon` class and replaces it with `.input-group-prepend` and `.input-group-append` depending on the value of the slot
* deprecates the `.input-group-btn` class and uses the classes above
* defaults component to `input-group-append` if no slot value provided
* updates specs

update input group addon changes from bootstrap beta 3

---

src/components/alert/alert.js

bButtonClose component was imported in alert with the shortcut alias
(bBtnClose) but used with the full tag (b-button-close). When importing
b-alert as an individual component b-button-close alias was not set and
vue failed to import the b-button-close component.
Importing bButtonClose component with the fullname fix #1522 .

Fix #1522: Import button-close in alert with a name matching tag.

---

src/components/input-group/README.md
src/components/input-group/fixtures/input-group.html
src/components/input-group/index.js
src/components/input-group/input-group-append.js
src/components/input-group/input-group-prepend.js
src/components/input-group/input-group-text.js
src/components/input-group/input-group.spec.js

@pi0 @tmorehouse This is what I got through today. It is **not** working code, but I wanted to get some eyes on it for a little help. Vue is new to me and so I'm using this to learn some internals. I think we can easily migrate from input-addon to the two new components @tmorehouse suggested in #1505 just by swapping it out in input-group.js. I laid out these goals to support this change:
* Support the current way of doing it with left and right properties, but surface some messaging to update the HTML to use `b-input-group-prepend|append`.
* Support for child nodes inside `b-input-group-prepend|append`
* Created a `b-input-group-text` component for handling the child div of `b-input-group-prepend|append`
* Add tests for new components
* Update the docs

[WIP] Feat/beta 3 input groups

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js

Allows to add css classes to the toggle button of `<b-dropdown>`

Add toggleClass prop to b-dropdown

---

docs/markdown/reference/validation/README.md
docs/markdown/reference/validation/meta.json

This patch adds a new document that suggests form validation plugins for use
with Bootstrap-Vue. Included is a reference to Vuelidate and a basic
example that highlights the interaction between Bootstrap-Vue and
Vuelidate. It's purposefully verbose and basic to show what is
happening, rather than being a complex high level demonstration.
Closes #171

Add Vuelidate form validation example

---

src/mixins/clickout.js

When removing the click listener, we were calling `removeEventListener` on the wrong element, and this was causing a memory leak.
fixes #1391

Call removeEventListener on the right element

---

src/components/button-toolbar/README.md

"left" and "right" for input-group in b-button-toolbar not work  in 2.0.0-rc

use "prepend" and "append" for input-group

---

src/components/table/README.md
src/components/table/table.js

feat(Table) Use object's property as a key

---

src/components/modal/fixtures/modal.html
src/components/modal/fixtures/modal.js
src/components/modal/modal.spec.js
src/directives/modal/modal.js
src/utils/target.js

This pull request fixes #1613 keeping the default behavior of utils/target untouched.
Multiple event listeners for event type are possible and they are unbound all together.

fix v-b-modal directive unbinding

---

src/mixins/toolpop.js

While it works, passing an `HTMLelement` (e.g. an `HTMLButtonElement`) to a tooltip/popover raises the following warning:
```[Vue warn]: Invalid prop: type check failed for prop "target". Expected String, Object, got HTMLButtonElement. ```

Accept an HTMLElement as a valid target for tooltips and popovers

---

.gitignore
src/components/table/fixtures/table.html
src/components/table/fixtures/table.js
src/components/table/table.js
src/components/table/table.spec.js

Bootstrap-Vue has some extra keys that can be provided to enhance table
functionality. These should be explicitly ignored when automatically
discovering the fields for a table, when the fields prop is not
provided.
The reason for explicitly ignoring the keys, rather than blanket
ignoring all keys beginning with "_" is to minimise any possible
collisions with user provided data in that field.
Fixes #1635

Ignore BV keys when auto-discovering table fields

---

src/components/form-select/form-select.js

The size attribute is not specific to multiple-select fields: it can be
used on single selects on both Bootstrap and raw HTML. We could probably
pass the value straight through instead of renaming it "selectSize",
but I'd like to avoid making a breaking API change at this stage.
Fixes #1639

Always pass selectSize to selects

---

src/directives/scrollspy/README.md

Fixed a couple of small spelling and markup typos in the ScrollSpy directive documentation.

Fix (ScrollSpy docs) spelling/markup errors

---

CHANGELOG.md

convential-changelog seems to be failing to handle our commit logs, probably due to bad formatting on our part. Manually adding some important release notes. I've left out all the minor "fix typo" commits, though I can go back and add them if there is value in that.

Manually add rc2 release notes

---

src/components/list-group/README.md

```
Incorporate list groups into [cards](/docs/components/cards). Use the `<b-list-group>`
prop `flush` prop when using cards with `no-body` to make the sides of the list group
flush with the card.
```
docs/components/cards is invalid so fix it.
Thanks you.

Fix(docs) : invalid url in list-groups

---

src/components/modal/README.md
src/components/modal/modal.js

Added `modalClass` property to `bModal`

---

src/components/tabs/package.json
src/mixins/form-options.js

The props already have default values that cover the cases, so it is unnecessary to cover them again.
Also I have ordered the properties _value, text, disabled_ to be in the same order everywhere in the file.

Clean unnecessary measures

---

package.json
src/components/table/table.js
yarn.lock

This fixes a breaking bug in the latest update, where `table` can't compile because `lodash/get` is not in `node_modules`. Here's the error message I'm getting:
```
ERROR in ./node_modules/bootstrap-vue/es/components/table/table.js
Module not found: Error: Can't resolve 'lodash/get' in '/home/rjmill/Development/build-chain/node_modules/bootstrap-vue/es/
components/table'
@ ./node_modules/bootstrap-vue/es/components/table/table.js 4:0-29
@ ./node_modules/bootstrap-vue/es/components/table/index.js
@ ./node_modules/bootstrap-vue/es/components/index.js
@ ./node_modules/bootstrap-vue/es/index.js
@ ./src/main.js
@ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/main.js
```
`lodash.get` was being imported from `lodash/get`, even though the …

fix(table): import lodash.get from "dependencies"

---

src/components/form-select/form-select.js

The form-input component currently has some arbitary restrictions around
the combinations of multiple, custom-select and selectSize that will be
applied. Previously I tried to address this by passing through the
selectSize, but this caused an issue (hiding the arrows) in custom
selects when the size was set to 0.
This patch cleans up the internal computed state of form-select to be
more relaxed about what user input is rendered in the final component
Fixes: #1658

fix(select): Fix issues with form-select

---

src/components/modal/README.md

Change "teh" to "the" in the modal README.md

docs(modal): fix a typo

---

src/components/tabs/tabs.js

`b-tabs` is very convenient to handle content, but its style is currently limited to `nav-tabs` and `nav-pills`. 
`no-nav-style` gets rid of the mandatory `nav-${navStyle}` allowing more customization without the overhead of deflecting `nav-tabs` and `nav-pills` effects. Here's a sample:
I'd have introduced a `nav-style` or `nav-variant` prop instead, but it'd have lacked constitency with `pills` prop to remain backward compatible.
cheers

feat(tabs/noNavStyle): added related prop and check

---

src/components/tabs/README.md
src/components/tabs/tabs.js

As keyboard navigation prop shouldn't introduce a breaking change, it makes more sense do define it as `no-key-nav` opt-out attribute.

fix(tabs): rename prop to no-key-nav, update docs

---

src/utils/tooltip.class.js

Hi.
I think that #1728 is the spec now.
But if use the offsets function of POPPER.JS, it can be resolved.
https://popper.js.org/popper-documentation.html#modifiers..offset
Please check it when you have a time.
Keiko

fix: Accept not only integer but other texts like as POPPER.JS (#1728)

---

src/components/dropdown/README.md

Fix typo `aria-lableledby` in documentation

docs(dropdown): typo in aria-labelledby

---

src/components/alert/README.md
src/components/alert/alert.css
src/components/alert/alert.js

Closes https://github.com/bootstrap-vue/bootstrap-vue/issues/1512

feat(alert): Add fade prop

---

src/components/form-group/README.md

Fixed a few small textual errors in the documentation.

Minor text corrections in form group documentation

---

src/components/table/table.js

Currently the table component uses this code to set the `aria-rowcount` property:
```javascript
'aria-rowcount': this.$attrs['aria-rowcount'] || (this.perPage && this.perPage > 0)
? '-1'  
: null
```
> https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount
> If all of the rows are present in the DOM, it is not necessary to set this attribute as the user agent can automatically calculate the total number of rows. However, if only a portion of the rows is present in the DOM at a given moment, this attribute is needed to provide an explicit indication of the number of rows in the full table.
> Authors MUST set the value of aria-rowcount to an integer equal to the number of rows in the full table. If the total number of rows is unknown, authors MUST set the value of aria-rowcount to -1 to indicate …

fix(table): Fix Table aria-rowcount

---

src/components/tabs/tab.js

after this change, bootstrap-vue tab transition has the same behavior as original bootstrap.
hide of the previous tab happens instantly, and the new tab have a 0.15s animation. resolves #1806

fix(tab): fix the delay in tab transition

---

src/components/form-input/form-input.js

When fromatter function removes last char from value, text input does not update and character still visible in text input
We could update value of text input directly using its reference
Most of this changes done by @pi0 so all credits goes to him

fix(form-input): force update formatted value

---

src/components/form-input/form-input.js

plaintext could be convenient to customize `b-input` styling (for example when you need to wrap it into a div), but readonly is currently forced to true, when plaintext is enabled.
this PR introduces an indeterminate state for readonly, and hence allows it to be forced to false even with plaintext enabled.

fix(readonly): allow readonly to be forced to false when plaintext is enabled

---

src/directives/popover/README.md

Here's some typos I found when reading this doc, there may be more, but this is what I found.

Fix typos in Popover docs

---

src/components/table/table.js

To make it easier to extend the functionality of b-table without feature creep in the b-table itself, a bit more/easier access to the various stages of computedItems is needed.
For example, to implement #225 externally, access is needed to the filtered and sorted, but not yet paginated items. With this change this becomes possible by doing something like this:
const table = this.$refs.the-table
let items = table.hasProvider ? table.localItems : table.items
items = table.sortItems(table.filterItems(items))
This PR incorporates no functional changes and adds no features.

feat(table): Split computedItems into multiple functions

---

docs/markdown/reference/validation/README.md

This updates the documentation from the discussion in #1270

updated vee-validate example to handle the `fields` error in issue #1270

---

src/directives/popover/README.md

emit the `bv::hide::popover` event instead of `bv::hide::popover` to close a specific popover

fix(popover): fixes close emit argument

---

src/components/table/table.css

FIX the breakpoint-max values in the stacked table CSS
Set to 0.02px delta to work around a current rounding bug in Safari.
See https://bugs.webkit.org/show_bug.cgi?id=178261
See also patch on bootstrap v4:
https://github.com/twbs/bootstrap/pull/25177

fix breakpoints on stacked tables to latest bootstrap-values

---

src/components/button/button.js
src/components/button/button.spec.js
src/components/button/fixtures/button.html
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js
src/components/dropdown/fixtures/dropdown.html

This PR makes the `b-button`s tag confirgurable (e.g. to a `div`).
This can be very handy if you want the buttons styling but want to place another clickable element inside the button which is normally prevented by the [interactive content model](https://www.w3.org/TR/html5/dom.html#interactive-content).

feat(button): Make button tag configurable

---

src/components/table/table.js

The provider function was called with state values that were only partially updated after a user action as this function is called as soon as an event is emitted. This meant that the provider was called with potentially an invalid context as in the case I encountered and subsequent calls for subsequent data changes from the event processing were ignored as the table was set as busy.
With this change, waiting for the $nextTick before calling the provider, the DOM has time to update and it is called with the proper context. The provider is also only called once per user event as opposed to every state changes stemming from the event if the busy state had been removed; so this is the proper solution considering that the provider may be reaching out a remote database.

fix(table): only call provider once DOM is fully updated (#1904)

---

docs/markdown/reference/images/README.md

`transformToRequire` (now renamed to `transformAssetUrls`)

fix(docs): vue-loader v15 changes

---

src/components/modal/README.md

I changed the wording to make it more explicit as to why `v-b-modal` is recommended over other approaches. I hope this change makes it clearer to understand.
https://github.com/bootstrap-vue/bootstrap-vue/issues/2018

docs: clarify the benefits of using v-b-modal

---

package.json
yarn.lock

The [`opencollective`](https://www.npmjs.com/package/opencollective) dependency brings in a lot of unneeded packages into the dependency tree for essentially `console.log` at post install. On a fresh project, where we just habe `bootstrap-vue` as a dependency, it pulls in over 100 dependencies. The open collective project has an alternative dependency which does essentially the same thing without polluting the dependency tree: [`opencollective-postinstall`](https://www.npmjs.com/package/opencollective-postinstall)
Output before:
Output after:
Dependency tree before/after:
```bash
yarn list | wc -l
#after
yarn list | wc -l
```

Replace `opencollective` dependency with `opencollective-postinstall`

---

docs/markdown/reference/validation/README.md

The state change doesn't get updated when a form is submitted or validated without touching the input (Ex: User clicks submit button but the field is required). Took me hours to figure out this small change to update the state in such cases.
If the field is touched, then it's fine. The issue was when field wasn't touched yet there's an error due to it being required.

fix (docs): Handle state change on validated fields.

---

src/components/modal/modal.js

fix(modal): fixes modal with long content on click backdrop scroll to .modal-content top

---

src/components/table/README.md
src/components/table/table.js

I noticed that you can't sort a table if the key is a nested property. This fixes that. See the example in the components/table/readme.md that the address.city column can now be sorted.

feat (table): Updated table component to support sorting on nested object properties.

---

src/components/table/package.json
src/components/table/table.js
src/components/table/table.spec.js

Allows for right click as well as existing click + double click.

feat(table): Support contextmenu event binding for table rows

---

src/components/table/package.json
src/components/table/table.js

Some users might want to know not only when the mouse is hovering a row,
but also when the mouse leaves the row.
For example for dynamically showing (and hiding) some row content based
on mouse hovering.

feat(table): Add row-unhovered event

---

src/components/form-group/README.md
src/components/form-group/form-group.js

Adds in the missing `disabled` prop.
Disabled state is only applicable when the a `fieldset` is rendered (i..e when no `label-for` is specified
Note that not all browsers will disable the inputs inside of a disabled fieldset.
Fixes #1920

fix(form-group): add missing disabled prop

---

src/components/popover/index.js
src/components/popover/package.json

This commit adds the missing popover directive to the plugin.

fix(popover): Add directive to component plugin

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js
src/components/dropdown/fixtures/dropdown.html
src/mixins/dropdown.js

This commit adds support for `dropright` and `dropleft` directions for the dropdown component.
Closes #2108.

feat(dropdown): Add `dropright` and `dropleft` direction support

---

src/components/button-group/button-group.js
src/components/card/card-body.js
src/components/dropdown/dropdown.js
src/components/form-group/form-group.js
src/components/input-group/input-group.js
src/components/jumbotron/jumbotron.js
src/components/modal/modal.js
src/components/nav/nav-item-dropdown.js
src/components/progress/progress-bar.js
src/components/table/README.md
src/components/table/table.js
src/mixins/form-options.js
src/mixins/pagination.js
src/utils/strip-scripts.js

Utility for removing script tags from injected HTML (i.e. for use with `v-html` or `domProps.innerHTML`)
Prevents possible user supplied input form injecting scripts into the DOM
Fixes #1974
Fixes #1665
Scripts will no longer be injected into the DOM (i.e. from user supplied data or component props that support HTML)
_PR titles should following the [**Conventional …

feat(security): Strip HTML script tags before inserting content into DOM. Fixes #1974,#1665

---

src/components/dropdown/dropdown.css
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js

This PR use custom CSS for the `no-caret` option on the `<b-dropdown>`component instead of removing the `dropdown-toggle` class from the toggle itself which can cause minor styling issues.
Closes #1473

fix(dropdown): Use custom CSS for `no-caret` option #1473

---

src/mixins/id.js

safe ID's must be created on mount() of the component, and only client side. This was the original way it was intended, but was inadvertently changed over time to lose its reactive nature (there is no reactivity to this._uid)
this addresses this issue by storing the bv safe ID in data on mount, of which computed properties and methods can rely on it.
The computed prop `safeId` replaces the method `safeId(...)`, and returns a cached method reference which mimics the old method `safeId(...)`, and accepts the same optional suffix parameter.
fixes #1978  …

fix(safeId): trigger id creation/update after mount (fixes #1978)

---

src/components/modal/README.md
src/components/modal/modal.js
src/components/modal/modal.spec.js

Support multiple modals being opened onscreen at the same time.
Keeps track of the number of modals currently opened to determine if scrollBar adjustments need to be done.
Fixes #1997
Fixes #1869
Fixes #1842
Fixes #1513
_While not officially supported in Bootstrap V4 native_, it has been a popular feature request for Bootstrap-Vue
It requires that the outer div container (containing .modal and .modal-backdrop) have CSS `position: relative` and a z-index of multiples of 2000 (starting at 2000) to ensure proper stacking of the opened modals. This may cause weird layout issues depending on the overflow and positioning settings of the parent container (which is similar to current behaviour).  It is always best to place your `b-modal` outside of constrained elements/components.
**What kind of …

[WIP] feat(modal): Support multiple modals open at once

---

src/components/form-file/README.md
src/components/form-file/form-file.js

As an alternative to calling the `reset()` method, users can now clear the form file input by setting the v-model to null or an empty string.
The watcher checks for null and empty string and internally calls reset().
Also listens for reset events triggered by the parent form and clears the v-model

feat(form-file): reset file input when value  set to null or empty string

---

src/components/form-group/README.md
src/components/form-group/form-group.js
src/components/form/README.md
src/components/form/fixtures/form-invalid-feedback.html
src/components/form/fixtures/form-invalid-feedback.js
src/components/form/fixtures/form-valid-feedback.html
src/components/form/fixtures/form-valid-feedback.js
src/components/form/form-invalid-feedback.js
src/components/form/form-invalid-feedback.spec.js
src/components/form/form-valid-feedback.js
src/components/form/form-valid-feedback.spec.js

adds a new boolean prop `tooltip` to `b-form-invalid-feedback`, `b-form-valid-feedback`, and `b-form-group` that will change the style of feedback from a block of text to a tooltip style.
tooltip style feedback documentation was added to Bootstrap v4.1

feat(forms): add support for tooltip-style feedback text

---

src/components/list-group/list-group-item.js
src/components/list-group/list-group-item.spec.js

A `<button>` element without a type specified defaults to type "submit" in some browsers.
This PR explicitly sets the attribute `type="button"` when `<b-list-group-item>` is rendering a `<button>` element, and no `type` attribute is supplied.
Fixes #2192 

fix(list-group-item): set button type to 'button' when button in mode or tag=button (Fixes #2192)

---

src/components/table/table.js

If user provides `aria-rowcount` and/or `aria-describedby` attributes, preserve their values when rendering. Fixes #1801 where on initial mount `this.$attrs` may be undefined.
Also ensures that any non-prop attributes are rendered on the `<table>` element when table is wrapped in responsive `<div>`.  Sets `inheritAttrs: false` in the `<b-table>` component definition, and merges `this.$attrs` on the `<tbody>`

fix(table): Preserve aria-rowcount and aria-describedby if provided. Fixes #1801

---

src/components/table/README.md
src/components/table/package.json
src/components/table/table-busy.spec.js
src/components/table/table.js

Adds a new slot `table-busy` which allows users to display a loading message when the table is in the busy state.
If no `table-busy` slot is present, the current rows are displayed (as was the behaviour before)
Includes new test suite for `busy` state testing using `vue-test-utils`
Closes #1859

feat(table): Add table-busy slot for loading status. Closes #1859

---

src/components/form-input/README.md
src/components/form-input/form-input.js
src/components/form-input/form-input.spec.js
src/components/form-input/package.json
src/components/form-textarea/README.md
src/components/form-textarea/form-textarea.js
src/mixins/form-text.js

Incorporates the new form-text mixin introduced with `b-form-textarea` PR #2111 which will help reduce the code footprint size, and introduces new `number` and `trim` modifier props.

feat(form-input): Use new form-text mixin and add trim and number modifiers

---

src/components/input-group/_input-group.scss

Prevents the CSS from appearing in the compiled output CSS more than once.
Reduces file size of generated bootstrap-vue.css

fix(scss): import _input-group.scss once at most

---

src/components/popover/README.md

`Enable / Disable Popover by $ref event` button from the example in the section `Programmatically disabling popover` does not work, because the example missed `ref="popover"`.

docs(popover): missed ref="popover" in the "Programmatically disabling popover" example

---

src/components/table/table.js

Rather than updating the v-model on every render, emit only when the displayed row data changes.
Closes #2231

fix(table): Emit v-model input event only when computedItems changes (closes #2231)

---

src/components/table/table.js

for array data, change is detected with the items watcher, works ok when changes are huge, added or deleted items for example.
localItems watcher is to be avoided because it is triggered for details
But for remote data (provider function), the watcher is not called, but as we need to call the refresh method anyway, clear selection is made there.
This refresh call could also be used for array data if need greater control.
**If adding a new feature, or changing the functionality of an existing feature, the PR's description above …

fix(table): Clear selection when data change

---

package.json

Adds scss and css files to the `sideEffects` rule

fix(package.json):  prevent css and scss from being tree shaken out

---

src/components/form-group/form-group.js

The `<label>` element in non-horizontal form group has `display: inline-block` which prevents label alignment from working in non-horizontal form-groups.
This addresses the issue by adding class `d-block` to the `<label>` when non-horizontal.

fix(form-group): allow label alignment on label when not horizontal

---

src/components/form-checkbox/README.md
src/components/form-checkbox/_form-checkbox.scss
src/components/form-checkbox/form-checkbox-group.js
src/components/form-checkbox/form-checkbox.js
src/components/form-checkbox/form-checkbox.spec.js
src/components/form-checkbox/index.scss
src/mixins/form-radio-check.js

Implements Boostrap V4.2 custom-switch style checkboxes.
Conditionally adds new CSS if not using v4.2 CSS
Adding support for switch styling involves only minor updates to the checkbox.
TODO:

feat(form-checkbox): support custom switch styling

---

src/components/index.scss
src/components/list-group/README.md
src/components/list-group/_list-group.scss
src/components/list-group/fixtures/list-group.html
src/components/list-group/index.scss
src/components/list-group/list-group.js

Conditionally includes a Boostrap V4.2 SCSS section for supporting zebra striped list-groups (similar to striped tables).

feat(list-group): add striped support

---

CONTRIBUTING.md
docs/nuxt.config.js
src/components/pagination-nav/README.md
src/components/pagination/README.md

Add `overflow-x:auto:` to some of the documentation examples, so that they can be scrolled on small screens and don't cause the page to resize.
Note for things like drop downs and other components that dynamically position, this technique does not work due to positioning issues with overflow scroll.

chore(docs): add overflow-x:auto to wider examples for small screen support

---

src/components/image/fixtures/image.html
src/components/image/img-lazy.js

- Wraps initial inView check in `$nextTick` to ensure DOM rendering is complete.
- Listens to bubbled `transtionend` events to see of img is in viewport.
- Listens for image load events (placeholder).
- Adds new syncable prop `show` to force image to show.
Fixes #1755

fix(b-img-lazy): better initial inView check + new show prop (fixes #1755)

---

src/components/table/README.md
src/components/table/table-provider.spec.js
src/components/table/table.js
src/components/table/table.spec.js

If criteria causes the provider function to need a refresh, and a refresh is currently in progress, schedules a new update request once the currently running provider completes.
Also applies to the 'refresh()` method if the provider is running when called.
This is not really a "debounce", but if multiple provider refresh updates are triggered while a provider is currently running, only a single refresh will be requested once the current provider completes (when `refreshed` is emitted).
TODO:
**If adding a new feature, or changing …

feat(table): "Debounce" providerFunction and refresh methods

---

src/components/card/card-body.spec.js
src/components/card/card-footer.spec.js
src/components/card/card-group.js
src/components/card/card-group.spec.js
src/components/card/card-header.spec.js
src/components/card/card-img.js
src/components/card/card-img.spec.js
src/components/card/card-sub-title.js
src/components/card/card-sub-title.spec.js
src/components/card/card-title.js
src/components/card/card-title.spec.js

Add unit tests for card sub-components.

chore: add tests for card sub-components

---

docs/markdown/reference/router-links/README.md
src/components/link/README.md
src/components/link/link.js

Add support in `<b-link>` for `<nuxt-link>` when running under Nuxt.JS.
If Nuxt is detected, then will render a `<nuxt-link>` instead of `<router-link>` (`<nuxt-link>` supports all of the features of `<router-link>`, plus more).
Adds new prop `no-prefetch` which disables Nuxt's link prefetching feature (available in Nuxt v2.4.0+).

feat(link): Add support for nuxt-link

---

src/components/link/fixtures/link.html
src/components/link/link.js
src/components/link/link.spec.js

active-class and exact-active-class props are applied automatically by router-link.
The active prop should only turn off/on the `active` class.

fix(link): use `active` class when manually placed into active state

---

src/components/collapse/collapse.js
src/components/modal/modal.js

Use passive event listeners where possible

perf(events): use passive event listeners where possible

---

src/components/tabs/README.md
src/components/tabs/tab.js
src/components/tabs/tab.spec.js
src/components/tabs/tabs.js

Fixes: #2327
Fixes: #2148
Closes: #2403
Closes: #2180 
Users (web authors) must also realize that tabs' controls are (or act like) buttons.  One cannot place form controls inside a button/link per HTML/HTML5 standards.  Stop trying to do this! :stuck_out_tongue_closed_eyes: 

fix(tabs): various fixes and improvements (Fixes: #2327, #2148. Closes: #2403, #2180)

---

src/components/tabs/tabs.js

This PR corrects the type of the `tabIndex` property form `Boolean` to `Number`.
event changes)
keyboard …

fix(tabs): `tabIndex` prop type

---

src/components/pagination/pagination.js

Sets `total-rows` default value to 0.
fixes #2498 
event changes) …

fix(pagination): set default total rows to 0 (fixes #2498)

---

src/mixins/dropdown.js

Change ordering of `shown` event and focusMenu method.
Focuses the menu container before emitting the `shown` event, so that users can optionally focus a menu item (or form input) once shown.
Closes #2520
"chore: fix typo in docs", etc). **This is very important, as the …

fix(dropdown): focus menu container before emitting shown event. Closes #2520

---

src/components/tabs/package.json
src/components/tabs/tabs.js

When a non-disabled tab button is clicked (or keyboard nav activates tab), emits a `click` event on the respective `b-tab` component instance.  Passes the event object as the first argument.
Fixes #2512
"chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` …

fix(tabs): Emit click on b-tab instance when button clicked. Fixes #2512

---

src/components/progress/progress-bar.js
src/components/progress/progress.js

Use `provide` and `inject` for better communication between progress and progress-bar
event changes) …

perf(progress): use provide and inject for inter component communication

---

src/components/form-checkbox/README.md

Plain checkbox also supports indeterminate state on Windows/Linux/Mac/Android, but not on iOS.
event …

chore(docs): Indeterminate state of plain checkbox for iOS

---

src/components/dropdown/README.md

Add example of $root events for dropdown. 
Closes #2514 
event changes)
keyboard only users? clickable …

chore(docs): dropdown $root events example.

---

package.json
yarn.lock

Adds `@babel/runtime` to devDependencies
Fixes #2566
event changes) …

fix(deps): Add @babel/runtime to devDependencies

---

src/components/form-textarea/README.md

Brackets wrong way round.
event changes)
keyboard only users? clickable items should be in the tab index, …

fix(docs): fix broken link in form-textarea docs

---

src/components/card/card.js

Fixes error `Invalid attempt to spread non-iterable instance` when `b-card` is set to `no-body` and has no content
Please replace this line with a detailed description of your pull request. If no description your PR
may be rejected.
- [x ] It's submitted to the `dev` branch, **not** the `master` branch
- [x ] The PR should address only one issue or feature. If adding multiple features or fixing a bug
- [x ] PR titles should following the
[**Conventional …

Fix (bCard): array spread error when set to no-body

---

src/utils/get.js

Fixes an issue with the `get` method where the passed object is null or undefined.
Fixes #2623
event …

fix(utils/get): handle calse where passed object is null (Fixes #2623)

---

src/components/table/README.md
src/components/table/table.js

The Table component "empty" slot isn't very flexible, as it must be a named slot and cannot be scoped (relates to https://github.com/bootstrap-vue/bootstrap-vue/issues/2206 which is explicitly part of core, see https://github.com/vuejs/vue/blob/4d4d22a3f6017c46d08b67afe46af43027b06629/src/core/instance/render-helpers/resolve-slots.js#L23), preventing the `b-table` component from being wrapped (relates to https://github.com/vuejs/vue/issues/7587). As a solution, I've taken a cue from  https://github.com/bootstrap-vue/bootstrap-vue/issues/2206#issuecomment-443336885 to add flexibility to the `empty` and `emptyfiltered` slots to support both unscoped and scoped slots, allowing the developer to have flexibility with the implementation needed.
**What kind of change does this PR introduce?** …

feat(table): add support for scoped empty slots

---

docs/markdown/reference/images/README.md
src/components/card/README.md
src/components/card/card-img-lazy.js
src/components/card/card-img-lazy.spec.js
src/components/card/index.js
src/components/card/package.json
src/utils/object.js

New helper sub-component `<b-card-img-lazy>` which provides most of the features of `<b-img-lazy>` but tailored for use in cards. `<b-card-img-lazy>` is a functional component wrapper for `<b-img-lazy>`
"chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` …

feat(card-img-lazy): new card-img-lazy sub-component

---

src/components/form-input/form-input.js
src/components/form-input/form-input.spec.js
src/mixins/form-text.js

Allows number type for `b-form-input`, to handle when using the `number` modifier prop. Prevents console warnings about prop type checks.
**If new …

fix(form-input): allow number type for form-inputs (via form-text mixin)

---

src/components/table/table.js
src/utils/object.js
src/utils/to-string.js

When b-table encounters an object (including Arrays) as a field value, and no formatter or field scoped slot is provided, a blank value is typically rendered in the field cell:
```js
items: [
{ age: 40, name: { first: 'Dickerson', last: 'Macdonald' } },
{ age: 21, name: { first: 'Larsen', last: 'Shaw' } }
]
```
Before:
This PR adds in a function to convert an object/array to a string for rendering.
This is identical to how Vue performs `{{ value }}` interpolation (actually it is very identical, as the method is borrowed from Vue's utils).
After:
This conversion is only done for the visual representation, and the raw value is still passed to the slots scope (formatted and unformatted)
**Does this PR introduce a breaking …

feat(table): better default rendering of unformatted object values

---

src/mixins/normalize-slot.js
src/utils/normalize-slot.js
src/utils/normalize-slot.spec.js

Util and Mixin for normalizing scoped and un-scoped slots.
Util can be used in functional components, while the mixin can be used in normal components.
This will be handy where we want to be able to support both scoped or regular slots in components (i.e. optionally scoped slot). …

chore: util and mixin for normalizing scoped and un-scoped slots

---

src/components/table/README.md
src/components/table/package.json
src/components/table/table.js
src/mixins/normalize-slot.js

In versions of Vue prior to 2.6, scoped slots and un-scoped slots were separate entities.  Now all regular names (un-scoped) slots are also available in the `$scopedSlots` as functions (which provide render speed optimizations, over regular $slots).  This PR makes optionally scoped slots work with Vue 2.5.x.
The following slots are now all available as optionally scoped:
- `colgroup`
- `thead-top`
- `HEAD_<field_key>`
- `FOOT_<field_key>`
- `empty`
- `emptyfiltered`
- `top-row`
- `bottom-row`
When the user provides a slot-scope, these slots will be called as $scopedSlots, and passed a slot scope context.
Uses the new normalize-slots mixin.
Will also introduce optional scoped slots into other components (such as modal) for passing methods to the slots in a separate PR.
**What kind of …

feat(table): make some slots available either as scoped or unscoped

---

src/components/table/README.md
src/components/table/table.js

Minor adjustments to row `:key` generation based on primary key existence.
Rather than use a serialized version of the row values as the rows `:key` value, the displayed row index value is used (unless a primary key is provided).
Users who are experiencing issues with components in cells getting re-used (and not fully updating, as in #931, and #2410) will need to specify a `primary-key` column to circumvent issues they may encounter.  This PR partially reverts #2416 as using the `primary-key` will provide better results, as the serialized string (from the rows values) could change due to mutations in row data, causing unnecessary re-renders.
Also adds a row attribute `data-pk` which will have the primary key value. …

perf(table): minor tweaks to primary key usage

---

src/components/nav/nav-item.js
src/components/nav/nav-item.spec.js

When `<b-nav-item>` was set to `disabled`, it would still emit a click event, when it shouldn't.
This PR moves any registered listeners to the rendered `<b-link>` sub component.
Also adds two new props `link-attrs` and `link-classes` to pass additional attributes and classes to `a.nav-link`.
"fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, …

fix(nav-item): move listeners to link element

---

src/components/pagination-nav/README.md
src/components/pagination/README.md
src/components/pagination/pagination.spec.js
src/mixins/pagination.js

`innerText` may cause some SSR hydration issues.
Instead, it now passes the text as a String to the last argument of `$createElement`
Addresses #2744
**If new …

fix(pagination): avoid using domProps innerText (Addresses #2744)

---

src/components/table/table.js
src/components/table/table.spec.js

When user is selecting a range of text in the table, a row-clicked event was occurring.
This PR filters out click events when the user is in the midst of composing a text selection.
closes #2791
"chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is …

fix(table): don't emit row/head-clicked when user is selecting text (Closes #2791)

---

src/components/form-checkbox/form-checkbox-group.spec.js
src/components/form-radio/form-radio-group.spec.js
src/mixins/form-radio-check.js
src/utils/dom.spec.js

form-radios and form-checkboxes were not rendering with required attribute when prop required was set on the group. The original test was checking for the wrong attribute, and has now been corrected as well.
Fixes #2839
"chore: fix typo in docs", etc). **This is very important, …

fix(form-radio/form-checkbox): ensure prop required propagated in group mode (fixes #2839)

---

src/components/carousel/carousel.js

In the carousel component, there's an [event handler](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/carousel/carousel.js#L403) that references `event.originalEvent`, which appears to always be undefined in several (all?) mobile browsers. Since [line 405](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/carousel/carousel.js#L405) isn't checking for the existence of `originalEvent` first, an error is thrown for every touch.
Maybe someone more familiar with the codebase can explain why `event.originalEvent` is being used here? It seems like `event.originalEvent` is a jQuery-specific thing, so maybe it's just a hold over from some Bootstrap code? Either way, I tried to make this PR as least destructive as possible - so if `event.originalEvent` …

fix(carousel): fix touchmove handler to re-enable swipe gestures

---

src/components/carousel/carousel-slide.spec.js
src/components/dropdown/dropdown-item-button.spec.js
src/components/dropdown/dropdown-item.spec.js
src/components/form-checkbox/form-checkbox-group.spec.js
src/components/form-checkbox/form-checkbox.spec.js
src/components/form-file/form-file.spec.js
src/components/form-input/form-input.spec.js
src/components/form-radio/form-radio-group.spec.js
src/components/form-radio/form-radio.spec.js
src/components/form-textarea/form-textarea.spec.js
src/components/table/table-bottom-row.spec.js
src/components/table/table-busy.spec.js
src/components/table/table-caption.spec.js
src/components/table/table-colgroup.spec.js
src/components/table/table-primarykey.spec.js
src/components/table/table-provider.spec.js
src/components/table/table-row-details.spec.js
src/components/table/table-selectable.spec.js
src/components/table/table-sort.spec.js
src/components/table/table-tbody-row-events.spec.js
src/components/table/table-tbody-transition.spec.js
src/components/table/table-tfoot-events.spec.js
src/components/table/table-thead-events.spec.js
src/components/table/table-thead-top.spec.js
src/components/tabs/tab.spec.js
src/components/tabs/tabs.spec.js
src/utils/dom.spec.js

Vue-test-utils does not automatically destroy mounted wrappers at the end of each test.  This can potentially cause test issues (when using native DOM querySelector methods), and since the DOM is not removed from the JSDOM document it can impact memory usage over time for large test suites.
Note however, that, currently, wrapper.destroy() does not work with functional components.
See https://github.com/vuejs/vue-test-utils/issues/1185
This PR adds `wrapper.destroy()` at the end of each `it(...)` test where appropriate (mainly for mounts that set `attachToDocument: true`), for non-functional component mounts.
**The PR fulfills …

chore(tests): call wrapper.destroy() after each test to release DOM and memory

---

src/components/form-file/README.md
src/components/form-file/form-file.js
src/components/form-file/form-file.spec.js
src/components/form-file/package.json

Adds in a new prop `file-name-formatter`, which accepts a function that can return the file names formatted as the user sees fit.
The optional formatter is called with a single argument which is an array of File object(s).  It should return a string (no HTML supported).
Also adds in a scoped slot `file-name` for formatting the file name(s).
Closes #2667 
"fix(alert): not …

feat(form-file): add in prop and scoped slot for formatting selected file names

---

src/directives/scrollspy/README.md
src/directives/scrollspy/scrollspy.class.js

Support links generated by vue-router when it is in hash based routing mode (i.e. two hashes in the HREF)
Closes #2722
**If new features/enhancement/fixes are added …

feat(scrollspy): support when vue-router is in `hash` based route mode (closes #2722)

---

src/utils/get.js
src/utils/get.spec.js

If the nested value in an object was `0`, `get()` was returning `null` instead of the correct value.
event …

fix(utils/get): handle case when nested value is falsy

---

src/components/breadcrumb/breadcrumb-item.js
src/components/breadcrumb/breadcrumb-item.spec.js

This PR removes the `role="presentation"` attribute from `<breadcrumb-item>` which is causing accessibility warnings.
Closes #2988.
**If new …

fix(breadcrumb-item): remove `role="presentation"` (closes #2988)

---

src/components/form-textarea/form-textarea.js

`computedHeight` is used, when `max-rows` is given to an `b-form-textarea` to calculate the auto height.
**1. fix: not subtracting border width from scrollHeight**
`scrollHeight` contains only the padding and not the border.
This resulted in an incorrect calculation of `contentRows` (float instead of int) and lead to an visible vertical scroll bar, even when `max-rows` haven't been reached yet.
~**2. fix: respecting boxSizing in height calculation**~
~Depending on boxSizing, the height of the element contains the padding and border (`box-sizing: border-box`) or not (`box-sizing: content-box`).~ **EDIT (by TM):** _Bootstrap CSS always sets every element to `border-box`, so this extra test would only generate overhead that is not needed_.
~**3. fix: setting height temporary to `minHeight` …

fix(form-textarea): improved computedHeight calculation when in auto resize mode

---

src/components/collapse/collapse.js
src/components/navbar/navbar-toggle.js
src/components/navbar/navbar-toggle.spec.js
src/directives/toggle/toggle.js
src/directives/toggle/toggle.spec.js
src/utils/config.js

Adds a new private $root event for ensuring the toggle state is in line with the collapse state.
The new event is emitted anytime the `<b-collapse>` component updates, regardless of the visible state of the collapse.
Closes #3020
"chore: fix typo in docs", etc). **This is very …

fix(v-b-toggle/b-collapse): ensure toggle remains in sync with collapse (Closes #3020)

---

src/index.d.ts

RC 17 introduced an invalid `mixed` keyword in the TypeScript definitions file, this PR fixes that issue by replacing instances of `mixed` with `any`.
This fixes [#3041](https://github.com/bootstrap-vue/bootstrap-vue/issues/3041) and it's duplicate [#3042](https://github.com/bootstrap-vue/bootstrap-vue/issues/3042)
"fix(alert): not alerting during SSR render", …

fix(typescript): replaced invalid `mixed` keyword with `any` (fixes #3041)

---

docs/markdown/intro/README.md
nuxt/index.js
nuxt/plugin.template.js

Introduce a new `pretranspile` option for for users using nuxt module.
BootstrapVue ships with pre-transpiled `es/` dist. This has many advantages and does not needs transpiling again. But as it has a wider babel config (for browser support) than Nuxt, transpiling on final project produces bundles with less size and better runtime perf in flavor of more compile time.
This option by default is only enabled for production mode so we have both speed and final build quality.
Results on a starter nuxt project with BV:
`usePretranspiled: true`: (`es/`)
- 906 KB 
- 221 KB Gzip
- Build time: 20.51s
`usePretranspiled: false`: (`src/`)
- 829 KB
- 210KB Gzip
- Build time: 27.7s
Using `src/` takes more **7.2 sec** and reduces bundle size for **77 KB** ( **11 KB Gzip**)
**What kind of change does this …

feat(nuxt): add `usePretranspiled` option

---

src/components/modal/modal.js

Clears out the data for return_focus when the modal has hidden
Specifically affected users who were using v-model and re-using same modal from various locations on the page.
Fixes #3067 …

fix(modal): clear internal return_focus value after modal closes (fixes #3067)

---

src/components/modal/modal.js

This PR fixes the close on click-out functionality on IE 11.
**Background:**
IE does not regard `document` as a node, so `document.contains()`is always retuning `false`.
Using `document.body.contains()`resolves this problem.
Closes #3115.

fix(modal): close on click-out for IE11 (closes #3115)

---

src/components/tabs/tab.js
src/components/tabs/tab.spec.js

I'm a screen reader user, and the existence of `aria-expanded="true"` on the panel doesn't make much sense to me and isn't visible in any ARIA examples I've examined. This removes the attribute and updates the spec.

fix(tab): don't use `aria-expanded` on the panel

---

src/components/toast/README.md

chore(docs): minor updates to toast docs

---

src/components/toast/toast.js
src/components/toast/toaster.js
src/utils/config.js

Adds additional values to global config for `b-toast`, `b-toaster` (and `this.$bvToast.toast()` as it uses the previous two).
Closes #3169

feat(toast): add additional options to global config (closes #3169)

---

src/mixins/form-text.js

This PR adds an additional check to to the `updateValue()` method to check if the given value is different from the actual input value, even when the `localValue` hasn't changed.
This can be caused by the `formatter` function.
Closes #2657.

fix(form-input): properly handle out-of-sync values (closes #2657)

---

src/mixins/pagination.js

Rather than use string literals like `'…'`, use ES5 Unicode escape sequence string `'\u2026'`.
May address #3179

fix(pagination): use unicode escape sequence for default bookend buttons (closes #3179)

---

src/components/modal/modal.js

In some cases, IE 11 is not setting document.activeElement, which is used to determine which element to return focus to when the modal closes.
This PR adds in an extra check for that.
fixes #3206 

fix(modal): return focus edge case bug in IE11 (fixes #3206)

---

src/components/modal/modal.js

When modal is set to be initially open on mount, delay the show in a `$nextTick()` to help ensure DOM is fully loaded
Addresses https://github.com/bootstrap-vue/bootstrap-vue/issues/3312#issuecomment-493389988

fix(b-modal): delay initially open modal via nextTick when using v-model or visible prop

---

docs/markdown/intro/README.md
nuxt/plugin.template.js

Merges imports from same module into a single import statement
Adds note in docs that tree-shaking only works when in `production` mode in Nuxt, and note on using tree shaking option combined with manual imports of components/directive/plugins inside the Nuxt app.
Adds a note about tree shaking in intro section when importing individual components/directives/plugins.
Addresses #3323

feat(nuxt module): optimize imports into single import statements

---

src/components/tabs/tab.js
src/components/tabs/tab.spec.js
src/components/tabs/tabs.js
src/components/tabs/tabs.spec.js

fix(tabs): use DOM query for tab probing after mount (closes: #3361)

---

docs/markdown/misc/settings/README.md

Minor update to configuration docs, noting ability to configure via `BootstrapVue.setConfig({....})` before `Vue.use(BootstrapVue)`.

chore(docs): minor update to configuration docs

---

src/components/form-checkbox/form-checkbox.spec.js
src/components/form-file/form-file.spec.js
src/components/form-input/form-input.spec.js
src/components/form-radio/form-radio.spec.js
src/components/form-select/form-select.spec.js
src/components/form-textarea/form-textarea.spec.js
src/mixins/form.js

Wrap autofocus routine in a requestAnimationFrame to allow for autofocusing in modal to work.
The `autofocus` prop was introduced in v2.0.0-rc.21

fix(form control): handle autofocus inside modal or when inside a transition

---

src/components/button/README.md
src/components/button/button.js
src/components/button/button.spec.js

New `squared` prop will add class `rounded-0` to the button to make the corners squared.

feat(button): add new `squared` prop for making buttons with square corners

---

src/components/tabs/tab.js
src/components/tabs/tabs.js

Fix when using tabs that are dynamically created
Fixes #3395
Other tweaks:
- removed reliance on MutationObserver for detecting new tabs
- `b-tab` instances now notify `b-tabs` when they have been mounted/unmounted, so that `b-tabs` can then update its list of tabs (in DOM order)
- We still need to use DOM queries after mount (in `b-tabs`) to determine tab order and tab VM instances, as `this.$slots.default` may have cached old vnode instances which don't reflect the current instances (might be a 2.6.x Vue bug, or side-effect of new slot handling), when rendered inside lazy modals
- While `this.$children` does have accurate lists of the `b-tab` instances, unlike `this.$slots.default`, we can't rely on it as the children in `this.$children` are not guaranteed to be in document order. …

fix(tabs): fix regression with dynamically added tabs (fixes #3395)

---

src/components/tabs/tabs.js

Addresses https://github.com/bootstrap-vue/bootstrap-vue/issues/3260#issuecomment-498640877
In some cases, when querying the DOM for the contained b-tab instances, the vm attached to the element can either be the `transition` component (inside the b-tab) or it can be the `b-tab` itself, dependent on render conditions.
This fix uses the `registeredTabs` array as the source of truth, and then uses the DOM to determine order of the b-tab instances (after mount, by comparing b-tab IDs with the IDs found in the DOM)
Closes #3260 (via work-around https://github.com/bootstrap-vue/bootstrap-vue/issues/3260#issuecomment-498713337) …

fix(b-tabs): handle cases where `b-tab` has manually specified ID

---

src/components/link/link.js

Checks `evt.currentTarget` instead of `evt.target` when searching for router-link's vue instance in `b-link`.
Fixes #3474

fix(b-dropdown): close when clicking on nested elements inside item with `to` prop (fixes #3474)

---

src/mixins/form-text.js

In rare instances, the input may have been removed from document (during destroy phase) and browser autocomplete triggers a change before removed from document, resulting in `this.$refs.input` being undefined.  Adds in a check in `mixins/form-text` to handle this edge case.
Closes #3498

fix(form-input, form-textarea): handle case where input has been removed from document (closes #3498)

---

src/_variables.scss
src/components/table/_table.scss

Switch from absolute positioning to `display: inline-block` + `float: right` + `::before` (instead of `::after`) for sort icons.
Removes need for `position: relative;` on table header/footer cells which can interfere with dropdowns and tooltips/popovers in headers of responsive tables (note `boundary` option needs to be set on dropdown, tooltip, popover, to allow to break out of responsive table container)
closes #3563 

fix(table): adjustments to sort icon positioning SCSS (closes #3563)

---

src/components/popover/popover.js
src/components/tooltip/tooltip.js
src/directives/popover/popover.js
src/directives/tooltip/tooltip.js
src/utils/tooltip.class.js

This PR passes the parent context rather than root context to tooltips/popovers, so that they can auto-destroy when the parent context is destroyed.
In the earlier days of tooltips/popovers, the tooltip/popover would remain in document when not shown (and in some instanced would remain in document when route changes), where as in later releases tooltips/popovers are only instantiated when shown (and destroyed on hide).
This PR passes the `parent` context to the tooltip/popover class rather than the root context.  So that the tooltip/popover can hook into the parent `destroyed` hooks and destroy itself.
This will be beneficial for those that have tooltips outside of a child `<router-view>` (or `<nuxt-child>`) and the tooltips were being closed when the child route changes.
Now the tooltip …

feat(tooltip, popover): remove need for route watcher

---

docs/markdown/intro/README.md
docs/markdown/reference/router-links/README.md
docs/nuxt.config.js

This PR corrects the polyfilling suggestions in the docs to remove the `mutationobserver-shim` since [IE supports MutationObserver](https://caniuse.com/#feat=mutationobserver).
On the other hand we suggest to optionally include `intersection-observer` to polyfill the [lacking support of IntersectionObserver on some older browsers](https://caniuse.com/#feat=intersectionobserver).

fix(docs): correct polyfilling suggestions

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js
src/components/nav/README.md
src/components/nav/nav-item-dropdown.js
src/mixins/dropdown.js

Adds a new `lazy` prop to dropdowns. If set to `true`, only renders the contents of the menu (default slot) when open.
When `lazy` is set, it will improve memory footprint when many menus appear on a page.
Addresses #3634
To Do:

feat(b-dropdown, b-nav-item-dropdown): add new lazy prop (addresses #3634)

---

src/_variables.scss
src/components/index.scss
src/components/popover/README.md
src/components/popover/_popover.scss
src/components/popover/index.scss
src/components/popover/package.json
src/components/popover/popover.js
src/components/popover/popover.spec.js
src/components/tooltip/README.md
src/components/tooltip/_tooltip.scss
src/components/tooltip/index.scss
src/components/tooltip/package.json
src/components/tooltip/tooltip.js
src/components/tooltip/tooltip.spec.js
src/directives/popover/README.md
src/directives/popover/package.json
src/directives/popover/popover.js
src/directives/tooltip/README.md
src/directives/tooltip/package.json
src/directives/tooltip/tooltip.js
src/directives/tooltip/tooltip.spec.js
src/mixins/toolpop.js
src/utils/config-defaults.js
src/utils/tooltip.class.js

- Add support for tooltip and popover variants
- Add support for custom class for tooltips and popovers
- Improve directive version performance by pre-compiling modifier test regular expressions
New props on components:
- `variant` - supports Bootstrap theme colors (i.e. 'danger', 'primary', 'info', etc)
- `custom-class` - a string classname added to the outer wrapper of the tooltip or popover.
Directive versions have new modifier `v-<variant>`, and support passing optional config options `variant` and `className` (passing config object as the expression) 
Default values (current value is `null`) can be specified via the BootstrapVue global config.
SCSS Notes:
- Tooltip variants use the base Bootstrap theme colors for background, and yiq-color for text.
- Popovers also use the bootstrap …

feat(tooltip, popover): add support for contextual variants and custom class (closes #1983, #2075)

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js

Add a new prop `split-button-type` for specifying the split button's type (`button`, `submit`, `reset`, defaults to `button`).
The prop has no effect if `split-to` or `split-href` is set.
Closes #3694
To Do:

feat(b-dropdown): new `split-button-type` prop to specify split button type (closes #3694)

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
src/components/table/README.md
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js
src/components/table/package.json
src/mixins/normalize-slot.js
src/utils/normalize-slot.js
src/utils/normalize-slot.spec.js

Support new bracketed naming convention for table scoped field slots, deprecate old field slot names.
Now allows for fields with key `default`, and prevents possible conflicts between user field keys and other table slots.
Adds support for default/fallback scoped slots for data cells, header cells and footer cells.
| Slot Usage | Current (deprecated) slot name | New slot naming syntax |
| ------- | --------------- | --------------------- |
| **Data cells** | `<key>`  | `[<key>]`  |
| **Default data cells** | n/a | `[]` |
| **Heading cells** | `HEAD_<key>` | `HEAD[<key>]`  |
| **Default heading cells** | n/a | `HEAD[]` |
| **Footer cells** | `FOOT_<key>` | `FOOT[<key>]` |
| **Default footer cells** | n/a | `FOOT[]`  |
Where `<key>` is the field's key name.
Closes #3731
To Do:
**What kind …

feat(b-table, b-table-lite): new field scoped slot naming convention + new fallback scoped slots, deprecated old field slot convention (closes #3731)

---

src/components/form-checkbox/form-checkbox.spec.js
src/components/form-file/form-file.js
src/components/form-file/form-file.spec.js
src/components/form-radio/form-radio.spec.js
src/mixins/form-radio-check.js

Sets `inheritAttrs: false` and applies `this.$attrs` to the underlying input, so that any non prop attributes are transferred to the input.  Applicable to custom form controls that wrap the input in an outer element.
applies to:
- `<b-form-file>`
- `<b-form-checkbox>`
- `<b-form-radio>`
Closes #3752

feat(b-form-file, b-form-checkbox, b-form-radio): make input element inherit non-prop attributes (addresses #3752)

---

src/_variables.scss
src/components/form-checkbox/README.md
src/components/form-checkbox/_form-checkbox.scss
src/components/form-checkbox/index.scss
src/components/form-checkbox/package.json
src/components/form-file/README.md
src/components/form-file/_form-file.scss
src/components/form-file/form-file.js
src/components/form-file/index.scss
src/components/form-file/package.json
src/components/form-radio/README.md
src/components/form-radio/_form-radio.scss
src/components/form-radio/index.scss
src/components/form-radio/package.json
src/components/index.scss
src/components/input-group/README.md
src/components/input-group/package.json
src/components/table/README.md
src/mixins/form-radio-check.js

Adds ability to specify size (`sm` or `lg`) to the following custom controls:
Bootstrap v4.x most likely wont include custom-control sizes (except for custom-select for which sizes are currently supported), while bootstrap v5 will.
For form-file, radios and checks, it uses the custom classes `b-custom-control-sm` and `b-custom-control-lg` for controlling sizing.
Closes #3745
To Do:

feat(form controls): add support for control sizing of `b-form-file`, `b-form-checkbox`, and `b-form-radio` (closes #3745)

---

src/components/tabs/tabs.js

This PR fixes the `id` and `aria-controls` attributes of the `<b-tab>` nav items.
Closes #3831.

fix(tabs): nav item `id` and `aria-controls` (closes #3819)

---

src/_variables.scss
src/components/table/README.md
src/components/table/_table.scss
src/components/table/helpers/mixin-table-renderer.js
src/components/table/helpers/table-cell.js
src/components/table/table.spec.js

Adds in support for sticky table headers (with graceful fallback for IE11)
New prop `sticky-header`, when set to true enables headers that remain sticky when table is scrolled. Default max-height is set to 300px in CSS, but users can optionally set `sticky-header` to a string that specifies the `max-height`.
Supported on `b-table`, `b-table-lite` and `b-table-simple`
Closes #2085
Closes #555

feat(table): add sticky header support (closes #2085)

---

docs/components/importdoc.vue

Removes showing deprecated import paths from plugin import table. Leaves warning alert below plugin import table re deprecated import paths.

chore(docs): remove deprecated import paths from importdoc.vue

---

src/components/modal/README.md
src/components/modal/modal.js
src/components/modal/modal.spec.js

Prevent the page from scrolling when tabbing to bottom of modal when enforce focus is enabled.
Closes #3842 
Also adds in handling of <kbd>CTRL</kbd>+<kbd>TAB</kbd> within enforce focus routine.

fix(b-modal): prevent page scroll when tabbing to bottom of modal + better tab containment in enforceFocus (closes #3842)

---

src/components/table/README.md
src/components/table/helpers/mixin-selectable.js
src/components/table/helpers/mixin-tbody-row.js
src/components/table/index.d.ts
src/components/table/table-selectable.spec.js

Adds in the ability for programmatic row selection
New Public methods on BTable instance (when in selectable mode):
- `selectRow(index)`
- `unselectRow(index)`
- `isRowSelected(index)`
- `selectAllRows()`
- `clearSelection()`
Notes:
- `index` refers to the displayed row index number, which is not necessarily the actual index in the original source array (the index is computed after sorting, filtering, pagination have been applied)
- If  `select-mode` is `single`, then `selectAllRows()` will only select the first row, and `selectRow(index)` will unselect any previously selected row
Closes #3064 
Closes #3370
To Do:
**If new …

feat(b-table): programmatic row selection (closes #3064, #3370)

---

CHANGELOG.md
src/components/table/README.md
src/components/table/_table.scss

Minor updates to the table docs
Also added comment to table sticky SCSS re upstream issue at twbs/bootstrap re table color inheritance.

chore(docs): minor updates to the table docs

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
src/components/nav/nav.spec.js
src/components/table/README.md
src/components/table/helpers/mixin-filtering.js
src/components/table/helpers/mixin-items.js
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js
src/components/table/helpers/normalize-fields.js
src/components/table/helpers/normalize-fields.spec.js
src/components/table/package.json
src/components/table/table-row-details.spec.js
src/components/table/table-tbody-row-events.spec.js
src/components/table/table-tfoot-events.spec.js
src/components/table/table-thead-events.spec.js

This PR removes the deprecations from the `<b-table>` and `<b-table-simple>` components.
Users should now be using slots `cell[field]` instead of `field`, `head[field]` instead of `HEAD_field`, and `foot[field]` instead of `FOOT_field`. Noe these new slot names are different than teh ones introduced in 2.0.0-rc.28.
The changes are needed due to the new Vue `v-slot` syntax

feat(table): remove deprecated slot names

---

src/components/modal/README.md
src/components/modal/modal.js
src/components/modal/modal.spec.js

Adds a new prop `auto-focus-button` which accepts a string value of `'ok'`, `'cancel'`, or `'close'`, which will auto-focus one of the respective built in buttons (if present).
Falls back to focusing the modal content container (default action) if not set, or the button is not found.
Works with modal message boxes as well.
Closes #3945
Replaces #3542
To Do:

feat(modal): add prop for auto focusing one of the built in-buttons once `shown` (closes #3945)

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
src/components/table/README.md
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js
src/components/table/table-row-details.spec.js
src/components/table/table-tbody-row-events.spec.js
src/components/table/table-tfoot-events.spec.js
src/components/table/table-thead-events.spec.js

Switch `cell[...]`, `head[...]` and `foot[...]` slot name syntax to `cell(...)`, `head(...)` and `foot(...)` syntax, to prevent user confusion with [dynamic slot name](https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names) syntax.
Since we are breaking the slot names in 2.0.0 stable, this is the time to make the change.
Similar to the PR that changed the slot names to lower-case and square brackets

feat(b-table, b-table-lite): switch slot name syntax to use round brackets instead of square brackets

---

src/components/table/helpers/mixin-tbody-row.js

Changed from attribute `aria-describedby` to `aria-details` when a row has details showing.
`aria-describedby` is read out by screen readers as a flattened string of the text content (which may not always make sense with complex markup such as sub tables). `aria-details` is similar, but just informs the user that there is a landmark region with additional details that they user can navigate to.
Addresses part of #3801

feat(b-table, b-table-lite): use `aria-details` rather than `aria-describedby` when details row showing (addresses #3801)

---

src/components/dropdown/dropdown-divider.js
src/components/dropdown/dropdown-form.js
src/components/dropdown/dropdown-group.js
src/components/dropdown/dropdown-header.js
src/components/dropdown/dropdown-item-button.js
src/components/dropdown/dropdown-item.js
src/components/dropdown/dropdown-text.js

Adds `role="presentation"` to all `<li>` elements in the dropdown sub items

feat(dropdown): add `role=presentation` to `<li>` elements for improved a11y

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-tbody.js

Will help improve performance (slightly) by not having to compute the possible slot names for each row rendered.
The cell slot names will only be looked-up once each render cycle.
Uses a non-reactive property on the table instance to store the cache.
Closes #4008 (partially)
Performance is still slow when table has 1000+ rows displayed, but is slightly improved.
User should be presenting paginated data (e.g. 100 rows at a time) rather than generating 1000 rows on screen. …

perf(b-table): cache cell slot names each render cycle (addresses #4008)

---

src/directives/popover/popover.js
src/directives/tooltip/tooltip.js

Restores revious functionality on the tooltip/popover directives. Ensures, if title/content is a function, that the function is called before the tooltip/popover is opened.
I had missed this when revamping tooltips and popovers.

chore: tooltip/popover directives execute title/content if function before each show

---

src/components/table/helpers/mixin-tbody-row.js

Row details was always using the physical row index to generate the Vue render `:key`, causing any row details child components to re-render if new rows were prepended (`unshift`ed) to the items array.
This PR makes the details row use a `:key` based on the item's row key (based on primary key field if available). This will prevent unnecessary re-renders of components inside details slot (as long as a `primary-key` field is provided).
Improves render performance when using child components in a `row-details` slot.
Fixes an issue on stackoverflow: 
https://stackoverflow.com/questions/57708063/b-table-reloads-nested-components-when-unshifting-a-new-row-but-not-when-pus
**Does this PR introduce a breaking change?** (check …

fix(b-table, b-table-lite): generate `:key` for `row-details` row based on the `primary-key` field value if available

---

src/components/dropdown/dropdown-divider.js
src/components/dropdown/dropdown-form.js
src/components/dropdown/dropdown-group.js
src/components/dropdown/dropdown-header.js
src/components/dropdown/dropdown-text.js

Makes all dropdown sub-components behave the same as `<b-drodpown-item>` and `<b-dropdown-item-button>` when it comes to class bindings being placed on sub-component's root element
Non prop attributes are transferred to the inner element
Closes #4022 

fix(b-dropdown-*): ensure class bindings are placed on root element for all dropdown sub-components (closes #4022)

---

src/components/table/README.md
src/components/table/helpers/mixin-tfoot.js
src/components/table/package.json
src/components/table/table-tfoot-custom.spec.js

New optionally scoped slot `custom-foot` to allow users to provide their own custom footer content.
Contents of this slot will be rendered inside a `<b-tfoot>` component.  Users should use `<b-tr>` and `<b-th>`/<`b-td>` sub components to build their desired footer structure.
Scoped props passed to the slot:
- `items` a shallow copy of the displayed rows item data (array of objects)
- `fields` a shallow copy of the normalized fields array in array of objects form
- `columns` the number of columns (fields) in the table.
If the `foot-clone` prop is set, then the `custom-foot` slot will **not** be shown.
Closes #3960 
**If new …

feat(b-table, b-table-lite): add new scoped slot `custom-foot` to allow user to create their own table footer (closes #3960)

---

CHANGELOG.md
package.json
src/directives/popover/README.md
src/directives/tooltip/README.md

Bump version to 2.0.0 stable, update changelog.
Includes a migration section in the changelog entry.
Plus a few minor tweaks to the tooltip/popover directive docs

chore: bump version and update changelog

---

src/components/toast/_toaster-transition.scss
src/components/toast/_toaster.scss

Cleans out the old commented out sections of b-toaster scss

chore(b-toaster): clean out old toaster scss comments

---

src/components/table/package.json

Fixes the published docs (master branch) for table slot names in package.json meta

chore(docs): hotfix slot names in table package.json meta

---

src/components/table/README.md
src/components/table/_table.scss

Re-declares the `table-active` row variant class after any other row-variant classes so that it can take precedence when using it as the `selected-variant` for selectable rows.
Addresses #3008 (but only when using `selected-variant="active"`)
To Do:

fix(tables): ensure row variant `active` (class `table-active`) takes precedence over other row variants (addresses #3008)

---

src/components/toast/README.md

Add an example of using a fixed position alert instead of toasts.

docs(b-toast): show example of using `<b-alert>` as an alternative to a toast

---

CHANGELOG.md
docs/markdown/misc/third-party/README.md
docs/markdown/misc/third-party/meta.json
docs/markdown/reference/color-variants/README.md
package.json
src/_variables.scss
src/components/collapse/README.md
src/components/collapse/collapse.js
src/components/modal/README.md
src/components/popover/package.json
src/components/popover/popover.js
src/components/table/README.md
src/components/table/_table.scss
src/components/toast/README.md
src/components/tooltip/helpers/bv-tooltip.js
src/components/tooltip/package.json
src/components/tooltip/tooltip.js
src/directives/popover/README.md
src/directives/popover/popover.js
src/directives/tooltip/README.md
src/directives/tooltip/tooltip.js
yarn.lock

Preparation for release v2.0.2
- `tables`: add in missing Bootstrap v4.3 variant class `bg-active` for dark tables
- `tables`: ensure row variant `active` takes precedence over other row variants
- `tooltips, popovers`: hide trigger element `title` attribute during show delay
- `b-collapse`: don't make `id` prop required
- `b-popover`, `b-tooltip`: ensure `boundary-padding` is passed to popper instance
Additional docs updates and fixes

chore: release v2.0.2

---

src/components/form-file/README.md
src/components/form-file/form-file.js
src/components/form-file/form-file.spec.js
src/components/form-file/package.json
src/utils/inspect.js

When creating the new props docs and web-types (for yet to be released v2.0.3), the value type was changed to `[File, Array]` from `Any` (`undefined`) for better prop docs generation.
The resetting of the file control can be done by setting to `null`, and empty array, or an empty string, and when doing so Vue would emit an prop type check warning (when using empty string to reset the input).
This adds a deprecation message to have users switch to setting to `null` instead of empty string, and uses a custom validator to check the prop type/value
**If adding a new …

fix(b-form-file): fix prop type checking for `value` prop

---

src/components/navbar/package.json

1. `Ste` -> `Set`
2. `'sn', 'ms'` -> `'sm', 'md'`

chore(docs): fix navbar typo

---

src/components/card/index.d.ts

When we importing b-card-sub-title component individually, typescript throws following error:
```
Module '"../../node_modules/bootstrap-vue/src"' has no exported member 'BCardSubTitle'. Did you mean 'BCardSubtitle'?
```
Fix incorrect export declaration of BCardSubTitle component.

fix(types): BCardSubTitle component declared export name

---

src/components/tabs/README.md
src/components/tabs/package.json
src/components/tabs/tabs.js
src/components/tabs/tabs.spec.js

Emit new event `activate-tab` before changing tabs.
New event is emitted with three arguments:
- `newTabIndex` tab index that will be activated
- `prevTabIndex` tab index of the current active tab, or -1 if no active tab
- `bvEvt` BvEvent object instance
Calling `bvEvt.preventDefault()` will prevent the tab from activating.
Ideally users should be setting the `disabled` prop on any `<b-tab>` they don't want users to activate (better for accessibility). If users do use this event to prevent a tab from activating, they should provide feedback to the user as to why the tab cannot be activated (i.e. an alert, etc).
Closes #4273
To Do:
**The PR fulfills these …

feat(b-tabs): emit cancelable BvEvent before changing tabs via new `activate-tab` event (closes #4273)

---

src/components/table/package.json

Corrects table package.json meta prop descriptions: transition-list=> transition-group

chore(table meta): `transition-list` => `transition-group`

---

docs/markdown/intro/README.md
src/components/form-input/README.md
src/components/form-input/form-input.spec.js
src/components/form-input/package.json
src/components/form-textarea/README.md
src/components/form-textarea/package.json
src/components/table/README.md
src/components/table/helpers/mixin-filtering.js
src/components/table/package.json
src/components/table/table-filtering.spec.js
src/mixins/form-text.js

Adds a new prop `debounce` that will allow users to specify a debounce timeout for updating the v-model.
Internally debounces the v-model `update` event.  Note `change`/`blur` events will immediately update the v-model.
If prop `lazy` is set, then no debouncing is used.
Defaults to no debouncing (`0` ms)
Addresses #4150 as a preferred way of debouncing table filter criteria
Probably closes #4288 for similar reasons
To Do:

feat(b-form-input, b-form-textarea): add `v-model` debouncing feature, and deprecate `<b-table>` prop `filter-debounce` (closes #4150)

---

src/components/tabs/README.md
src/components/tabs/tabs.js
src/components/tabs/tabs.spec.js

fix(b-tabs): allow space to trigger tab activation when `no-key-nav` is enabled (fixes #4323)

---

src/directives/popover/popover.js
src/directives/tooltip/tooltip.js

During the re-write of the popover and tooltip directives the element reference passed to the title/content functions (if they are a function) was inadvertently left out.  This PR adds passing the element reference back in.
Fixes #4331

fix(v-b-tooltip, v-b-popover): ensure reference to trigger element is passed to title/content function (fixes #4331)

---

src/components/tabs/README.md

Updated docs to include lazy loaded tab content use case in #4352
closes #4352

docs(tabs): document load tab content only when active (closes #4352)

---

src/directives/modal/modal.js
src/directives/modal/modal.spec.js

When the `v-b-modal` directive is used on non-link elements (`a`), users can only open it using the spacebar. This adds inconsistency where other implementations (because they're link elements) can be opened using the `Enter` key.
From https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls#Example_1:_Using_Space_to_activate_a_button:
> Adding the ARIA role "button" makes it clear that this is a button control and not a link. Because we are using an anchor element, the control is focusable and the browser will automatically call the onclick handler for the Enter keystroke. Since users expect to be able to activate buttons with either Enter or Space, a keyboard handler provides the support for activating the button via the …

fix(v-b-modal): open modal using `ENTER` key on non-button elements for A11Y

---

src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js
src/components/dropdown/package.json

Adds a `splitClass` property to the dropdown component to allow setting a custom class selector to the dropdown split button when split mode is enabled. 
**Why is this necessary?**
We need to customize the dropdown’s split and toggle buttons based on our design system specifications. We apply these customizations by adding a custom class selector using the `toggleClass` property for the toggle button. We also want to apply a  class selector to the split button, but the dropdown component don’t expose a property to achieve that. 
We are using a [workaround](https://gitlab.com/gitlab-org/gitlab-ui/merge_requests/896/diffs#b508c38bfed76f7489eae21f5fd6cae969094e7a_76_93) of applying these classes when the component is updated, but we’d like to replace it with a sound approach.
**What kind of …

feat(b-dropdown): add splitClass property to dropdown component

---

src/components/collapse/README.md
src/components/collapse/collapse.js
src/components/collapse/collapse.spec.js
src/components/collapse/package.json

Optionally scoped default slot:
Scope:
- `close()` method for closing the collapse
- `visible` visible state of collapse (boolean)

feat(b-collapse): add optional scoping to default slot

---

src/components/layout/README.md
src/components/layout/col.js
src/components/layout/package.json
src/components/layout/row.js
src/components/layout/row.spec.js

Adds support for Bootstrap v4.4 row columns on `b-row`, via new props `cols`, `cols-sm`, `cols-md`, etc.
https://getbootstrap.com/docs/4.4/layout/grid/#row-columns

feat(b-row): add Bootstrap v4.4 row columns support

---

src/components/dropdown/dropdown-form.js
src/components/dropdown/dropdown-form.spec.js
src/components/dropdown/package.json

We use `b-dropdown-form` in a bunch of places (mostly advanced search filters), and want to have control over the form class[es]. It's less complex and more reusable to specifically list the form classes in the parent component, rather than specifying prop options for layout and/or using multiple css selectors. Currently, passing a class prop on `b-dropdown-form` sets the `class` on the `li`.
Closes #4474

feat(b-dropdown-form): add formClass prop for adding classes to the form element (closes #4474)

---

src/index.d.ts

The main typescript declaration file included the `default` export (BootstrapVue plugin), but was missing the named export for `BootstrapVue`
Replaces #4588 
Thanks @keithn for the heads up!

fix(typescript): include named export `BootstrapVue` in type declaration file

---

src/components/form-select/index.d.ts

Adds in missing type declarations for `<b-form-select-option>` and `<b-form-select-option-group>`
https://stackoverflow.com/questions/59678515/b-form-select-option-not-working-in-bootstrap-vue

fix(types): add missing declarations for `b-form-select-option` and `b-form-select-option-group`

---

src/directives/modal/modal.js

Prevent un-necessary unbind/rebind when parent component updates, by checking if values have changed (modal ID or triiger element).
In some cases when the parent component re-rendered due to a state change on a click handler, the directive would rebind and the modal open event would not have a chance to emit.
Fixes #4669  

fix(v-b-modal): only unbind/rebind if trigger element or modal ID changes (closes #4669)

---

CHANGELOG.md
package.json
src/components/dropdown/README.md
src/components/dropdown/dropdown-item-button.js
src/components/dropdown/dropdown-item.js
src/components/dropdown/dropdown.js
src/components/form-input/README.md
src/components/form-textarea/README.md
src/components/modal/README.md
src/components/modal/modal.js
src/components/modal/modal.spec.js
src/components/modal/package.json
src/components/nav/nav-item-dropdown.js
src/components/nav/package.json
src/components/navbar/navbar.js
src/components/navbar/navbar.spec.js
src/components/table/README.md
src/icons/README.md
src/mixins/click-out.js
src/mixins/dropdown.js
src/mixins/form-text.js
yarn.lock

- `b-modal`: new `ignore-enforce-focus-selector` prop (closes #4537)
- `b-nav-item-dropdown`: add `boundary` prop, applicable when not in `b-navbar` (closes #4684)
- `b-dropdown`: focus-in handling for Safari and Firefox on macOS/iOS (closes #4328)
- `b-form-input`, `b-form-textarea`: properly handle out-of-sync values (closes #4695)
- dev dependencies update
- minor docs updates

chore: release v2.4.0

---

src/components/popover/README.md
src/components/tooltip/README.md
src/components/tooltip/_tooltip.scss
src/directives/popover/README.md
src/directives/tooltip/README.md

This PR fixes the `<b-tooltip>` arrow margin.
Bootstrap defines an arrow margin for the `.popover` that equals the `border-radius`.
This arrow margin is missing for `.tooltip`.
Closes #4272.

fix(b-tooltip): fix arrow margin (closes #4721)

---

src/components/form-radio/README.md

Add clarification to v-model section
Closes #4736 

docs(form-radio): add clarification to v-model section (closes #4736)

---

src/components/form-input/README.md
src/components/form-radio/README.md
src/mixins/form-text.js

Stops ignoring change events if `evt.taget.composing` flag is still set by Vue. 
Also adds notes to docs about mobile browser keyboard predictive text handling and IME composition handling.
Closes #4724

fix(b-form-input, b-form-textarea): handle change event for all mobile device keyboards (closes #4724)

---

src/components/form-spinbutton/_spinbutton.scss
src/components/form-spinbutton/form-spinbutton.js
src/components/form-spinbutton/form-spinbutton.spec.js

Use CSS to avoid having to place `dir="ltr"` on the flex container to prevent flex column re-ordering

fix(b-form-spinbutton): prevent buttons from re-ordering when parent element is RTL

---

src/components/table/package.json

There was a typo in the `sortCompare` key for the table components meta data inside `package.json`, which is fixed with this commit.
Simple typo fix in the table docs

chore(docs): fix typo in table docs

---

src/components/calendar/README.md
src/components/calendar/calendar.js
src/components/calendar/package.json
src/components/form-datepicker/README.md
src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json

Added prop to allow formatting of in-component displayed date string to allow better control of size (and a better integration with other components defining these format, e.g. vue-i18n). This is especially helpful for space-constrained usage in forms.
Closes #4797

feat(b-calendar, b-form-datepicker): allow customization of in-component displayed date format (closes #4797)

---

src/components/form-spinbutton/form-spinbutton.js

Prevent double increment/decrement when clicking `+`/`-` buttons on mobile/touch devices
Fixes #4838

fix(b-form-spinbutton): prevent double increment/decrement on mobile (fixes #4838)

---

src/components/form-timepicker/README.md
src/components/time/README.md
src/components/time/time.js

IE 11 does not resolve the `hourCycle`, so we add basic fallback support based on the resolved `hour12` value. For most locales this should be fine if the `hour12` prop is left as `null`

chore(b-time): add fallback of `hourCycle` for IE 11 support

---

src/icons/README.md

Adds a note re alpha2 to alpha3 changes

chore(docs): note changes from alpha2 to alpha3 icons

---

src/components/collapse/collapse.js
src/components/navbar/README.md
src/components/navbar/navbar-toggle.js
src/components/navbar/navbar-toggle.spec.js
src/components/navbar/package.json
src/directives/toggle/toggle.js

Makes the default slot of `<b-navbar-toggle>` scoped, with the scope containing the collapse's expanded state.
Also documents that the component _has_ a default slot
Plus minor code refactor for reduced bundle size

feat(b-navbar-toggle): make default slot scoped

---

docs/pages/play.vue

The playground export to CodePen/CodeSandbox/JsFiddle was not installing the icons plugin.

fix(docs): ensure that the IconsPlugin is imported when exporting from playground to CodePen, CodeSandbox, and JsFiddle

---

src/components/tooltip/helpers/bv-tooltip.js
src/components/tooltip/tooltip.spec.js

Additional unit test for tooltip/popover for code coverage

chore(tooltip, popover): add tests for modal close event

---

src/components/calendar/calendar.js

Allows for keyboard navigation when initial selected date is out of range
Fixes #5057 

fix(b-calendar, b-form-datepicker): handle keyboard navigation when selected date is out of range (fixes #5057)

---

src/components/calendar/README.md
src/components/calendar/calendar.js
src/components/calendar/package.json
src/components/form-datepicker/README.md
src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json
src/utils/object.js
src/utils/object.spec.js

Adds scoped slots for calendar date navigation button content
Closes #5117 

feat(b-calendar, b-form-datepicker): add scoped slots for date navigation buttons (closes #5117)

---

.gitignore

To trigger a zeit redeploy on master branch, to ensure auto-deploy is working

chore: remove old `es/` dir from gitignore on master branch

---

.github/renovate.json

As v10.x.x of highlight.js does not support IE11 browser (https://github.com/highlightjs/highlight.js/issues/2501)
Closes #5212

chore: don't let renovate update hightlight.js past 9.x.x

---

src/_custom-controls.scss

Additional custom SCSS to allow b-form-datepicker and b-form-time-picker  (non button mode) to be placed as main input in input groups. Button mode already works well with input groups.
~It is not quite perfect for sm input-groups as the input-group ends up being 2px taller than normal small input groups.~

fix(b-form-datepicker, b-form-timepicker): adjust scss to support input-groups

---

src/components/overlay/overlay.js
src/components/overlay/overlay.spec.js
src/components/overlay/package.json

This PR adds support for the `click` event on the `<b-overlay>` component's overlay.

feat(b-overlay): add support for overlay `click` event (closes #5243)

---

src/components/table/index.d.ts

Update types for b-table field definition to include stickyColumn
Fixes #5263

fix(types): update table field definition types to include sticky column (fixes #5263)

---

docs/common-props.json
docs/markdown/reference/router-links/README.md
src/components/avatar/avatar.js
src/components/badge/badge.js
src/components/breadcrumb/breadcrumb-link.js
src/components/button/button.js
src/components/dropdown/dropdown-item.js
src/components/dropdown/package.json
src/components/link/README.md
src/components/link/link.js
src/components/link/link.spec.js
src/components/link/package.json
src/components/list-group/list-group-item.js
src/components/nav/nav-item.js
src/components/navbar/navbar-brand.js
src/components/navbar/navbar.js
src/components/pagination-nav/pagination-nav.js
src/components/table/td.js
src/components/toast/toast.js
src/utils/config-defaults.js
src/utils/dom.js
src/utils/router.js

Adds a new prop `router-component-name`, which defaults to `undefined`.
Default is to auto detect `<router-link>` or`<nuxt-link>`.
Gridsome does not provide a means for detecting that the app is running under Gridsome, so users who wish to use `<g-link>` can set this prop to `'g-link'`
Notes:
- if `vue-router` is not detected, then the user supplied router-link component will not be used.
- If vue-router is detected, and `g-link` is not a registered component, then the render or the link will fail
- Gridsome's `<g-link>` component does not support FQDN URLs nor hash only URLs (https://gridsome.org/docs/linking/)
To Do:
Possible ToDo:
- Check to see if the user supplied component name is registered with Vue, and if not, fallback to `<router-link>`
Closes #2627
**What kind of change does …

feat(b-link): add support 3rd party router links such as Gridsome's `<g-link>` (closes #2627)

---

src/directives/toggle/README.md
src/directives/toggle/toggle.js

Do not check for `evt.defaultPrevented` before dispatching toggle control event.
Closes #5391

fi(v-b-toggle): don't check for `evt.defaultPrevened` (closes #5391)

---

src/components/sidebar/README.md
src/components/sidebar/_sidebar.scss
src/components/sidebar/package.json
src/components/sidebar/sidebar.js
src/components/sidebar/sidebar.spec.js
src/utils/config-defaults.js

This PR adds an additional property `backdrop-variant`.
You can use the `backdrop-variant` prop to control the theme color variant of the backdrop.

feat(b-sidebar): add prop `backdrop-variant`

---

src/components/form-checkbox/form-checkbox-group.spec.js
src/mixins/form-radio-check-group.js
src/utils/loose-equal.js

Uses `looseEqual` to determine if the `input` event should be emitted.
This will prevent input event loops when the array reference changes, but the contents are the same.
StackOverlow issue: https://stackoverflow.com/questions/62002613/computed-property-setter-creates-maximus-stack-exceeded
To Do:

fix(b-form-checkbox-group): only emit `input` when value loosely changes

---

src/components/table/helpers/mixin-items.js

When using `b-table` with `v-model`, specifying certain props such as `items` and `sortCompareOptions` as object or array literals in the template would cause the browser to hang.
The cause was that `computedItems` depends on a chain of computed properties, some of which return a new array of items every time they're reevaluated, meaning that every reevaluation would cause the `input` event to be emitted. This would normally work because of computed property caching, but if a dependency was specified in the template using an object or array literal, the property would have to be recomputed each time resulting in an infinite loop. For example, the `sortedItems` computed property depends on `items` and `sortCompareOptions` (#5461 has an example using the latter and …

fix(b-table): prevent endless reevaluation when using v-model and object/array literal prop values (fixes #5461)

---

src/components/navbar/navbar-toggle.spec.js
src/directives/toggle/toggle.js
src/directives/toggle/toggle.spec.js

When the element with the `v-b-toggle` directive assigned had other click handlers assigned that triggered a re-render of the element, the toggle click handler was not fired since we re-assign it to pick up any target changes.
This PR adds a `requestAnimationFrame()` call before re-assigning the click listeners in order to allow any previous click handling to occur first.
Closes #5475.

fix(v-b-toggle): handle component updates on click listeners (closes #5475)

---

src/components/button-toolbar/button-toolbar.js

This PR fixes an issue that prevented the user from being able to leave the focus of the `<b-button-toolbar>` by keyboard (SHIFT + TAB).
Closes #5733.

fix(b-button-toolbar): allow focus to leave toolbar by keyboard when `key-nav` enabled (closes #5733)

---

src/components/modal/helpers/bv-modal.js
src/components/toast/helpers/bv-toast.js
src/components/tooltip/helpers/bv-popper.js
src/components/tooltip/helpers/bv-tooltip.js

This PR fixes the `v-b-popover` / `v-b-tooltip` destroy behavior when the parent gets destroyed.
While at it, this PR unifies the logic to do so for all components that need to destroy itself on parent destroy.
Closes #5747.

fix: component destroy handling on parent destroy (closes #5747)

---

src/components/form-tags/_form-tags.scss
src/components/form-tags/form-tags.js

This PR ensures that `<b-form-tags>` has the same height with or without tags.
The issue was introduced with #5544 which removed the top margin from the field `<li>` element which holds the `input` and the add `button`. Since this element is always rendered, other than the tags, adding the same top margin as the tags ensures it always balances the negative margin of the tags list element.
While at it, this PR unifies the `safeId()` and element `keys`.
It also fixes a small a11y where the `aria-describedby` of  `<b-form-tags>` pointed to the wrong ID which was introduced during the changes made in #4775.
Closes #5750.
**If …

fix(b-form-tags): ensure same height with or without tags (closes #5750)

---

src/mixins/form-radio-check.js

This PR removes the `autocomplete="off"` from the `<b-form-checkbox>` and `<b-form-radio>`components which causes a W3C validation error.
The attribute was added way back to work around a issue in older Firefox versions:
> This is to prevent a bug with some older versions FireFox. The bug is when you have a form on one page (with checkboxes or radios) and then link to a new page, and then the user uses the browser back button to return to the previous page. Firefox would retain the previously selected values but wouldn't issue a change event.
Users facing this issue are better off adding the `autocomplete="off"` attribute to the `form` element containing the checkboxes/radios.
Closes #4230.
**Does this PR introduce a …

fix(b-form-checkbox/b-form-radio): remove `autocomplete="off"` attribute (closes #4230)

---

docs/markdown/intro/README.md

This PR corrects the Bootstrao SCSS imports in the "Getting Starting" section of the docs.
Close #5920.

chore(docs): correct Bootstrap SCSS imports (closes #5920)

---

src/components/table/helpers/mixin-thead.js
src/components/table/table-sorting.spec.js

This PR ensures that only sortable fields have a `tabindex="0"`.
Closes #6097.

fix(b-table): only set `tabindex="0"` for sortable fields (closes #6097)

---

src/components/form-btn-label-control/bv-form-btn-label-control.js
src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/form-datepicker.spec.js
src/components/form-timepicker/form-timepicker.js
src/components/form-timepicker/form-timepicker.spec.js

This PR ensures only the `sr-only` class is applied to the `label` when `<b-form-datepicker>` / `<b-form-timepicker>` are in `button-only` mode.
Closes #6172.

fix(b-form-datepicker/b-form-timepicker): label styles when in `button-only` mode (closes #6172)

---

src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js
src/components/dropdown/package.json

Add `toggle-attrs` prop to allow adding HTML attributes to the dropdown toggle. This feature has been talked about here: https://github.com/bootstrap-vue/bootstrap-vue/issues/3694
At GitLab we have a [component library](https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-dropdown--default) built on top of Bootstrap Vue and would like this feature so that we can add the `data-qa-selector` attribute to the dropdown toggle. We use this attribute exclusively for QA E2E specs. I could also see it being helpful for adding the `data-testid` attribute which is supported by [Vue Testing Library](https://testing-library.com/docs/vue-testing-library/api#queries). This prop could also be used for other user-facing attributes such as `aria-*` attributes.
Closes #3694.
**What kind of change does …

feat(b-dropdown): add `toggle-attrs` prop (closes #3694)

---

docs/markdown/intro/README.md

Hi, I was trying to apply the library to a personal project when I noticed a small error in the documentation. **The links in the part that indicate that the library can be imported into html were missing the protocol**, which caused a little inconvenience having to enter them manually. I took the liberty of making the changes and submitting this PR, I apologize for not opening an issue first, I am still learning to collaborate with open source projects.
description above …

fix(docs): completing the url so that the link is correct

---

src/components/table/helpers/mixin-sorting.js
src/components/table/table-sorting.spec.js

Fixes an issue where `aria-sort` wasn't being correctly set on fields that used a `sortKey` and `no-local-sorting` was set on `<b-table>`.
It should now correctly set them when sorting that column.
Closes #6602.
Working example: https://codesandbox.io/s/bootstrapvue-starter-project-forked-3b7pt?file=/App.vue

fix(b-table): set `aria-sort` when using `sortKey` and `no-local-sorting` (closes #6602)

---

src/_variables.scss
src/components/form-checkbox/_form-checkbox.scss
src/components/form-input/_form-input.scss
src/components/form-radio/_form-radio.scss
src/components/skeleton/_skeleton.scss

Replace Sass division with multiplication (required for sass versions greater than 1.32.13) (fixes #6830)
**Does this PR introduce a breaking change?** 

fix: replace sass division with multiplication (fixes #6830)

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/test.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions
