bootstrap-vue/bootstrap-vue

- components/tab.vue
https://vuejs.org/v2/guide/migration.html#vm-get-removed
> $get has been removed from Vue 2.0

- components/progress.vue
I fixed progress undefined var issue #33, reorganized props and fixed css issues to be up to date regarding  [Bootstrap 4 documentation](https://v4-alpha.getbootstrap.com/components/progress/)
> Fixed issues on b-progress #33

- components/carousel.vue
- components/components.js
Thanks @RobinRadic for the carousel.vue issue
I also fixed importation mistakes
> Fixed carousel issues #17

- README.md
> added note re: bootstrap CSS

- docs/pages/docs/components/dropdowns.vue
The `dropdown-menu` div is already in the component.
> Fixed dropdowns documentation mistake

- components/form-fieldset.vue
- components/form-input.vue
- components/form-select.vue
Now user can choose between horizontal and vertical form layouts
Like in this article [http://stacktips.com/tutorials/bootstrap/vertical-horizontal-and-inline-form-example-in-bootstrap](url)
> Added ability to choose form layout for input and select

- components/dropdown.vue
- package.json
Also changed version from 0.6.0 to 0.6.1 indicating a bug fix.
> Changed 'open' class for 'show'. Fixes #90

- components/table.vue
resolves #98 
In the absence of any unit tests (that I could see...?) I tested with my use case and also ran the build scripts to make sure there were no obvious build errors.
- Tested locally as per #98 - resolves the error reported
- Ran build script which completed without errors
- Ran `yarn build` which completed without errors
> added explicit import of pagination component to table.vue

- components/form-input.vue
I find it useful to have access to the change event in the parent component as well. This way I can do "unformats", for instance.
> Emit change event to parent component

- components/tab.vue
- components/tabs.vue
made the tabs be able to be set using :value and it will emit a input that can be used for vuex and vue-router
> [Tabs component] updates

- components/modal.vue
Fix for events not being destroyed on destruction.
> remove event listener on destruction

- components/tabs.vue
- Fixed visual bug with button class
- Changed HTML tags to the offical bootstrap syntax
- Removed size property
- Added the possibility to render small tabs
> Visual tabs bug fixed

- components/tabs.vue
- Prevent to jump to top by click on a tab
> Behaviour tabs bug fixed

- components/dropdown.vue
Fix dropdown.vue import button issue.
> fix dropdown.vue import button issue

- docs/pages/docs/index.vue
> Fixed a typo

- components/nav-item-dropdown.vue
- docs/pages/docs/components/navbar.vue
- Change open class from `open` to `show` to match latest
boostrap version
- Use text prop if provided in the main slot
- Add documentation in the navbar section
- Try to improve markup indentation
> Improve and document b-nav-item-dropdown

- lib/components/button.vue
- lib/components/collapse.vue
- lib/components/dropdown.vue
- lib/components/link.vue
- lib/components/nav-item.vue
Futher dropdown elements fixes and enhancements to make them act like original Bootstrap
Add event object to all custom click events to make .stop and .prevent modifiers work
> Futher fixes on dropdowns and link

- lib/components/form-input.vue
- lib/components/nav-item.vue
I had to make some fixes for a project I'm working on. I'm sharing them back upstream.
In details :
- Uses directly the bLink components by importing it. I'm using Vue without the template compiler and it rightly complained about not knowing `b-link`. This fixes that issue.
- ~~Slight code improvement for bFormInput: it uses `is` instead of `v-if` to switch between input and textarea. If found this cleaner.~~
- Blur and focus events from input and textarea and propagated up to chain in bFormInput.
> Couple of fixes

- lib/components/button.vue
Same drill as last time. (#174)
> b-button: Remove warning by importing b-link

- lib/components/table.vue
We wanted to have the ability to redirect when clicking a row instead of using a button. We opted to go with passing a function to the component and have that function execute when the row is clicked in which we redirect.
Using a function will give us some flexibility in the case that we might want to do something else.
If there is a builtin/easier way to do this then we'd like to know about and forget about this pull request.
> Add clickable table row

- examples/dropdown/demo.html
- lib/components/dropdown.vue
The dropdown component is using the button as the default dropdown toggle, so I have added the btn-link class to the button when using the link prop, so the styling to the button changes.
> implemented link prop for dropdown

- lib/components/popover.vue
Fixes https://github.com/bootstrap-vue/bootstrap-vue/issues/249
> Popover - Fix offset validation, add targetOffset property

- lib/components/popover.vue
Per https://github.com/bootstrap-vue/bootstrap-vue/issues/271
> Refactoring, fix element rendering as invisible when hidden

- lib/components/link.vue
> b-link: Fix typo

- lib/mixins/dropdown.js
My mistake,  Fixing how event listeners are attached/detached from `document.body.children`
> Iterate over body.children for event listeners

- examples/form-select/demo.html
Corrected a wrong property name. (`calss` => `class`)
> Fix a typo

- lib/components/form-input-static.vue
- lib/components/form-input.vue
- lib/components/index.js
- lib/mixins/generate-id.js
Added a standalone `<b-form-input-static>` component, and refactored `<b-form-input>` to use the new component when `static` prop is `true`
> new b-form-input-static component

- docs/SETUP.md
Added notes for migrating a project from bootstrap 4 to bootstrap-vue
> Setup.md: Add bootstrap -> bootstrap-vue migration notes

- docs/SETUP.md
- lib/components/form-fieldset.vue
Support for text alignment classes on the form input label per issue #307.
Didn't see a test runner in the package.json besides linting, so I assume circle-ci will test this upon submission.
> Enhancement for issue #307

- examples/modals/demo.js
- examples/tables/demo.html
Removed the unnecessary `this` keyword
> Unnecessary This

- lib/components/collapse.vue
- lib/components/dropdown.vue
- lib/components/nav-item-dropdown.vue
- lib/components/nav-toggle.vue
- lib/components/nav.vue
also removed dependency on generate-id
> Additional ARIA on navs and dropdown

- lib/components/carousel.vue
> [carousel] Fixed this arg in forEach

- lib/components/collapse.vue
- lib/mixins/dropdown.js
Plus removed a duplicate method from dropdown.js
> [collapse] render ID on root div

- examples/navbar/demo.html
Dropdown should use `right` instead of `right-alignment`
> Bring navbar example up to date

- lib/components/modal.vue
- okDisable property for disabling "OK" button in modal component
> Modal - add okDisable property

- lib/components-extra/index.js
- lib/directives-extra/index.js
- lib/extra.js
I've clonned repository, tried to build project with extra-components and realized that extra-components does not work.
Fixed this.
> components-extra does not work

- lib/components/alert.vue
to make it more understandable
> fixed warning message

- lib/components/list-group-item.vue
https://github.com/bootstrap-vue/bootstrap-vue/issues/516
> <b-list-group-item> "to" prop should accept [String, Object]

- lib/components/form-radio.vue
> Fixes issue #496. Emit change event for form-radio

- docs/components/modal/README.md
- docs/components/modal/meta.json
- lib/components/modal.vue
Add fix/feature for issue #521, and expands documentation a bit.
> [modal] Tweaks and enhanced documentation

- docs/components/button-group/README.md
Extended documentation for `b-button-group`
> [button-group] Documentation update

- docs/components/badge/README.md
Extended documentation for `b-badge`
> [badge] Documentation update

- docs/components/alert/README.md
Extended documentation for `b-alert`
> [alert] Documentation update

- lib/components/form-radio.vue
Apply contextual state to form-radio
Fix for #545 (form-radio only)
> [form-radio] contextual state fix

- docs/components/button/README.md
- docs/components/form-checkbox/README.md
- docs/components/form-fieldset/README.md
- docs/components/form-file/README.md
- docs/components/form-input/README.md
- docs/components/form-radio/README.md
- docs/components/form-select/README.md
- docs/components/form/README.md
- docs/components/form/index.js
- docs/components/form/meta.json
- docs/components/index.js
Updates to the form controls documentation.
Feel free to add additional changes to this branch
> [docs] form control & button documentation update

- CONTRIBUTING.md
> Fixed small typo

- lib/components/pagination.vue
Was getting reference errors with nuxt during SSR while rendering the page, this commit solves those reference rerrors
> [pagination] fixed referenceerror: i is not defined

- docs/components/nav/README.md
- docs/components/nav/meta.json
Additional documentation for `nav`
> [nav] Extended documentation

- lib/components/modal.vue
> [modal] fix - update focusFirst timing

- docs/components/breadcrumb/README.md
- docs/components/button/README.md
- docs/components/carousel/README.md
- docs/components/collapse/meta.json
- docs/components/form-checkbox/README.md
- docs/components/form-file/README.md
- docs/components/form-radio/README.md
- docs/components/form-select/README.md
- docs/components/input-group/README.md
- docs/components/table/README.md
- docs/components/tabs/README.md
This PR is created to make adjustments to documentation.
Feel free to add/push to this `docs-fixes` branch.
> [docs] Documentation updates

- docs/nuxt/components/componentdoc.vue
Add boilerplate about native events to all component pages.
> [docs] componentdoc.vue native boilerplate

- lib/components/form-checkbox.vue
- lib/components/form-file.vue
- lib/components/form-input-static.vue
- lib/components/form-input.vue
- lib/components/form-radio.vue
- lib/components/form-select.vue
- lib/mixins/form-custom.js
- lib/mixins/form.js
Optimize the props on all form input controls, removing unused props off of some controls.
This addresses #542 and should also optimize the docs
> feat(form controls): Optimize props

- docs/components/alert/README.md
- docs/components/button/README.md
- docs/components/carousel/README.md
- docs/components/collapse/README.md
- docs/components/form-fieldset/README.md
- docs/components/form-file/README.md
- docs/components/form-input/README.md
- docs/components/modal/README.md
- docs/components/pagination/README.md
- docs/components/table/README.md
- lib/components/modal.vue
> docs: Documentation updates

- docs/components/form-select/README.md
- lib/components/form-select.vue
Adds new prop `invalid` to `b-form-select`
> feat(form-select): Add aria-invalid support

- lib/components/form-checkbox.vue
- lib/components/form-file.vue
- lib/components/form-input-static.vue
- lib/components/form-input.vue
- lib/components/form-radio.vue
- lib/components/form-select.vue
- lib/mixins/form.js
Adds `required` prop to form controls, and applies `aria-required` where applicable
> feat(form controls): Add required attribute and related ARIA support

- examples/table/demo.html
Change deprecated fieldset prop from `label-size` to `label-cols`
To prevent erroneous console warnings during test
> fix(table demo.html): remove deprecated fieldset prop

- CONTRIBUTING.md
> docs(contributing): Typos and updates

- docs/README.md
added section on ie11 support and how to make bootstrap-vue work with this browser.
> Update README.md with notes on IE11 support

- lib/components/form-radio.vue
If ID supplied on component, generate IDs for each radio input
> feat(form-radio): ARIA - Add IDs to individual radios

- docs/components/form-fieldset/README.md
- lib/components/form-fieldset.vue
User supplied `for` target was not being applied to the label properly.  This PR fixes that.
Also deprecate prop `for` in favour of `label-for`
Documentation updated to reflect changes
> fix(form fieldset): 'label for' prop not being applied to label - ARIA

- __tests__/components/table.spec.js
- docs/components/form-checkbox/README.md
- docs/components/form-fieldset/README.md
- docs/components/form-file/README.md
- docs/components/form-input/README.md
- docs/components/form-radio/README.md
- docs/nuxt/components/componentdoc.vue
- lib/components/form-fieldset.vue
- lib/components/form-radio.vue
- lib/components/table.vue
- lib/mixins/dropdown.js
- nuxt.config.js
Includes update documentation text.
> docs: Update live examples for ARIA compliance.

- docs/components/button/README.md
Hello, This is my first contribution to the open source community and PR, just a simple correction in the component button readme file, i hope it helps.
> fix(docs): typo in button docs

- README.md
Resolve #145 
"Can you clearly explain clearly in the way to integrate both of them, and the ways of using bootstrap for the beginner?"
Instructions updated and written to be more detailed for users of various Vue project structures (or vue-cli templates).
**Screenshot Preview:**
> docs(readme): Update README.md with more detailed install instructions

- README.md
> fix(docs): update README.md for Bootstrap version

- docs/components/pagination/README.md
- lib/components/pagination.vue
Some links were missing `href="#"`
Added `aria-controls` prop to allow reference to component that is being controlled
> fix(pagination): Added missing href & ARIA adjustments

- lib/components/card.vue
- lib/components/carousel-slide.vue
- lib/components/jumbotron.vue
- lib/components/modal.vue
- lib/components/popover.vue
Addresses issue #668 
Adds props for setting header tag types and more
> feat(card,carousel-slide,jumbotron,modal,popover):: Add props for setting tag types

- docs/SETUP.md
Adds details for repo's main README.md file, which is not included in the docs website.
Feel free to tweak the docs.
> docs(setup): Incorporate docs from repo README.md

- lib/components/collapse.vue
Addresses issue #712 
Applicable only when in a nav/navbar (`is-nav` is true), and the navbar is in toggle mode)
When the toggled navbar is open, clicking on any nav-item or dropdown-item (but not a dropdown toggle button)  will close the collapse items.
> feat(collapse): Close collapse when clicked in nav/navbar (issue #712)

- README.md
Adds a badge that shows the status of our dependencies. Helps us stay honest and up to date with our small number of dependencies. _(far right badge)_
> feat(readme): add david dep badge

- __tests__/components/alert.spec.js
- __tests__/helpers.js
- examples/alert/demo.html
- examples/alert/demo.js
- lib/components/alert.vue
Reverts bootstrap-vue/bootstrap-vue#721
Reverting temporarily for additional testing of certain scenarios.
> Revert "fix(alert): use v-model to update show value"

- lib/components/pagination.vue
Improved ARIA roles and aria-* attributes for better W3C ARIA validation.
Pagination now 100% passes W3C WAI ARIA validation
> fix(pagination): Improved ARIA roles and attributes

- lib/components/carousel.vue
Add v-model support to allow external control of slides.
Addresses issue #743
> feat(carousel): Add v-model support (issue #743)

- docs/components/navbar/README.md
Expanded documentation for `<b-navbar>` to include descriptions and examples for sub-components
> docs(navbar): Enhanced navbar documentation

- docs/components/card/README.md
- docs/components/card/meta.json
- lib/components/card.vue
Extended documentation for cards.
~Need to add section on `b-card-group` and document slots~
> docs(card): Extended card documentation

- lib/components/form-radio.vue
Change to merge into dev branch
> fix(form-radio): Add missing classes in button mode

- lib/components/tabs.vue
> fix(tabs): tabs not clickable (issue #789)

- docs/components/button/README.md
Remove use of reserved word `var`
Addresses issue #802
> fix(docs): button update example (issue #802)

- lib/components/navbar-brand.vue
Removed erroneous `this` in template
> fix(navbar-brand): Removed erroneous this in template

- lib/components/form-checkbox.vue
Better focus/blur handling in button mode
> fix(form-checkbox): Better focus handling in button mode

- docs/components/navbar/README.md
Fix unclosed em tag in navbar example
> Fix unclosed em tag

- lib/components/form-input.vue
> fix (form input) input reactivity

- docs/components/card/README.md
- docs/components/card/meta.json
- docs/components/tabs/README.md
- lib/components/card.vue
Change prop `no-block` to `no-body` to better reflect V4.beta classes
Update documentation
> fix(card):  change prop no-block to no-body

- docs/components/card/README.md
> fix(card): docs

- docs/components/progress/README.md
- lib/components/progress.vue
Add support for setting the height of the progress bar
Also includes expanded documentation
> feat(progress): Add height prop

- docs/components/form/meta.json
- lib/components/form-row.js
- lib/components/index.js
- tests/components/form-row.spec.js
- tests/fixtures/form-row/demo.html
- tests/fixtures/form-row/demo.js
Similar to native `.row` class, but created a row using `.form-row` class which has tighter margins.
Created as a functional component, and allows for a custom tag (defaults to `div`)
Includes tests
> feat(form-row): New functional component

- lib/components/table.vue
Addresses issue #859 in v0.x branch
> fix(table): filtered event not firing when filter cleared (issue #859)

- lib/components/form-input.vue
- yarn.lock
Just removes the type check.
Issue #858
> fix(858): remove type validation on form-input

- docs/components/carousel/README.md
- lib/components/carousel-slide.vue
Adds a slot img to carousel-slide
> feat(carousel): Add img slot to carousel-slide

- docs/components/carousel/README.md
- lib/components/carousel-slide.vue
Adds a slot for custom control of image
> feat(carousel) Add img slot to d-carousel-slide

- docs/components/form-input/README.md
- docs/components/form-input/meta.json
- docs/components/form-textarea/README.md
- docs/components/form-textarea/meta.json
- lib/components/form-input.vue
- lib/components/form-textarea.vue
- lib/mixins/id.js
- lib/mixins/index.js
Prevent prop mutation errors on form-text area.  Minor improvements to form-input
Documentation updates
> fix(forms): Adjustments to form-textarea and form-input

- lib/components/dropdown.vue
- lib/components/nav-item-dropdown.vue
Adds client side only auto ID generation
> feat(dropdown): Add auto ID generation

- lib/components/form-checkbox.vue
- lib/components/form-file.vue
- lib/components/form-group.vue
- lib/components/form-input.vue
- lib/components/form-radio.vue
- lib/components/form-select.vue
- lib/components/form-textarea.vue
- lib/mixins/form-size.js
- lib/mixins/form-state.js
- lib/mixins/index.js
Created mixins for Size and State
> chore(forms): Size and State mixins

- lib/components/tab.vue
Make it transition again
Attempt to fix #504
> fix(tab): transitions

- docs/components/form-checkbox/README.md
> Fix typo in Form Checkbox page

- lib/classes/tooltip.js
> fix(tooltip+popover): Hide tooltip/popover when $route changes

- docs/components/jumbotron/meta.json
- lib/components/nav-item-dropdown.vue
- lib/mixins/dropdown.js
Work in progress
possible fix for issue #952
> fix(nav-dropdown): Fix right alignment in <b-nav>

- docs/components/embed/README.md
- docs/components/embed/index.js
- docs/components/embed/meta.json
- docs/components/index.js
- lib/components/embed.js
- lib/components/index.js
- tests/components/embed.spec.js
- tests/fixtures/embed/demo.html
- tests/fixtures/embed/demo.js
- yarn.lock
Based on https://getbootstrap.com/docs/4.0/utilities/embed/
> feat(embed): New component b-embed for responsive video embeds

- lib/classes/popover.js
- lib/classes/tooltip.js
> fix(popover+tooltip): Allow indiviual component imports

- lib/components/alert.vue
> fix(b-alert): add dismissible check for dismiss btn

- lib/mixins/dropdown.js
> feat(dropdowns): Add hide() and show() methods

- lib/classes/tooltip.js
- lib/directives/scrollspy.js
- lib/mixins/dropdown.js
- lib/utils/dom.js
- lib/utils/index.js
Centralizing several utility methods for DOM querying and tests
Includes the `Element.closest` polyfill
Should help reduce gzipped lib size
> feat: dom utility methods

- lib/utils/observe-dom.js
Reverts bootstrap-vue/bootstrap-vue#1025
> Revert "fix(observedom): Callback not being called for changes other than childList changes"

- lib/components/col.js
- tests/components/col.spec.js
- tests/fixtures/col/demo.html
- tests/fixtures/col/demo.js
> fix(b-col): handle bool style prop for sm,md,lg,xl

- lib/components/modal.vue
- lib/utils/observe-dom.js
New `lazy` prop allows modal to be taken out of dom (`v-if`) when not visible
> feat(modal): Add lazy loaded modal support

- lib/components/modal.vue
Incorporates fixes from https://github.com/twbs/bootstrap/issues/23672
Also use newer DOM utils for better minification
> fix(modal): Modal jumps position when the viewport is resized

- docs/directives/scrollspy/README.md
- lib/classes/index.js
- lib/classes/scrollspy.js
- lib/directives/scrollspy.js
- lib/utils/dom.js
Various bug fixes for v-b-scrollspy directive.
Migrates core of scrollspy into a class module.
Update example docs.
> fix(scrollspy): fixes ffor various bugs

- docs/nuxt/components/toc.vue
- docs/nuxt/pages/docs/components/_component.vue
- docs/nuxt/pages/docs/directives/_directive.vue
- docs/nuxt/pages/docs/index.vue
- docs/nuxt/pages/docs/layout/index.vue
- docs/nuxt/pages/docs/misc/changelog.vue
- docs/nuxt/pages/docs/misc/contributing.vue
- docs/nuxt/pages/docs/reference/_reference.vue
Pre-generates the TOC lookup table.
Removes need to page components to signal to update TOC.
TOC automatically updated on $route change
> perf(docs): Better TOC SSR generation

- lib/components/form-checkbox-group.vue
- lib/components/form-radio-group.vue
> fix(form-radio-group): Allow number type for checked

- lib/mixins/form-options.js
Handle case where object format is missing value and/or text keys.
Addresses issue  #1098
> fix(form-options): Handle object special cases

- docs/nuxt/components/search.vue
Searches for each word entered and only returns results where each word is present.
Also fixes matching sub arrays in TOC content (h3 headers)
> feat(docs): Search by keywords

- docs/README.md
adds info on vue-cli
adds info on cherry picking components & compiling from source
> chore(docs): improve getting started info

- docs/components/button-toolbar/README.md
- docs/components/popover/README.md
- docs/components/tooltip/README.md
"123" and "456" are nice but noone would ever use them in reallife.
> feat(docs): Use more realistic numbers

- docs/components/modal/README.md
- lib/components/modal.vue
Add disable Cancel button prop and busy prop to disable both buttons at once
> feat(modal) disable cancel button ability

- package.json
Issue #1121 should be addressed. I'd like to import components individually because I'd like to reduce my package's size with dynamic importing. So, I created this pull request.
> Fix dependencies to import components individually

- docs/README.md
Add link to official `Webpack` guide to configure css loading
issue #1209
> (fix) Webpack css import configuration

- docs/reference/variants/README.md
- Fix some typos in the variants docs
---
PS: Sorry for the small PR :)
> docs: typo fixes

- lib/components/input-group.vue
> input-group.vue, property "defualt" ==> "default" (trivial error :))

- src/components/form-file/form-file.vue
> fix(form-file) missing formSizeMixin

- docs/pages/docs/layout.vue
> docs: Add redirect from old layout section

- src/components/button-toolbar/button-toolbar.js
- src/components/carousel/carousel.js
- src/components/modal/modal.vue
- src/components/tabs/tabs.js
- src/mixins/dropdown.js
- src/utils/index.js
- src/utils/key-codes.js
Move repeated event KeyCode constants into utils file.
> perf: add event KeyCode constants in utils

- src/components/table/README.md
- src/components/table/table.vue
This is the last of the components to be converted to render functions.
> perf(table): convert template to render function

- src/components/alert/README.md
- src/components/breadcrumb/README.md
- src/components/button/README.md
- src/components/carousel/README.md
- src/components/collapse/README.md
- src/components/form-checkbox/README.md
- src/components/form-file/README.md
- src/components/form-group/README.md
- src/components/form-input/README.md
- src/components/form-radio/README.md
- src/components/form-select/README.md
- src/components/form-textarea/README.md
- src/components/form/README.md
- src/components/modal/README.md
- src/components/pagination-nav/README.md
- src/components/pagination/README.md
- src/components/popover/README.md
- src/components/progress/README.md
- src/components/table/README.md
- src/components/tabs/README.md
- src/directives/popover/README.md
- src/directives/scrollspy/README.md
- src/directives/tooltip/README.md
The idea was to make it possible to copy the examples in to a .vue file of the Nuxt starter template where they should compile without error.
> docs: updated code examples

- src/components/table/table.vue
Switch to 2 space tabs, no semi's
> chore: table code style update

- src/components/table/table.vue
> fix(table): initial busy of true always made table busy

- src/components/carousel/carousel.js
Add extra validation for slides Uncaught TypeError: Cannot set property 'tabIndex' of undefined in pause() function
> fix(carousel): uncaught typeerror on empty slides.

- src/components/form-group/README.md
- src/components/form-group/_form-group.js
Allow optionally control of the label's size to match the form input(s) size
> feat(form-group): new label-size prop

- src/components/form-group/README.md
- src/components/form-group/_form-group.js
Reverts bootstrap-vue/bootstrap-vue#1415
Switching to dev branch
> chore: revert "feat(form-group): new label-size prop"

- src/directives/popover/README.md
Fixed intended behavior for combined triggers (Hover + Focus)
> docs(popover): update triggers example

- src/components/form-group/fixtures/form-group.html
Ensure fixtures use most prop options
> chore: update test fixture for form-group

- src/components/button/button-close.spec.js
- src/components/button/fixtures/button-close.html
- src/components/button/fixtures/button-close.js
Sanity checks for the alert component test failures regarding button-close.
> chore(button-close): add testing for button-close click handlers

- src/utils/observe-dom.js
- src/utils/popover.class.js
- src/utils/tooltip.class.js
Excluding some things that are difficult to test in a JSDOM environment
> chore: coverage

- src/components/image/img-lazy.js
> chore(img-laxy): fix required typo

- src/components/form-checkbox/form-checkbox.js
(this commit does not change the html structure however)
> update checkbox changes from bootstrap beta 3

- src/components/button/README.md
> docs(button): fix typos

- src/components/button-group/README.md
- Fix link typo in **Button group**'s See also section
💃
> fix: Fix typo in See also section

- src/components/form-checkbox/form-checkbox.js
- src/components/form-radio/form-radio.js
Add the missing attribute "for" to the checkbox.
Update the HTML markup and class of the radio form element to the new html structure of bootstrap beta-3.
#1408
> Feat/checkbox & radio

- scripts/build
Grammar police reporting in. Changing hte to the.
> Spelling correction in comment

- docs/utils/index.js
fix possible `Cannot read property 'replace' of undefined` error
> fix(utils) possible runtime error

- src/components/table/README.md
- src/components/table/fixtures/table.html
- src/components/table/table.js
- src/components/table/table.spec.js
> Fix table html injection

- src/components/table/README.md
- src/components/table/table.js
> fix(Table) allow empty labels

- src/components/tabs/README.md
- src/components/tabs/tabs.js
As requested at #1583 
fixes #1583
> Feat(Tab) add title slot

- docs/pages/index.vue
> docs: fix capitalization of GitHub

- src/components/table/README.md
> fix(Table docs) use correct input-group markup

- .editorconfig
- src/components/carousel/carousel.js
- src/components/carousel/carousel.spec.js
- src/components/carousel/fixtures/carousel.html
- src/components/carousel/fixtures/carousel.js
> fix(Carousel) transition direction

- src/components/modal/modal.js
> fix(modal): Correct the internal btn variable names

- src/components/dropdown/dropdown.js
- src/components/nav/nav-item-dropdown.js
> Added `menuClass` prop to `bDropdown`

- package.json
- src/index.d.ts
Hi, i have added a basic Typescript declaration just for a ready-to-go plugin import into a Vue/TS project.
It should be completed with the components props for a better handling.
Nicola
> Added Typescript declaration

- src/components/tabs/README.md
- src/components/tabs/tabs.js
> fix(tabs): typo in tabs (#1735)

- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown.spec.js
> fix(dropdown): aria-labelledby for dropdowns

- docs/plugins/docs-mixin.js
> fix(docs): typo in docs plugin

- src/components/form-input/form-input.js
Reverts #1734
Related to #1751 and #1765
> fix(form-input): revert step, min and max props

- src/components/table/README.md
- src/components/table/fixtures/table.js
- src/components/table/table.js
- src/components/table/table.spec.js
Based on custom classes per table cell https://github.com/bootstrap-vue/bootstrap-vue/commit/d05d6b6eb32a14ff4f652915968f2443da6c6b4a
Related issue #1758
> feat(table): support custom attributes per table cell in a column (#1758)

- docs/components/componentdoc.vue
Fixes 
e.g. http://localhost:3000/docs/components/table
> fix(docs): Fix duplicate keys in events table

- src/components/table/README.md
- src/components/table/fixtures/table.html
- src/components/table/table.js
- src/components/table/table.spec.js
> feat(table): Add no-sort-reset prop

- docs/components/componentdoc.vue
Sorry I forgot to remove a piece of code in #1786
> fix(docs): Remove incorrect code added during debugging

- src/components/card/README.md
- src/components/carousel/README.md
- src/components/carousel/fixtures/carousel.html
- src/components/image/README.md
- src/components/image/fixtures/image.html
- src/components/image/img.spec.js
- src/components/tabs/README.md
lorempixel.com is down, replace them with placeimg.com
> replace lorempixel.com with picsum.photos, resolves #1823

- src/components/breadcrumb/breadcrumb-link.js
> feat(breadcrumb-link): Actually support children

- src/components/table/README.md
- src/components/table/table.js
Closes #1783.
Improvements for docs are welcome
> feat(table): Add the sort-direction prop

- docs/markdown/reference/validation/README.md
Added example for vee-validate and fixed example for vuelidate state property
> Added vee-validate example

- docs/components/search.vue
> fix(docs): fixes broken styling of docs navigation

- src/components/dropdown/README.md
> fix(dropdown): typo in README

- src/components/modal/README.md
- src/components/modal/modal.js
> feat(table) Add content-class prop

- docs/markdown/reference/utility-classes/README.md
Sync with latest version of main bootstrap docs
> docs: update utilities links

- src/components/pagination/README.md
- src/components/pagination/fixtures/pagination.html
- src/mixins/pagination.js
> feat (pagination) added slots for first, prev, next, last, and ellipsis

- src/components/table/README.md
> Update on README.md

- src/components/form-file/form-file.js
Hello, in commercial project I am working for I faced issue with _form-file component_.
Extensions validation works only for _multiple_ files.
This PR fixes this issue.
Thanks.
> fix(form-file): add validation of single form file

- src/components/collapse/collapse.js
> fix(collapse/toggle): "collapsed" class cleared when component updated. fixes #1798

- src/components/form-file/form-file.js
> fix(form-file): issue with "accept" values (fixes #1526, reverts #2028)

- src/components/tooltip/index.js
- src/components/tooltip/package.json
This commit adds the missing tooltip directive to the plugin.
> fix(tooltip): Add directive to component plugin

- src/components/form-select/README.md
Replace this line with a detailed description of your pull rqeuest
> chore(docs): form-select typo fix

- src/components/button-group/README.md
The PR add a missing hyphen in a template tag.
> docs(button-group): typo fixes

- src/utils/loose-equal.js
The `looseEqual` util (used in b-form-select, form-radios and form-checkboxes, and possibly others) should compare `Date` objects by their values.
The `looseEqual` util function is based on the core VueJS `looseEqual` utility function.
From https://github.com/vuejs/vue/pull/7940
_PR titles should following the [**Conventional …
> fix(utils/loose-equal): check dates in looseEqual util

- src/components/input-group/input-group-addon.js
- src/components/input-group/input-group-append.js
- src/components/input-group/input-group-prepend.js
- src/components/input-group/input-group.js
- src/components/input-group/package.json
Some adjustments to the render functions of `b-input-group` and it's sub components.  Addresses possible `undefined` content issues.
Includes component reference for sub components, and removed unneeded props in the append/prepend sub-component.
Includes rendering Vue placeholder elements (``) for optional content areas, improving DOM patch performance.
_PR titles should following the [**Conventional …
> fix(input-group): Minor fixes and documentation update

- src/components/table/table.js
Convert null or undefined cell values to an empty string
Fixes #1502 
> fix(table): return empty string if cell value is null or undefined. Fixes #1502

- src/components/dropdown/README.md
- src/components/dropdown/dropdown.js
- src/mixins/dropdown.js
- src/utils/key-codes.js
Dropdowns missing keyCode definition for `TAB`. Also was no closing when focus (via TAB) moved out of the menu.
Closes #1577 
> fix(dropdown): add missing TAB keyCode. closes #1577

- src/utils/plugins.js
Replace this line with a detailed description of your pull rqeuest
> chore: fix comment typo in plugins.js

- src/components/dropdown/README.md
Updated README to include usage instructions of the text slot.
> docs(dropdown): added instructions for button-content slot

- src/components/popover/README.md
This pull request fixes typos in the popover documentation.
> docs(popover): fix documentation typos

- src/components/modal/modal.js
modal.style.paddingLeft and modal.style.paddingRight should be set to 0, if no scrollbar exist.
> fix(modal): clear modal paddingLeft and paddingRight if no Scrollbar(s) in adjustDialog().

- src/components/form-input/form-input.spec.js
- src/mixins/form-state.js
form control states were inadvertently being flagged as valid (`true`) when the state prop was set to an empty string.
fixes #2166
> fix(form-state): explicitly handle when state is set to empty string. fixes #2166

- src/components/form-file/README.md
- src/components/form-file/form-file.css
- src/components/form-file/form-file.js
Adds new prop to customize browse button text.
Includes temporary CSS until Bootstrap V4.2 is released
fixes #2143 
> fix(form-file): Add prop to allow customization of browse button text. fixes #2143

- src/components/form-file/README.md
- src/components/form-file/form-file.js
Adds missing handler registration, and adds optional drop placeholder.
> fix(form-file): fix drag and drop feature

- src/components/modal/README.md
Add ID to the modal from `Emitting Events on $root` example
Please replace this line with a detailed description of your pull rqeuest. If no descrpion your PR may be rejected.
> docs(modal): add ID to "Events on $root" example

- src/components/form-checkbox/form-checkbox-group.js
- src/components/form-checkbox/form-checkbox.js
- src/components/form-file/form-file.js
- src/components/form-input/form-input.js
- src/components/form-input/form-input.spec.js
- src/components/form-radio/form-radio-group.js
- src/components/form-radio/form-radio.js
- src/components/form-select/form-select.js
- src/components/form-textarea/form-textarea.js
- src/mixins/form-radio-check.js
- src/mixins/form.js
form controls that are wrapped in other elements internally were not transferring the form attribute to the input.
The form attribute allows a form control to specify which form it belongs to.
fixes #2154
> feat(forms): add form prop to all inputs. fixes #2154

- src/components/table/README.md
The Readme already says that "thClass" and "tdClass" don't work in scoped styles. I've found that even "class" doesn't work, but does work when I remove the scoping, and therefore suspect this is a general thing for people to look out for, when setting classes on fields of b-table.
Please replace this line with a detailed description of your pull rqeuest. If no descrpion your PR may be rejected.
> docs(table): Mention "class" also does not work when defined in scoped style

- docs/assets/css/styles.css
- docs/markdown/reference/validation/README.md
- docs/nuxt.config.js
- docs/plugins/play.js
- package.json
- src/components/form-file/README.md
- src/components/tabs/README.md
- yarn.lock
This PR addresses several console errors in the docs and improves the `play` directive.
The example name defined in markdown is now omitted for the live example on the docs page.
> fix(docs): Fix console errors and improve `play` directive

- docs/components/codemirror.vue
- docs/pages/play.vue
Fix playground hang issues when invalid template or us is entered.  only update stored copy of playground javascript and template if compilation successful.
Playground edits will be reset to default if last visit to playground was more than 7 days from last edit.
Now supports using render functions as alternative to template html.
Fixes #1843 
> fix(docs): fix playground issues. fixes #1843

- docs/pages/play.vue
Minor tweaks to the new playground code and layout.
> docs(playground): minor adjustments to playground layout

- docs/pages/play.vue
Some improvements to playground console overrides.
Creates a "fake" console object and passes it to the  scope of the generated app via a closure.
Includes methods `console.info`, `console.log`, `console.warn`, `console.error`, and `console.clear` . Other console methods and properties are not available.
> docs(playground): improve console overrides

- docs/pages/play.vue
Fixes the export to fiddle button when JS and HTML are valid-ish
> fix(docs): fix issue with playground export button

- docs/markdown/reference/theming/README.md
- docs/markdown/reference/theming/meta.json
- docs/markdown/reference/utility-classes/meta.json
- docs/markdown/reference/validation/README.md
Add reference section on theming Bootstrap.
> Create theming reference section

- src/components/alert/alert.css
Targets the alert custom fade transition CSS to just the alert component, so that the CSS doesn't override/conflict any user's custom fade CSS definitions
> fix(alert): target custom transition CSS to just the alert component

- src/components/form-select/form-select.js
This PR is to ensure that current value of v-model is present on change event. Please see details of the issue for more detailed description (https://github.com/bootstrap-vue/bootstrap-vue/issues/1772).
Fixes #1772
> fix(select): Current v-model value on change event (fixes #1772)

- src/components/modal/modal.js
Disables enforce focus while another modal is opened on top.
Fixes #2175
> fix(modal): Handle enforce focus when modals are stacked (Fixes #2175)

- src/components/dropdown/README.md
- src/components/dropdown/dropdown-item-button.js
Add support for `active` state to `<dropdown-item-button>`.
> fix(dropdown-item-button): Add support for `active` state

- src/components/carousel/carousel.js
- src/components/collapse/collapse.js
- src/components/modal/modal.js
- src/utils/dom.js
- src/utils/observe-dom.js
- src/utils/target.js
Use utils/dom.js for better minification
> chore: use dom utils

- src/components/table/README.md
- src/components/table/table.js
Automatically checks if click/keypress was on a non-disabled link/button/form-control before emitting a `head-clicked` or `row-clicked` event.
Removes need for user to add `.stop` modifier to event handler.
> feat(table): Remove need to add `.stop` modifier on slot inputs/links/buttons

- src/components/modal/modal.js
- src/utils/dom.js
Listener placed on document (focusin) rather than the modal container (focusout). This more closely follows Bootstrap V4.1's enforce focus handler.
May address firefox issue (#1908) with `input type="password"` inside modals not being able to be focused.
> fix(modal): better enforce focus handler. 

- src/components/table/_variables.scss
- src/components/table/table.css
- src/components/table/table.js
- src/components/table/table.scss
- src/components/table/table.spec.js
Add SCSS file (for reference initially) and static CSS file compiled from SCSS
Includes slightly better sort indicator styling (using `aria-sort` attributes to trigger styles)
To be used later when we integrate SCSS into Bootstrap-Vue
> feat(table): initial SCSS file

- src/components/alert/_variables.scss
- src/components/alert/alert.scss
- src/components/dropdown/_variables.scss
- src/components/dropdown/dropdown.scss
- src/components/form-file/_variables.scss
- src/components/form-file/form-file.scss
- src/components/input-group/_variables.scss
- src/components/input-group/input-group.scss
creating custom component SCSS based on custom CSS files
> feat(css): create SCSS versions of CSS

- src/components/modal/README.md
Minor update to modal doc, re stacking modals.  Modals must be defined in the document in the order they will be opened.
> docs(modal): minor update on multiple modal support

- src/components/button/README.md
- src/components/carousel/README.md
- src/components/form/README.md
- src/components/layout/README.md
I noticed a dead link while reading documentation. This pull request includes a fix for that link, and four other dead links I found.
```
$ find . -name "README.md" | grep -v node_modules | xargs egrep -o --line-number "\[.+\]\(/.+\)" | python3 check_links.py
Dead link: ./src/components/form/README.md line 102 http://localhost:3000/docs/reference/spacing
Dead link: ./src/components/layout/README.md line 378 http://localhost:3000/docs/reference/spacing
Dead link: ./src/components/carousel/README.md line 98 http://localhost:3000/docs/components/img
Dead link: ./src/components/button/README.md line 149 http://localhost:3000/docs/components/form-radios
Dead link: ./src/components/button/README.md line 150 http://localhost:3000/docs/components/form-checkboxes
$ cat check_links.py
import sys …
```
> docs: fix dead links

- src/components/form-input/README.md
Please replace this line with a detailed description of your pull rqeuest. If no descrpion your PR may be rejected.
> chore(docs): form-input - use trim prop in example

- src/mixins/toolpop.js
Use `HTMLElement` SSR polyfill for type-check on `boundary` prop
Fixes #2229
> fix(toolpop mixin): allow boundary type to be HTMLElement (Fixes #2229)

- package.json
- scripts/build
`uglify-es` is no longer maintained. `terser` is maintained and is a drop-in replacement that has several bugs fixed
Also, `uglify-es` uses the same command name (`uglifyjs`) as `uglify-js`  which was causing the build scripts to use the wrong `uglifyjs` command (the `uglify-js` version) in some instances.
This PR also adjusts the minified JS files to end with `.<buildvariant>.min.js` rather than `.min.<buildvariant>.js` to maintain backwards compatibility with previous releases.
**If adding a new feature, or changing the functionality of an existing feature, the …
> feat(build): replace uglify-es with terser

- docs/markdown/intro/README.md
Show explicitly what is camelCasing and PascalCasing, so lets change:
`camel-casing` ->  `camelCasing`;
`pascal-casing` -> `PascalCasing`.
> docs(Getting Started): camelCasing, PascalCasing

- src/components/form-radio/README.md
Fixed really small typo on Form Radio docs
> Tiny typo on form radios docs

- src/components/navbar/README.md
Switched placement of _b-navbar-brand_ and _b-navbar-toggle_ in code sample to display navbar toggle button on the right side and navbar brand on the left side on mobile devices as is the default format implemented in Bootstrap
In the navbar component documentation, moved the b-navbar-toggle element to be AFTER the b-navbar-brand so the toggle button displays at the right side of the navbar on mobile devices to keep it in line with the default behavior of Bootstrap's same component. Previously navbar toggle button was being displayed at the left side of the navbar and the brand at the right side.
**The PR fulfills these …
> docs(navbar): changed toggle button placement

- docs/assets/css/styles.css
- docs/nuxt.config.js
- docs/plugins/bootstrap-vue.js
- docs/plugins/codemirror.js
Ensure that CSS/SCSS is imported in the right sequence for style overrides.
On occasion, the left navbar would experience strange layout issues due to the order that Nuxt dynamically loads the CSS/SCSS files. This PR _hopefully_ fixes that by importing all the non-scoped CSS in one location.
> fix(docs): improve CSS load ordering

- CHANGELOG.md
Needed for proper TOC generation and semantic markup
Conventional commits changelog generation has issues with correct markup :(
> chore: Fix changelog heading markup

- src/components/form-select/form-select.js
Exposes `focus()` and `blur()` methods on `b-form-select` instance.
Closes #2237
> feat(form-select): Expose focus and blur methods (Closes #2237)

- src/components/modal/README.md
- src/components/modal/modal.js
This PR allows to disable the modal stacking feature by setting `stackable` to `false`.
> feat(modal): Make stackable optional

- src/components/form-select/form-select.js
Removes temporary classes needed to address issues with form selects from bootstrap V4.0.x
Closes #1896 
> fix(form-control): remove interim class fixes from bootstrap 4.0 (fixes #1896)

- package.json
Flag  utils/array and utils/object as having sideEffects in package.json
To allow webpack4 to do better tree shaking.
> fix(package.json): flag most of bootstrap-vue as being side effect free

- src/components/modal/modal.js
Fix for the following edge case:
- `modal-open` class of body element remains despite the modal has closed when the modal's `show()` and `hide()` are called repeatedly and asynchronously.
- `data-modal-open-count` attribute value does not return to 0 also.
Fixes #2236
> fix(modal): handle edge cases where modal is shown/hidden in rapid succession (fixes #2236)

- src/components/table/table.js
Ignore some untestable code sections 
> chore(table): improve code coverage

- src/components/modal/modal.js
#2270 broke showing/hiding of once prevented modals.
This PR fixes this.
> fix(modal): Show/Hide when once prevented

- docs/assets/css/_bootstrap-vue.scss
- docs/assets/css/main.scss
- docs/assets/css/styles.css
- docs/nuxt.config.js
- docs/plugins/bootstrap-vue.js
- package.json
Nuxt.js loads static css/scss asset files async and doesn't guarantee load order.
Created a `main.scss` file for the docs, which imports all required css/scss in the desired order.
> fix(docs): guarantee css load order

- docs/nuxt.config.js
Needed due to updated Markdown Loader
> chore(docs): Pass options to markdown loader for heading IDs

- docs/markdown/reference/validation/README.md
Change spelling of "feilds" to "fields"
Please replace this line with a detailed description of your pull rqeuest. If no descrpion your PR may be rejected.
> chore(docs): fix typos in validation plugins reference section

- docs/assets/css/_bootstrap-vue.scss
- docs/assets/css/main.scss
- docs/nuxt.config.js
Now that the latest Nuxt.JS preserves CSS import order, we can move CSS back to nuxt.config.js
> chore(docs): Move CSS imports back to nuxt.config.js

- src/components/form-file/form-file.js
This PR fixes a `input` event loop when the `reset()` method is called or the `value` is set to the default value.
> fix(form-file): `input` event loop on `reset()` in multiple mode

- .eslintrc.js
- babel.config.js
This PR fixes `eslint` linting by disabling some `eslint-config-vue` default rules.
> chore(core): Fix `eslint` linting

- docs/assets/css/styles.css
- src/components/card/README.md
- src/components/card/_card-img.scss
- src/components/card/index.scss
- src/components/index.scss
Includes the border-radius CSS required for card-img-left and card-img-right, using Boostrap-V4 SCSS variables.
> feat(card): include custom styles for card-img-left and card-img-right

- src/components/table/README.md
Some minor changes to the documentation to explain that you can't sort on a field that is a property of a column, and a couple of minor typo corrections.
- [n/a ] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
> chore(docs): minor rewording regarding sorting on properties of columns, and typo fixes

- docs/pages/play.vue
- docs/plugins/play.js
- docs/utils/needs-transpiler.js
A followup to PR #2286 
Only includes babel-standalone for browsers that need to transpile the playground and live examples.
Tests for few basic ES6 syntaxes, and if any fail, then flags that the examples/playground code should be transpiled before instantiating the VMs.
Babel-standalone is still loaded lazily on pages that need it.
Notes:
- Side effect: Browsers running the transpiler will have more informative playground errors in the console logger.
- Playground will show a loading message when the compiler is first pulled down (for browsers that need it).
- Docs will not show a loading message when v-play is downloading the compiler (for browsers that need it).
**Does this PR introduce a breaking change?** (check …
> feat(docs): conditionally load babel-standalone only on browsers that need transpilation

- src/components/button/README.md
> docs(button): updated docs

- src/components/table/README.md
- src/components/table/table.js
Adds the `borderless` boolean prop to add class `.table-borderless` (from Boostrap V4.1.3) to the table.
> feat(table): add borderless prop

- src/components/pagination-nav/README.md
- src/components/pagination-nav/fixtures/pagination-nav.html
- src/components/pagination-nav/fixtures/pagination-nav.js
- src/components/pagination-nav/pagination-nav.js
- src/components/pagination/README.md
- src/components/pagination/fixtures/pagination.html
- src/components/pagination/fixtures/pagination.js
- src/components/pagination/pagination.js
- src/mixins/pagination.js
- Removes side effects from computed prop
- Optimizes duplicated code into helper methods/functions
- Blur `pagination-nav` when clicked, emulating normal link navigation behavior (Closes: #1891)
- Space keypress now triggers navigation in `b-pagination-nav` (Addresses https://github.com/bootstrap-vue/bootstrap-vue/issues/1891#issuecomment-397432096)
- Ensures current page link receives active class when v-model changes (Fixes: #1985, Fixes: #1629)
**If adding a new feature, or changing the functionality of an existing feature, …
> fix(pagination pagination-nav): v-model active class fix + keypress click fix (Fixes #1985, #1629)

- src/components/dropdown/README.md
- src/components/dropdown/dropdown.js
- src/components/dropdown/fixtures/dropdown.html
Add support for `href` and/or `to`, as well as `variant` on the split button.
New props:
- `split-href`
- `split-to`
- `split-variant` (defaults to same value as `variant`)
Only applicable when dropdown is in `split` mode.
Closes #1960
> feat(dropdown): support 'href', 'to' and 'variant' in split button mode (Closes #1960)

- src/components/table/fixtures/table.html
> chore: update usage of form-group deprecated horizontal prop

- package.json
- src/components/form-radio/README.md
- src/components/index.js
- src/components/index.scss
- src/components/spinner/README.md
- src/components/spinner/_spinner.scss
- src/components/spinner/index.js
- src/components/spinner/index.scss
- src/components/spinner/package.json
- src/components/spinner/spinner.js
- src/components/spinner/spinner.spec.js
- src/components/table/fixtures/table.html
- yarn.lock
> chore: merge dev into PR #2305

- src/components/navbar/README.md
> docs(navbar): minor doc updates

- docs/markdown/intro/README.md
Add some brief explanation of usage with Vue CLI 3
> chore: Document usage with Vue CLI 3

- src/components/table/README.md
- src/components/table/fixtures/table.html
- src/components/table/table.js
Fine tune selectable range mode to mimick the way file explorers work, thus making it more intuitive for final users.
> fix(table): selectable range mode update and minor fixes

- src/components/form-input/_form-input.scss
Removes temp css for disabled range inputs
> chore(form-input): remove interim fixes for disabled range inputs

- src/components/modal/README.md
Document new V4.2 moda size `xl`
> docs(modal): document v4.2 modal size xl

- docs/markdown/reference/router-links/README.md
> docs: correct spelling of router-links README

- src/components/card/README.md
Document responsive horizontal layout
Based on https://github.com/twbs/bootstrap/pull/27906
Closes #2364 
> docs(card): document responsive horizontal layout (closes #2364)

- docs/markdown/intro/README.md
- docs/markdown/reference/theming/README.md
- docs/markdown/reference/utility-classes/README.md
- src/components/form/README.md
Updates links to Bootstrap V4.2 Docs site
> fix(docs): Update links to Bootstrap V4.2

- src/components/card/README.md
- src/components/card/card-body.js
- src/components/card/card-sub-title.js
- src/components/card/card-text.js
- src/components/card/card-text.spec.js
- src/components/card/card-title.js
- src/components/card/index.js
- src/components/card/package.json
New card helper sub-components (functional):
> feat(card): new helper sub-components

- src/components/popover/fixtures/popover.html
- src/components/popover/fixtures/popover.js
- src/components/tooltip/fixtures/tooltip.html
- src/components/tooltip/fixtures/tooltip.js
- src/directives/popover/README.md
- src/mixins/toolpop.js
Add additional test scenarios for popover & tooltips
> chore: add additional test scenarios to popover and tooltip

- src/components/navbar/navbar-brand.spec.js
- src/components/navbar/navbar-nav.spec.js
- src/components/navbar/navbar-toggle.spec.js
- src/components/navbar/navbar.spec.js
Adding in tests for navbar and sub-components
> chore: add navbar tests

- src/components/carousel/carousel.js
- src/components/carousel/carousel.spec.js
- src/components/carousel/fixtures/carousel.html
Fixes a memory leak (infinite setIntervals) when no slides are given.
Adds additional test scenarios for carousel, plus ignore coverage for things we cant test in JSDOM
> fix(carousel): setInterval memory leak when no slides provided

- docs/components/nav.vue
- docs/components/sidebar.vue
- src/components/link/link.js
Removes the default values (setting to `undefined`) for props `active-class` and `exact-active-class`, so that the globally configured values can be used by default.
Affects `b-link`, `b-button`, `b-dropdown-item` and other components that build on `b-link` (i.e. have a `to` prop).
Fixes #2387, #1967
Components that accept a `to` prop will no longer default to using `active` as the class when the router-link is in the active state, but will instead use the globally configured values from vue-router (or nuxt) if the props `active-class` and `exact-active-class` are not set.
**While this change does not affect functionality of the component(s), it _may affect_ the …
> fix(router-link): remove default values for active-class and exact-active-class (Fixes #2387)

- src/components/carousel/carousel.spec.js
> chore: carousel test adjustment

- src/components/carousel/README.md
- src/components/carousel/carousel.js
Adds new prop `fade` which switches animation from slide to cross-fade.
Crossfade animation was introduced in Bootstrap V4.1.x
> feat(carousel): support crossfade animation

- src/components/carousel/carousel-slide.js
- src/components/carousel/carousel-slide.spec.js
- src/components/carousel/carousel.js
- src/components/carousel/carousel.spec.js
Use `provide` in `<b-carousel>` and inject in `<b-carousel-slide>` for property sniffing and reactivity.
Includes additional unit testing for carousel-slide sub component
> feat(carousel): use provide and inject for sub-component communication

- src/components/carousel/README.md
- src/components/carousel/carousel-slide.js
- src/components/carousel/carousel.js
- src/components/carousel/carousel.spec.js
- src/components/carousel/fixtures/carousel.html
- src/components/carousel/fixtures/carousel.js
- src/utils/env.js
Adds support for Bootstrap V4.1 touch/swipe on carousels
TODO:
> feat(carousel): add support for swipe on touch screens

- src/components/table/README.md
- src/components/table/table.js
Generates a unique key per rendered `table > body > tr` based on either a primary key column (field) or based on computed row index + serialized item data.
Adds a new prop `primary-key`, which identifies the column that contains a unique ID per row.  If not provided, b-table will generate a key based on the rendered row index concatenated with the rows data serialized.
This key is only used for rendering (`:key="..."`) the tbody rows, and allows for better row transitions (if used), and rendering.
Previously only the computed rowIndex was used, causing vnode re-use issues (such as https://github.com/bootstrap-vue/bootstrap-vue/issues/2410) when using subcomponents and directives in scoped field cells.
Fixes #2410 
**Does …
> fix(table): generate TR key using serialized item or primary key if provided (fixes: #2410)

- CHANGELOG.md
- docs/markdown/intro/README.md
- docs/markdown/misc/changelog/meta.json
- docs/markdown/reference/color-variants/README.md
- docs/markdown/reference/images/README.md
- docs/markdown/reference/router-links/README.md
- docs/markdown/reference/size-props/README.md
- docs/markdown/reference/spacing-classes/README.md
- docs/markdown/reference/starter-templates/README.md
- docs/markdown/reference/theming/README.md
- docs/markdown/reference/utility-classes/README.md
- docs/markdown/reference/validation/README.md
- docs/nuxt.config.js
- docs/pages/index.vue
- docs/pages/play.vue
This PR fixes some docs inconsistencies:
- `Webpack` -> `webpack`
- `Rollup` -> `rollup.js`
-  `Bootstrap-Vue`, `Bootstrap Vue` -> `BootstrapVue` 
- `vue-cli` -> `Vue CLI`
- `Change Log`, `ChangeLog` -> `Changelog`
- Code indentation and trailing semicolons
- Use `scss` code highlighting where needed
- Some other minor tweaks
> chore(docs): Remove inconsistencies

- src/components/carousel/carousel.js
- src/components/image/img-lazy.js
- src/directives/scrollspy/scrollspy.class.js
- src/directives/scrollspy/scrollspy.js
- src/utils/dom.js
- src/utils/env.js
Adds detection of event passive support to dom utils.  Normalizes 3rd argument to `addEventListener` and `removeEventListener`.
Passive mode allows the browser (that support passive mode) to optimize how it handles cancellable events that will never be cancelled (such as scroll/mouewheel/touch event handlers that will never call `event.preventDefault()`), improving scroll performance
Now used in `v-b-scrollspy`, `b-carousel`, and `b-img-lazy`
Related issue: #1858 (although it is codemirror that is generating those warnings)
Closes #1858 …
> perf(utils/dom): use passive event listeners where possible

- src/components/dropdown/README.md
- src/components/dropdown/_dropdown-form.scss
- src/components/dropdown/_dropdown-text.scss
- src/components/dropdown/dropdown-form.js
- src/components/dropdown/dropdown-form.spec.js
- src/components/dropdown/dropdown-text.js
- src/components/dropdown/dropdown-text.spec.js
- src/components/dropdown/index.js
- src/components/dropdown/index.scss
- src/components/dropdown/package.json
Adds support for form controls in dropdowns.
New helper components `b-dropdown-form` and `b-dropdown-text`
> feat(dropdown): support for form controls and free flow text

- docs/components/importdoc.vue
> chore(docs): Improve import docs

- .github/ISSUE_TEMPLATE.md
- CHANGELOG.md
- nuxt/index.js
- src/components/breadcrumb/breadcrumb.spec.js
- src/components/button/README.md
- src/components/form-checkbox/README.md
- src/components/form-group/README.md
- src/components/form-input/README.md
- src/components/image/README.md
- src/components/layout/README.md
- src/components/link/README.md
- src/components/modal/README.md
- src/components/popover/README.md
- src/components/spinner/README.md
- src/components/table/README.md
- src/components/tabs/README.md
- src/components/tooltip/README.md
- src/directives/popover/README.md
- src/directives/scrollspy/README.md
- src/directives/tooltip/README.md
- src/index.scss
- src/utils/warn.js
This PR corrects the spelling of "Bootstrap" and "BootstrapVue" everywhere in the repo.
> chore: Correct "Bootstrap" and "BootstrapVue" spelling everywhere

- src/components/tabs/tabs.js
Fixes an issue introduced by PR #2442 where the classes were not being applied to the correct items.
> fix(tabs): Fix tab titleLinkClass and titleItemClass handling

- docs/assets/css/styles.css
- src/components/table/README.md
- src/components/table/table.js
Renders the `<tbody>` element usingVue's  `<transition-group>` component (when transitions enabled). 
Users can pass an object of props via the `tbodyTransitionProps` prop, and can also pass an object of transition event handlers via the `tbodyTransitionHandlers` props. Users must also set which field contains a unique value per row, via `primary-key` so that transitions will happen correctly. The primary key field does not need to be present in the rendered table fields (it just needs to be present in the row data).
When neither prop is specified, no transitions will occur.
Closes: #1821 …
> feat(table): add support for transitions on tbody element (Closes #1821)

- package.json
Add vue-template-compiler and vue-server-renderer to devDependencies to prevent potential conflicts
> chore(deps): add vue-template-compiler and vue-server-renderer to devDependencies

- package.json
- renovate.json
- yarn.lock
This PR updates all dependencies except `prettier`.
`prettier` need to stay at *v1.24.3* to work properly with ESlint.
Closes #2443.
**If new …
> chore: Update dependencies and ignore `prettier` for now (Closes #2443)

- src/components/dropdown/dropdown-item-button.js
- src/components/dropdown/dropdown-item.js
This PR adds back the missing `click` event emits form `<b-dropdown-item>` and `<b-dropdown-item-button>`. …
> fix(dropdown): Add back missing `click` events

- src/components/modal/modal.js
Add `dialogClass` prop to `<b-modal>` to add custom classes to `modal-dialog` element.
Closes #2457.
event …
> feat(modal): Add `dialogClass` prop (Closes #2457)

- src/components/modal/README.md
Hi, there was a mistake in modal doc.
> fix(docs): fix modal docs typo

- package.json
- scripts/rollup.config.js
- src/components/table/table.js
- src/utils/get.js
- src/utils/startcase.js
- yarn.lock
This PR removes all `lodash.*` dependencies from `src/` files. Replacing by lightweight alternatives. They are inclined to convert to ESM and better maintenance. All copyright credits preserved.
This is a **HUGE** bundle size improvement and credit goes for @jackmu95 for discovery :heart: 
| File                            | Size (before) | Size (after) |
| ------------------------------- | ------------- | ------------ |
| bootstrap-vue.common.js         | 548K          | 512K         |
| bootstrap-vue.common.js.map     | 996K          | 940         |
| bootstrap-vue.common.min.js     | 235K          | 224K         |
| bootstrap-vue.common.min.js.map | 830K          | 780K         |
| bootstrap-vue.esm.js            | 421K          | 424K         |
| bootstrap-vue.esm.js.map        | 789K …
> perf(pkg): remove lodash dependency from src

- src/components/pagination-nav/package.json
- src/components/pagination/package.json
- src/mixins/pagination.js
Changes `Goto` to `Go to` in aria-labels for better screen reader annunciation.
Fixes #2508 
event …
> fix(pagination): adjust aria label defaults. Fixes #2508

- src/components/modal/README.md
- src/components/modal/modal.js
Adds new prop `scrollable` to modal for enabling scrollable dialog content, when the dialog would be taller than the viewport.
New in Bootstrap V4.3
TO DO:
**If new …
> feat(modal): add support for scrollable dialog content

- src/components/pagination/package.json
This caused the "Properties" section in the component docs to don't show up.
event changes)
keyboard only …
> fix(pagination): Component name in `package.json`

- src/components/table/table.js
Fixes private method `toString(...)` so that boolean `false` values can be filtered on.
Also adds special case for Date objects (using date's native toString method) and sorting of date objects.
Fixes #2485
"chore: fix typo in docs", etc). **This is very important, as the …
> fix(table): allow filtering on false values. Fixes #2485

- src/components/form-input/README.md
- src/components/form/README.md
- src/components/list-group/README.md
- src/components/modal/README.md
- src/components/table/README.md
Some minor tweaks to the docs.
event changes)
keyboard only users? clickable items should be in the tab …
> fix(docs): Minor markup cleanup

- docs/markdown/intro/README.md
- docs/markdown/reference/starter-templates/README.md
- docs/markdown/reference/theming/README.md
- docs/markdown/reference/utility-classes/README.md
- docs/pages/index.vue
- src/components/form/README.md
Update Bootstrap links in docs to v4.3.
event changes)
keyboard only users? clickable items should be in …
> fix(docs): Update Bootstrap links to v4.3

- CHANGELOG.md
- package.json
> chore: Update CHANGELOG.md and bump version

- docs/components/importdoc.vue
This PR fixes the directive import paths in the docs.
Closes #2568.
event changes) …
> fix(docs): Fix directive import paths (Closes #2568)

- CHANGELOG.md
- src/components/dropdown/README.md
- src/components/form-checkbox/README.md
Prettify docs and CHANGELOG.
event changes)
keyboard only users? clickable items should be in the tab …
> chore: Prettify

- src/components/table/table.js
If the table is in the busy state, and there are no item rows, do not show the empty row message when the busy slot is provided.
Closes #2565
**If new …
> feat(table): don't show empty row slot if table busy and busy slot provided (Closes #2565)

- docs/markdown/intro/README.md
Just fixes the docs to not break setup w/ Nuxt.
> docs: change @include to @import in the Nuxt plugin module section

- src/components/form-input/form-input.js
This PR re-enabled number value support to `<b-form-input>` which was accidentally removed with this PR #2204.
Closes #2582. …
> fix(form-input): Allow number as value type (Closes #2582)

- docs/components/footer.vue
Correct "Nuxt.js" casing and just use "GitHub" as footer nav item text.
event changes)
keyboard only …
> fix(docs): Improve wording in footer

- src/components/carousel/README.md
Please replace this line with a detailed description of your pull request. If no description your PR
may be rejected. …
> fix(docs): Correct typos in carousel docs

- src/components/breadcrumb/breadcrumb-item.js
- src/components/breadcrumb/breadcrumb-link.js
This PR fixes an bug that prevented the `to` prop to actually work for `<breadcrumb-item>`.
Closes #2575 …
> fix(breadcrumb-item): Fix `to` prop handling (Closes #2575)

- package.json
- src/index.d.ts
This PR adds `.ts` files to the list of extensions that `prettier` picks up.
Also prettify existing files. …
> chore: Prettify `.ts` files

- src/components/table/README.md
Adds additional information about the uses of the `primary-key` prop.
Closes #2580
event changes)
keyboard …
> docs(table): add additional info about primary-key prop (Closes #2580)

- babel.config.js
- scripts/build
Docs: https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs
This PR helps to prevent adding intropDefault to `es/` this
Also, remove unnecessary plugins from cjs build
from …
> fix(build): don't include babel runtime

- docs/markdown/intro/README.md
- nuxt/index.js
- nuxt/plugin.template.js
- Allow shorthand options for the module
- Update docs
- Prefer non `min` versions of styles for better debugging
- Use `es/` version
- Always transpile `bootstrap-vue/src`
from these …
> feat(nuxt): module improvements

- package.json
Add @jackmu95 to the list of maintainers in `package.json`.
event changes)
keyboard only users? clickable …
> chore: add @jackmu95 to maintainers

- .github/ISSUE_TEMPLATE.md
- Add [CodeSandbox](https://codesandbox.io/) to the list of online code editors
- Bolden headings
- Correct JSFiddle naming …
> chore: improve ISSUE_TEMPLATE

- docs/pages/play.vue
The playground console log uses `whitespace: pre-wrap` to format the log error messages. `prettier` mangled the pre space formatting by adding additional white space.
This PR removes this additional whitespace and adds `prettier` control comments to ignore this section.
Before:
After:
"fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix …
> chore(playground): remove excess whitespace from playground log

- nuxt/index.js
In Nuxt.JS plugin, changes:
```js
const bootstrapVueCSS = pickFirst(options.bootstrapVueCSS, options.bootstrapCss, options.bvCSS)
```
to:
```js
const bootstrapVueCSS = pickFirst(options.bootstrapVueCSS, options.bootstrapVueCss, options.bvCSS)
```
"chore: fix typo in docs", etc). …
> fix(nuxt plugin): fix typo with bootstrap vue css import properties

- src/components/table/README.md
Add a warning in the table items section about avoiding circular references in rows and field values.
Closes #2474 …
> docs(table): add warning about circular references in items row data (Closes #2474)

- docs/components/importdoc.vue
- docs/markdown/intro/README.md
- src/index.js
Document alternative way to import individual Plugins
event changes) …
> docs(intro): Document alternative way to import plugins

- docs/components/importdoc.vue
- docs/markdown/intro/README.md
- src/index.js
Reverts bootstrap-vue/bootstrap-vue#2617
> Revert "docs(intro): Document alternative way to import plugins"

- src/components/layout/README.md
Fixes colspan overflow in markdown issue by replacing markdown with HTML table for Layout Grid Options information. …
> fix(docs): fix grid options table layout issue

- src/components/modal/README.md
Fixes a race condition issue in the prevent closing example by wrapping the `hide` method call in a `$nextTick`
Closes #2633 …
> docs(modal): correct issue in prevent closing example (Closes #2633)

- src/components/table/_table.scss
Fix typo in class name for fixed table layout.
event changes)
keyboard only users? clickable items should …
> fix(table): fix class name for fixed table layout

- nuxt/index.js
Make Nuxt.js module default to inclusion of CSS files if config option(s) not provided.
The previous updates to the plugin module accidentally removed the defaults of `true`.
Cixes #2629. …
> fix(nuxt-module): fix default inclusion of CSS files (closes #2629)

- src/components/modal/README.md
- src/components/modal/modal.js
- src/components/modal/package.json
Adds a public method and root event to toggle a modal's visibility.
Closes #2708 
To Do:
event changes) …
> feat(modal): add toggle method and root event (Closes #2708)

- docs/components/componentdoc.vue
- docs/pages/docs/components/_slug.vue
- src/components/collapse/package.json
- src/components/modal/package.json
- src/components/popover/package.json
- src/components/table/package.json
- src/components/tooltip/package.json
Adds back in the missing reference to `rootEventListeners` from component package meta in `componentDoc.vue`  …
> docs(components): add in missing reference to root event listeners

- src/components/form-checkbox/form-checkbox-group.spec.js
- src/components/form-radio/form-radio-group.spec.js
Adds additional functionality tests to radio and checkboxes
> chore(tests): additional radio and checkbox tests

- src/components/form-select/README.md
- src/mixins/form-options.js
Update documentation on using the `options` props for `b-form-select`, `b-form-checkbox-group` and `b-form-radio-group`
**If new features/enhancement/fixes are added …
> docs(form options): Update documentation on using the options array

- src/components/carousel/carousel-slide.js
- src/components/carousel/carousel-slide.spec.js
- src/components/carousel/carousel.js
- src/components/dropdown/dropdown-item-button.js
- src/components/dropdown/dropdown-item-button.spec.js
- src/components/dropdown/dropdown-item.js
- src/components/dropdown/dropdown-item.spec.js
- src/components/form-checkbox/form-checkbox.js
- src/components/form-radio/form-radio.js
- src/components/progress/progress-bar.js
- src/components/progress/progress.js
- src/components/tabs/tab.js
- src/components/tabs/tab.spec.js
- src/components/tabs/tabs.js
- src/mixins/dropdown.js
This PR simplifies/unifies the default value declaration, and all injections are prefixed with `bv` for namespacing convenience.
**If new features/enhancement/fixes …
> chore: unify default provide and inject value usage

- src/utils/dom.js
Adds a convenience method to `utils/dom.js` for `requestAnimationFrame` (as `requestAF`)
Handy for components that use transitions and need to add a class in the `beforeEnter` hook to initiate the transition.
"chore: fix typo in docs", etc). **This is very important, as the …
> chore(dom): add requestAnimationFrame shorthand util

- src/mixins/form-radio-check-group.js
Removes the sizing class off of the group container, as the individual radios and checks will have the needed classes.
Closes #2743
**If new …
> fix(radio/check group): remove size class from the group container (Closes #2743)

- src/components/modal/modal.js
Adds a new prop `header-close-variant` for setting the color variant of the header close button (the <code>&times;</code> button).
Currently the header close button inherit's it's variant from the `header-text-variant`.  This PR allows the new `header-close-variant` to take precedence over the `header-text-variant`. If `header-close-variant` is not provided it falls back to the `header-text-variant` if provided.
Feature was requested on BootstrapVue discord channel.
and adding a new feature, break them into separate PRs if at all …
> feat(modal): add variant prop for header close button

- src/components/tabs/README.md
Minor docs updates.
Closes #2772
> chore(docs): minor updates to tab docs (Closes #2772)

- src/utils/html.js
Closes: #2770
event changes)
**If …
> fix(util/html): ensure argument is a string (Closes #2770)

- src/components/input-group/README.md
Closes #2786
event changes)
**If …
> chore(docs): fix typo in input-group example (Closes #2786)

- docs/pages/play.vue
fix prettier/eslint warning from play.vue.
event changes)
keyboard only users? clickable items should be …
> chore(docs): fix prettier/eslint warnings

- src/components/table/table.js
Fixes an error in text selection detection
event changes)
keyboard only users? clickable items should be …
> fix(table): fix detection of text selection

- src/utils/get.js
- src/utils/get.spec.js
Handle cases in `get()` util when the field value is not an array or object.
Closes #2807.
event changes) …
> fix(utils/get): handle cases when field value is not array or object (closes #2807)

- src/utils/loose-equal.js
- src/utils/loose-equal.spec.js
`array.prototype.every(...)` does not handle sparse arrays, as it only looks at explicitly defined indexes (keys basically)
```js
const array1 = [] // length is 0
// => []
array1[2] = true // length now is 3
// => [empty × 2, true]
Object.keys(array1)
//  => ["2"]
const array2 = [false, false, true] // length is also 3
// => [false, false, true]
Object.keys(array2)
// => ["0", "1", "2"]
array1.every((v, i) => array1[i] === array2[i])
// => true
array2.every((v, i) => array2[i] === array1[i])
// => false
```
The `looseEqual` routine was comparing arrays using array1.every(...), which only compares the indexes (keys) available/defined in array1, and not each and every possible index in the array.
This PR introduces a fix to handle sparse arrays.
**What kind of change does this PR …
> fix(util/loose-equal): handle comparing sparse arrays

- docs/markdown/reference/theming/README.md
Small fix to example code
event changes)
keyboard only users? clickable items should be in the tab index, …
> chore(docs): fix typo

- src/components/table/table.js
This PR allows strings to be passed to the `perPage` and `currentPage` props.
We do already parse them internally to integers so we don't need to change anything else.
While at it, I corrected some typos in the comments.
Closes #2821.
"chore: fix typo in docs", etc). **This is …
> fix(table): allow string for pagination prop types (closes #2821)

- src/utils/observe-dom.js
This is a follow-up fix to a bug #2825 introduced.
event changes) …
> fix(utils/observeDom): make sure to check for browser environment

- docs/assets/scss/styles.scss
- docs/components/toc.vue
- docs/content/index.js
Minor style adjustments to sidebar navs and toc navs
event changes) …
> chore(docs): minor tweaks to Sidebar and TOC

- src/components/breadcrumb/breadcrumb.js
- src/components/breadcrumb/fixtures/breadcrumb.html
- src/components/breadcrumb/fixtures/breadcrumb.js
- src/components/carousel/carousel.js
- src/components/collapse/collapse.js
- src/components/form-group/form-group.js
- src/components/image/img-lazy.js
- src/components/image/img-lazy.spec.js
- src/mixins/click-out.js
- src/mixins/focus-in.js
Additional coverage
event changes) …
> chore: additional coverage

- src/components/button/button.js
- src/components/button/button.spec.js
- src/components/image/img-lazy.spec.js
- src/components/media/fixtures/media.html
- src/components/modal/modal.spec.js
- src/mixins/click-out.spec.js
- src/mixins/focus-in.spec.js
- src/mixins/form-size.js
- src/mixins/listen-on-root.js
Rather than storing a reference to the handlers on the instance, it now registers a listener to the
components `beforeDestroy` hook event to remove the $root listener.
from these …
> chore(utils/listen-on-root): simplify $off handling + more test suite updates

- src/components/form-input/README.md
fix typo in b-form-input modifiers section
Please replace this line with a detailed description of your pull request. If no description your PR
may be rejected.
**If …
> fix(docs): fix typo

- src/components/modal/modal.js
> chore: more unit testing adjustments

- src/components/carousel/README.md
- src/components/carousel/carousel.js
Adds a new prop `no-hover-pause` that can be used to disabled carousel pausing on mouse over.
Closes #2887 …
> feat(carousel): add no-hover-pause prop

- src/components/carousel/carousel.js
- src/utils/noop.js
- src/utils/tooltip.class.js
This PR adds a `noop()` util and uses it wherever possible.
While at it, fix some comments.
event changes) …
> feat(utils/noop): add `noop()` util

- src/components/pagination-nav/README.md
- src/components/pagination/README.md
Few minor fixes to examples
event changes)
keyboard only users? clickable items should be in the tab …
> chore(docs): minor fixes

- src/components/form-checkbox/README.md
Fixed closing tag in `Contextual state and validation example`.
event changes) …
> docs(form-checkbox): fixed closing `<b-form-valid-feedback>` tag in contextual state and validation example

- src/components/table/helpers/mixin-thead.js
Possible fix for table SSR mismatch issues
Closes #2895
_a similar fix was used in pagination_
event …
> fix(table): fix SSR mismatch errors

- src/utils/dom.js
Updated to math the latest polyfill from:
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
Closes #2900
**If new features/enhancement/fixes …
> fix(utils/dom): update `closest()` routine to support SVG in IE11 (closes #2900)

- src/components/form-input/README.md
- src/components/form/README.md
- src/components/form/form-datalist.js
- src/components/form/form-datalist.spec.js
- src/components/form/index.js
- src/components/form/package.json
New helper component for creating `<datalist>` using an `options` array.  Handy for inputs that have a `list` attribute (like `<b-form-input>` and plain `<input>`) …
> feat(forms): new b-form-datalist component

- src/components/collapse/README.md
Closes #2903
event changes)
**If …
> chore(docs): fix typo in collapse accordion example (closes #2903)

- src/components/dropdown/_dropdown.scss
Fixes #2909
event changes)
**If …
> fix(dropdown): fix `no-caret` prop when dropleft (fixes #2909)

- src/components/form-checkbox/form-checkbox.spec.js
- src/mixins/form-radio-check.js
Closes #2911
To do:
event changes) …
> feat(form-checkbox/radio): allow no label in plain mode (fixes #2911)

- src/components/form-radio/README.md
Fix mistake on form-radio input in tag **b-form-valid-feedback**
- [х] Includes documentation updates …
> chore(docs): fix syntax mistake 

- src/components/collapse/collapse.js
- src/directives/toggle/toggle.js
Closes #2923
Better approach to fixing the original issue #1798 (and PR #2102)
event changes)
keyboard …
> fix(collapse/toggle): persist toggle state on element and prevent multiple state emits (closes #2923)

- src/components/tabs/tab.js
Deprecate the use of `href` prop on `<b-tab>` component.
Users should be using the `<b-nav>` component for navigation based tabs.
**If new features/enhancement/fixes …
> chore(tab): deprecate use of `href` prop

- src/components/link/fixtures/link.html
- src/components/link/fixtures/link.js
- src/components/link/link.js
- src/components/link/link.spec.js
Fixes #2938
event changes)
**If …
> fix(link): support handling multiple click event listeners (fixes #2938)

- docs/components/search.vue
#2893 introduces a change to `docs/components/search.vue` that removed the leading slash from the URL of the search results. This results in a 404 when clicking on the search result.
This PR adds the slash back and fixes the issue.
Closes #2945.
"chore: fix typo in docs", etc). …
> fix(docs): add back missing leading slash to search urls (closes #2945)

- docs/components/search.vue
Adds the `autocomplete="off"` attribute to the docs search input.
event changes) …
> chore(docs): disabled autocomplete on search input

- src/components/modal/modal.js
Fix for exiting fade transition on backdrop
Closes #2961
event changes)
keyboard only users? clickable …
> fix(modal): fix exiting fade animation on backdrop (closes #2961)

- src/utils/env.js
- src/utils/warn.spec.js
Check for `typeof process !== 'undefined'` (rather than for truthyness) in `utils/env.js`
Closes #2958  …
> fix(env): check for undefined on process (closes #2958)

- src/components/modal/modal.js
When a long page has been scrolled down, and a modal is opened, sometimes the page would scroll up a bit due to the sequence/timing of adding/adjusting scrollbar and modal-open class.
https://github.com/twbs/bootstrap/pull/27698
"chore: fix typo in docs", etc). **This is very …
> fix(modal): prevent page scroll as modal opens

- src/_utilities.scss
- src/components/dropdown/_dropdown-form.scss
- src/components/dropdown/_dropdown-text.scss
- src/components/dropdown/_dropdown.scss
- src/components/dropdown/index.scss
- src/components/index.scss
- src/components/nav/_nav-item-dropdown.scss
- src/components/nav/index.scss
- src/components/navbar/_navbar.scss
- src/components/navbar/index.scss
Switch from `:` to `::` pseudo selectors in SCSS for dropdown no-caret.
some browsers may have issues with `:` pseudo element selectors.
Closes #2951
**If new …
> chore(dropdown): switch to `::` from `:` pseudo selectors

- docs/components/importdoc.vue
- src/components/collapse/index.js
- src/components/collapse/package.json
- src/components/modal/index.js
- src/components/modal/package.json
- src/components/nav/package.json
- src/components/navbar/package.json
- src/components/popover/index.js
- src/components/popover/package.json
- src/components/tooltip/index.js
- src/components/tooltip/package.json
- src/index.js
- src/utils/plugins.js
The `plugins` and `directive` properties in the component's package meta must be at the top level.
They were inadvertently placed inside one of the individual component entries, making it not appear in the import reference sections.
Also tweaked the install routines for slightly improved performance.
"fix(alert): not alerting during SSR render", "docs(badge): Updated pill …
> fix(docs): fix component plugin's included plugins and directives

- src/components/table/README.md
Keeps the number of columns in examples reduced to a minimum, and adds responsive tables where needed.
This helps ensure that the example tables don't over flow on small screens (such as phones)
"chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is …
> docs(table): make examples work better on small screens

- src/components/jumbotron/jumbotron.spec.js
Unit testing
event changes)
**If …
> chore(unit testing): convert jumbotron test

- src/components/form/README.md
Minor update to lead in form example (showing form data result)
event changes) …
> docs: minor update to form lead-in example

- src/components/pagination/pagination.js
- src/components/pagination/pagination.spec.js
- src/components/table/README.md
- src/mixins/pagination.js
When the number of pages changes reset the current page to the first page and ensure the v-model is updated..
Closes #2987 …
> fix(pagination): reset to page 1 when total-rows or per-page changes (closes #2987)

- src/components/table/README.md
Fixed a few issues with the table complete example
event changes) …
> docs(table): minor updates to table complete example

- src/components/pagination/README.md
Currently the closing tag for `b-table` is `b-paginate` in the Pagination example docs; so I've fixed it to have the correct closing tag ie. `b-table`.
**If new …
> fix(docs): fix the closing tag for `<b-table>` in pagination example

- src/components/pagination/pagination.js
Fixes a typo in the component name from PR #3018 
event changes) …
> chore: fix b-pagination component name

- docs/plugins/bootstrap-vue.js
- src/components/modal/helpers/modal-manager.js
- src/components/modal/modal.js
- src/components/modal/modal.spec.js
- src/mixins/listen-on-root.js
- src/mixins/listen-on-root.spec.js
- src/utils/config.js
- src/utils/dom.js
Some additional modifications/tweaks to be applied to PR #3017
- No longer needs config options to set z-index (determined automatically by querying the computed styles of a temporary modal-backdrop element)
- Each stacked modal will now have it's z-index offset by 1 from the previously opened modal, keeping all z-indexes within a small range (i.e. 1040, 1041, 1042, etc), which should avoid placing modals over such items as notifications and toasts (which typically have a z-index of 2000 or higher)
- Created a `modalManager` instance that will handle keeping track of the opened modals (and their order), and managing their z-index, as well as controlling classes and adjustments on document.body and sticky/fixed page content.
**What kind of change does this PR introduce?** (check at least …
> fix(modal): z-index adjustments in PR #3017

- src/components/modal/modal.js
- src/components/modal/modal.spec.js
Fixes #3025
event changes)
**If …
> fix(modal): prevent close on backdrop when click initiated inside modal content (fixes #3025)

- CHANGELOG.md
- CONTRIBUTING.md
- docs/markdown/misc/settings/README.md
- docs/markdown/reference/theming/README.md
- docs/markdown/reference/validation/README.md
- docs/nuxt.config.js
- src/components/collapse/README.md
- src/components/table/README.md
To line up with Bootstrap V4 docs formatting, convert `lead` paragraphs (which use blockquote in markdown) to a paragraph `<p>` tag with class `bd-lead`.
Provides for better semantic HTML markup.
"chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is …
> docs: custom marked formatter for lead-in blockquotes

- scripts/rollup.config.js
Add `vue` to external array in rollup.config.js for the `esm` build
event changes) …
> chore(build): ensure Vue is excluded from `bootstrap-vue.esm.js` build

- babel.config.js
Fixes #3038 by producing valid `es` code to work with both cjs and es builds of `vue`:
```js
var _vue = _interopRequireDefault(require("vue"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
"chore: fix typo in docs", etc). …
> fix(build): enable babel option to interop default (fixes #3038)

- src/components/modal/README.md
This PR improves the "Prevent Closing" example in the `<b-modal>` docs by using the Validation API.
Closes #2497. …
> fix(docs): improve <b-modal> prevent closing example (closes #2497)

- docs/markdown/intro/README.md
- docs/nuxt.config.js
- scripts/build.scss
- scripts/build.sh
- src/_utilities.scss
- src/_variables.scss
- src/components/button/package.json
- src/components/dropdown/_dropdown-form.scss
- src/components/dropdown/_dropdown-text.scss
- src/components/dropdown/_dropdown.scss
- src/components/form-input/_form-input.scss
- src/components/input-group/_input-group.scss
- src/components/jumbotron/README.md
- src/components/pagination-nav/_pagination-nav.scss
- src/components/pagination/_pagination.scss
- src/components/table/_table.scss
- src/index.scss
- src/utils/config.js
Only include Bootstrap V4 SCSS functions, vars, and mixins during `bootstrap-vue.css` build. Removes them from the `/src/index.scss` file.
When users need to customize CSS they need to include Bootstrap.SCSS (or parts), followed by Bootstrap-Vue SCSS (which is the recommended way in the Docs, so no breaking changes for users who have custom Bootstrap SCSS).
Closes #2917  …
> chore: CSS build improvements (closes #2917)

- src/components/modal/README.md
Re-organizes sections and tweak some content.
event changes)
keyboard only users? clickable items should …
> docs(modal): minor udpates to modal docs

- docs/markdown/intro/README.md
- src/components/popover/README.md
- src/components/tooltip/README.md
Docs update
event changes)
**If …
> chore(docs): fix some heading levels and remove necessary blockquote sections that are not the lead in paragraph

- src/components/table/_table.scss
- src/components/table/table.js
Prevent hover styles from being applies to to busy/empty row.
Closes #3079.
event changes)
keyboard only …
> fix(table): prevent hover style on busy/empty row (closes #3079)

- src/components/dropdown/dropdown-divider.js
- src/components/dropdown/dropdown-divider.spec.js
- src/components/dropdown/dropdown-form.js
- src/components/dropdown/dropdown-form.spec.js
- src/components/dropdown/dropdown-header.js
- src/components/dropdown/dropdown-header.spec.js
- src/components/dropdown/dropdown-item-button.js
- src/components/dropdown/dropdown-item-button.spec.js
- src/components/dropdown/dropdown-item.js
- src/components/dropdown/dropdown-item.spec.js
- src/components/dropdown/dropdown-text.js
- src/components/dropdown/dropdown-text.spec.js
- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown.spec.js
- src/components/nav/nav-item-dropdown.js
- src/mixins/dropdown.js
- src/utils/object.js
> Bootstrap V4 is moving back to recommending semantic markup for their dropdown menus.
> 
> Placing the dropdown items (and other sub-components) inside `<li>` elements, and setting the dropdown menu container to a `<ul>`
> 
> twbs/bootstrap#28591
> twbs/bootstrap#25728
> 
> We should update these components to use the new recommended markup.
Closes #3072.
"fix(alert): …
> feat(dropdown): use semantic `<ul>` and `<li>` markup (closes #3072)

- src/components/dropdown/dropdown-item.js
- src/components/dropdown/dropdown-item.spec.js
- src/components/dropdown/dropdown.spec.js
- src/components/link/link.js
- src/components/link/link.spec.js
Fixes #3066 (Hopefully)
event changes)
keyboard only users? clickable items should be in the tab index, …
> fix(b-link): ensure href prop is not passed to router-links (fixes #3066)

- src/components/modal/modal.js
Fix typo in code comment
event changes)
keyboard only users? clickable items should be in the tab index, …
> chore(modal): fix typo in comment

- .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
More tweaks to the issue/PR templates.
event changes)
keyboard only users? clickable items should be in …
> chore: more tweaks to the issue/PR templates

- docs/nuxt.config.js
- package.json
- yarn.lock
Limit `core-js` to v2.x for now and add better polyfills for the docs.
Closes #3108.
`[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
adding a new feature, break them into separate PRs if at all possible.
naming convention (i.e. `fix(alert): not alerting during SSR render`,
`docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is
very important, as the `CHANGELOG` is generated from these messages.**
event changes)
keyboard only users? Clickable items should be in the tab index, etc.)
**If adding a new feature, or …
> chore: stick to `core-js` v2 + better docs polyfill (closes #3108)

- yarn.lock
Revert latest `yarn.lock` changes to fix Netlify deploy.
The reason for the failure was an dependency upgrade from `conventional-changelog-conventionalcommits` which requires a Node version >= 10. Netlify uses 8.x.
`[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
adding a new feature, break them into separate PRs if at all possible.
naming convention (i.e. `fix(alert): not alerting during SSR render`,
`docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is
very important, as the `CHANGELOG` is generated from these messages.** …
> chore: revert `yarn.lock` changes

- .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .prettierrc
Fix issue template prose wrap.
`[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
adding a new feature, break them into separate PRs if at all possible.
naming convention (i.e. `fix(alert): not alerting during SSR render`,
`docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is
very important, as the `CHANGELOG` is generated from these messages.**
event changes)
keyboard only users? Clickable items should be in the tab index, etc.)
**If adding a new feature, or changing the functionality of an existing feature, the …
> chore: fix issue template prose wrap

- docs/markdown/intro/README.md
- docs/nuxt.config.js
Fix the polyfill suggested and used in the docs to actually work on IE 11.
> fix(docs): fix polyfill for IE 11

- docs/components/sidebar.vue
- docs/markdown/intro/README.md
- src/components/modal/package.json
> fix(docs): minor tweaks

- src/components/modal/helpers/bv-modal.js
Fix for preventing errors during Hot Module Reload (HMR) 
> fix(modal): handle HMR when defining property on Vue prototype

- src/components/modal/modal.js
Addresses https://github.com/bootstrap-vue/bootstrap-vue/issues/3126#issuecomment-484347044
Specifically: When the v-model is used to open or hide the modal, and the corresponding show or hide event was cancelled, the v-model was not being reset.
> fix(modal): ensure that v-model is updated when show or hide is canceled

- src/_variables.scss
- src/components/toast/README.md
- src/components/toast/_toaster.scss
- src/components/toast/toast.js
- src/components/toast/toaster.js
Updates to the `<b-toaster>` structure and SCSS, to allow additional flexibility for styling of custom toasters.
Adds in 4 more toaster definitions (for a total of 8)
Enables hover-pause of auto-dismiss toasts (when mouse is over the toast, the auto hide delay will pause until the mouse leaves the toast)
Auto-hides the toast on body click when toast is actionable (has an `href` or `to` prop)
> feat(toast): updates to toaster SCSS and structure and enable hover-pause

- nuxt/index.js
Ensures that `this.options.css` and `this.options.build.transpile` are existing arrays
Fixes #3141
> fix(nuxt module): ensure that css and transpile are arrays (fixes: #3141)

- src/mixins/form-radio-check.js
Adds new prop that will apply an `aria-labelledby` attribute to the input.
Closes #3139
> feat(form-checkbox, form-radio): add `aria-labelledby` prop (closes: #3139)

- src/components/table/README.md
The info modal in the complete <b-table> example isn't working due an incorrect used Id when opening the modal programatically.
Closes #3144.
> fix(docs): info modal in complete <b-table> example (closes #3144)

- docs/components/sidebar.vue
#3129 introduced a regex to normalize the generated sidebar URL's that relied on ES2018 browser support. This commit changes the regex to one with better browser support.
> fix(docs): use regex to normalize URL with better browser support

- src/components/table/table.js
Adds a new prop `table-class` to apply arbitrary classes to `<table>` element (specifically usefull when table is in responsive mode and the `<table>` element is not the root element)
Closes: #3138
> feat(table): add new prop `table-class` for applying classes to table root element (closes #3138)

- renovate.json
Prevent renovate from trying to upgrade `core-js` above `<3.0.0` to prevent https://github.com/bootstrap-vue/bootstrap-vue/pull/3151
> chore: add `core-js` to renovate.json `ignoreDeps`

- src/_variables.scss
- src/components/table/_table.scss
Makes the table sort icons configurable via SCSS variables.
Addresses #2126 
> feat(table): make table sort icons configurable via SCSS variables

- src/components/toast/toast.js
Use `document.body.appendChild()` instead of `document.body.append()` for IE 11 support
> fix(toast): use appendChild insated of append for IE 11 support

- src/components/table/README.md
- src/directives/popover/README.md
- src/directives/tooltip/README.md
This PR fixes a typo in the tooltip documentation.
> fix(docs): typo in ´<strong>´ tags

- src/components/collapse/collapse.js
- src/components/collapse/collapse.spec.js
- src/directives/toggle/toggle.js
- src/utils/target.js
Allows the collapse target(s) id(s) to be dynamic
Closes #3165
> feat(v-b-toggle): make targets reactive to updates (closes #3165)

- src/components/table/README.md
Adds additional clarification about sort-compare routine.
> chore(docs): minor updates to `<b-table>` docs sort-compare section

- src/components/alert/alert.js
- src/components/badge/badge.js
- src/components/button/button-close.js
- src/components/button/button.js
- src/components/card/card-sub-title.js
- src/components/carousel/carousel.js
- src/components/dropdown/dropdown.js
- src/components/form-file/form-file.js
- src/components/form/form-text.js
- src/components/image/img-lazy.js
- src/components/image/img.js
- src/components/jumbotron/jumbotron.js
- src/components/list-group/list-group-item.js
- src/components/modal/modal.js
- src/components/navbar/navbar-toggle.js
- src/components/navbar/navbar.js
- src/components/progress/progress-bar.js
- src/components/progress/progress.js
- src/components/spinner/spinner.js
- src/components/table/helpers/mixin-selectable.js
- src/components/table/helpers/mixin-tfoot.js
- src/components/table/helpers/mixin-thead.js
- src/components/toast/toaster.js
- src/utils/config.js
This PR makes more component appearance props globally configurable.
Closes #3173.
> feat: make more component appearance prop defaults globally configurable (closes #3173)

- src/components/toast/README.md
> chore(docs): toasts fix typo im -> in

- src/_variables.scss
Alerts now use the default bootstrap fade transition (for a while), and this variable is no longer needed.
> chore: remove no longer needed SCSS variable

- src/components/navbar/README.md
Minor updates to navbar docs. Fixes mistake in input-group example
> chore: minor updates to navbar docs

- scripts/banner.txt
- scripts/build.sh
- scripts/rollup.config.js
- src/index.js
Add a header comment to main index.js file
> chore: add header comment to main index.js

- src/components/dropdown/README.md
- src/components/dropdown/dropdown-divider.js
- src/components/dropdown/dropdown-form.js
- src/components/dropdown/dropdown-group.js
- src/components/dropdown/dropdown-group.spec.js
- src/components/dropdown/dropdown-header.js
- src/components/dropdown/dropdown-header.spec.js
- src/components/dropdown/dropdown-item-button.js
- src/components/dropdown/dropdown-item.js
- src/components/dropdown/dropdown-text.js
- src/components/dropdown/index.js
- src/components/dropdown/package.json
- src/utils/normalize-slot.js
Default to using `<header>` tag instead of `<h6>` for `<b-dropdown-header>` (as `<h6>` implies an explicit heading level of 6 within the document as a whole)
Create a new sub-component `<b-dropdown-group>` for semantically grouping a dropdown items with an integrated associated header
Added `inheritAttrs: false` on all sub-components so that the inner element will receive any additional attributes (ie. `aria-*`, `id`, etc) that the user may want to add.
To Do:
description above …
> feat(dropdown): additional semantic markup optimizations for A11Y

- src/components/collapse/collapse.js
Testing scenario where we don't need a new utility class
> test(collapse): testing use of show class check

- src/components/dropdown/dropdown-item-button.js
- src/components/dropdown/dropdown-item.js
> chore: prettier vue component definition order

- docs/pages/index.vue
Add `<abbr>` tag and tooltip to WAI-ARIA on docs landing page.
> chore(docs): landing page - add `<abbr>` tag and tooltip to WAI-ARIA

- src/components/button/README.md
- src/components/button/button.js
- src/components/button/button.spec.js
Adds a new boolean prop `pill`, which defaults to `false`. When `true`, the button will have rounded pill corners.
> feat(button): add prop `pill` for pill style buttons

- src/components/modal/README.md
- src/components/nav/README.md
- src/components/tabs/README.md
Adds a badge under headings where new functionality, or enhanced/changed functionality is documented.
Closes #3218
> docs: add badges to ehanced/new/changed sections of docs

- src/components/modal/helpers/bv-modal.spec.js
- src/utils/config.spec.js
- src/utils/plugins.js
Checks for multiple instances of Vue and issues a warning when using Plugin(s). Will only warn once.
Addresses issue #3040
> feat: add warning if multiple instances of Vue detected (addresses #3040)

- src/components/modal/modal.js
- src/components/modal/modal.spec.js
Focusing the document.body can cause un-watned scrolls of the page on some browsers.
When auto-detecting the return focus element, this PR excludes selecting/focusing document.body.
When an element that has focus and then is hidden, browsers will blur the element an set document.body as the active element.
> fix(modal): exclude document.body when determining return focus element

- src/components/dropdown/README.md
- src/components/modal/modal.js
Prevent duplicate key when sending to portal-target.
> fix(modal): prevent duplicate key when sending to portal-target

- src/components/modal/modal.js
- src/components/toast/helpers/bv-toast.js
- src/components/toast/helpers/bv-toast.spec.js
- src/components/toast/toast.js
- src/components/toast/toast.spec.js
- src/components/toast/toaster.js
- src/components/toast/toaster.spec.js
> chore(toast): create unit tests for toasts

- nuxt/index.js
> chore(nuxt plugin): minor updates

- docs/pages/index.vue
> chore(docs): reference Vue 2.6+ in docs

- src/components/collapse/index.js
- src/components/modal/index.js
- src/components/popover/index.js
- src/components/toast/index.js
- src/components/tooltip/index.js
- src/directives/modal/index.js
- src/directives/popover/index.js
- src/directives/scrollspy/index.js
- src/directives/toggle/index.js
- src/directives/tooltip/index.js
Minor updates to code.
The `registerDirective` and `registerDiretives` helper methods in plugin.js now support stripping of the leading `V` on object shorthand names, so this PR adjusts the module import names in the various component plugin files.
> chore: minor updates to code structure.

- docs/markdown/intro/README.md
- docs/markdown/reference/starter-templates/README.md
> chore(docs): mention Vue CLI 3 plugin

- src/components/nav/README.md
- src/components/nav/nav-item-dropdown.js
- src/components/nav/nav-item-dropdown.spec.js
> fix(b-nav-item-dropdown): fix disabled state (fixes #3264)

- src/components/modal/README.md
- src/components/modal/helpers/bv-modal.js
- src/components/toast/README.md
- src/components/toast/helpers/bv-toast.js
- src/utils/warn.js
Minor updates to some docs
Also adds a `warn` when accessing `$bvModal` and `$bvToast` not via the `this` context (i.e. attempting to use `Vue.prototype.$bvToast(...)`).
Closes #3262
> chore(docs): minor docs updates (closes #3262)

- types/components/modal/index.d.ts
Correct "scrolable" typo to "scrollable"
(technically yes because it's changing the interface, but it's a fix so I would say no)
> chore: fix typo in type BvMsgBoxOptions definition

- CHANGELOG.md
- package.json
> chore: bump version and update changelog

- types/components/modal/index.d.ts
> fix(types): fix msxBoxConfirm typo

- src/utils/plugins.js
import 'OurVue' from `utils/vue` rather than from `'vue'`
> chore(plugins): import 'OurVue' from utils/vue

- docs/markdown/misc/settings/README.md
Updates the example plugin imports with new simplified imports
> chore(docs): update `/docs/misc/config` docs with simplified plugin import

- src/components/image/README.md
- src/components/image/img-lazy.js
- src/components/image/img-lazy.spec.js
- src/utils/env.js
If the browser supports `IntersectionObserver`, we use it instead of window event listeners for checking if the image is in range of the `viewport`
closes #3276
> feat(b-img-lazy): add support for IntersectionObserver (closes #3276)

- src/components/table/README.md
Fixes mistake in the table complete example.
> docs(table): fix typo in complete example

- src/components/input-group/input-group.js
- src/components/input-group/input-group.spec.js
Fixes typo in append slot checking
Closes #3284 
> fix(b-input-group): fix issue with slots (closes #3284)

- docs/nuxt.config.js
Remove route render errors for plugins.js and plugins-legacy.js files by adding to excludes.
> chore(docs): exclude route render attempt for plugins.js

- src/components/form-input/package.json
> chore(docs): fix typo in form-input meta

- src/components/modal/helpers/bv-modal.spec.js
- src/components/toast/helpers/bv-toast.spec.js
- src/utils/config.spec.js
- src/utils/dom.js
- src/utils/env.js
- src/utils/plugins.js
Suppresses the `Multiple Vue instances detected` warning when running under vue-test-utils and JSDOM
Closes #3303
> feat: don't warn about multiple Vue instances when testing in JSDOM (closes #3303)

- src/components/input-group/input-group.js
When using both prop `prepend` and slot `prepend`, place contents in the same `b-input-group-prepend` sub-component.
When using both prop `append` and slot `append`, place contents in the same `b-input-group-append` sub-component.
Will fix case where margin may be off by 1px (issue reported on discord chat)
> fix(b-input-group): use same input-group-prepend/append for both props and slots

- src/components/toast/_toaster.scss
Adds in css `width: 100%` for proper toast positioning in IE 11.
Closes #3327 
> fix(b-toaster): CSS fix for IE11 support (fixes #3327)

- docs/markdown/reference/validation/README.md
Old example of interaction with Vuelidate can't work
> fix(docs): correct Vuelidate validation example and some minor tweaks

- src/components/modal/package.json
This PR corrects the `BModal` directive name form `vBModal` to `VBModal`.
Closes #3334.
> fix(docs): correct modal directive name (closes #3334)

- docs/nuxt.config.js
- src/components/progress/README.md
Make it more clear which `<b-progress-bar>` prop supports HTML in the docs.
Closes #3333.
> fix(docs): route generation + `b-progress-bar` label HTML support examples (closes #3333)

- src/index.js
Use `installFatory` function for reduced code size for main BootstrapVue plugin.
Closes #3338
> fix: use `installFactory` for main `BootstrapVue` plugin (closes #3338)

- src/components/alert/alert.js
Handle edge case where `show` prop changes from a number to a Boolean.
Closes #3346
> fix(b-alert): handle case where dismiss countdown changes to a boolean value (closes #3346)

- src/components/form-checkbox/form-checkbox-group.js
- src/components/form-checkbox/form-checkbox.js
- src/components/form-radio/form-radio-group.js
- src/components/form-radio/form-radio.js
- src/components/modal/modal.js
- src/components/modal/package.json
- src/mixins/form-radio-check-group.js
- src/mixins/form-radio-check.js
Remove underscore from variable names.
> chore: remove underscore form variable and method names

- src/components/form-checkbox/README.md
- src/components/form-file/README.md
- src/components/form-input/README.md
- src/components/form-radio/README.md
- src/components/form-select/README.md
- src/components/form-textarea/README.md
> chore: add badges to new features for form-controls docs

- docs/markdown/intro/README.md
- src/utils/plugins.js
Minor update to `multiple vue instances detected` warning message, adding mention of setting up an alias.
> chore: minor update to `multiple Vue instances detected` warning

- src/components/toast/README.md
Update toast docs noting that toasts on demand without a message body will not be shown.
Closes #3359
> chore(toast): update toast docs (closes #3359)

- src/components/toast/README.md
Adds an example on passing `VNodes` to `this.$bvToast.toast(...)` method
> chore(docs): add advanced usage example to toasts

- src/components/alert/index.d.ts
- src/components/collapse/index.d.ts
- src/components/tabs/index.d.ts
Some minor additions to type declarations
> chore(types): additional updates to type declarations

- docs/markdown/intro/README.md
- src/utils/plugins.js
Minor updates to the checkMultipleVue routine. Generate the method via an IIFE
Minor update to module bundlers section of getting started docs (closes #3351)
> chore: update to `utils/plugins` multiple vue warn and docs intro update (closes #3351)

- docs/components/header.vue
If docs are detected to be running in dev mode, dev preview or localhost, adjust ordering of the version dropdown menu in navbar
> docs(header): order version dropdown based on hostname / dev mode

- src/components/modal/modal.js
> fix(modal): use `safeId()` when comparing id received by hide/show handler (closes #3389

- src/index.d.ts
Closes #3390
Assistance from anyone with TypeScript experience is greatly welcomed.
> fix(types): adjust typing of BvComponent & BvPlugin (closes #3390)

- src/components/modal/README.md
Fixes a typographical error for the modal documentation.
> (docs)modal: fix typo

- scripts/rollup.config.js
Reduces bundle CJS size, and allows consumers to use updated version of externals if needed. Matching the content with the ESM builds.
`dist/bootstrap-vue.common.js` will no longer include: `core-js`, `popper.js`, `portal-vue`, `vue-functional-data-merge`, of which all are included in our `package.json` dependencies.
> chore(build): don't include any externals in CommonJS bundle

- nuxt/index.js
Handles edge cases where users pass component, directive or plugin names as either `kebab-case` or `camelCase`, and normalizes them to the required `PascalCase` names
> feat(nuxt): handle edge cases where component, directive and plugin names are passed as `camelCase` or `kebab-case`
