package.json

Allows the Parcel bundler (and potentially more in the future) to use the source code as the module instead of pre-transpiled code

feat: add `"source": "src/index.js"` entry in package.json

---

docs/markdown/intro/README.md
docs/markdown/reference/images/README.md

Add mention in docs that Nuxt module now automatically configures `transformAssetUrls` to handle BootstrapVue component props

chore(docs): mention that Nuxt module now configures `transformAssetUrls`

---

src/components/table/helpers/mixin-filtering.js
src/components/table/helpers/mixin-provider.js

Ensure filter value is passed when not using local filter function or using provider filtering.
Fixes #3428

fix(table): ensure provider is refreshed when filter is an object (closes #3428)

---

src/components/modal/_modal.scss

Removed the double `:not(...)` selector off of the modal-backdrop override, as it was not really needed, as the `.modal-backdrop.show` and `.modal-backdrop.fade` classes have more specificity.
Reduces compiled CSS size (by a few bytes).

chore(modal): simplify modal backdrop CSS tweak for re-usable transition

---

src/components/pagination-nav/pagination-nav.js

fix(b-pagination-nav): attempt to auto-detect current page when `pages` array or `number-of-pages` changes (closes #3443)

---

src/components/table/README.md
src/components/table/helpers/mixin-items.js
src/components/table/helpers/mixin-pagination.js
src/components/table/helpers/mixin-provider.js
src/components/table/helpers/mixin-sorting.js
src/components/table/helpers/mixin-table-renderer.js
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-tbody.js
src/components/table/helpers/mixin-thead.js
src/components/table/helpers/mixins-table-renderer.js
src/components/table/index.d.ts
src/components/table/index.js
src/components/table/package.json
src/components/table/table-lite.js
src/components/table/table-lite.spec.js
src/components/table/table.js

New `<b-table-lite>` table component. using shared _helper_ code of `<b-table>`, but tailored for just rendering arrays of items, without enhanced features.
New component **does not** support:
- Filtering
- Sorting
- Pagination
- Provider functions
- Busy state
- Selectable rows
- Fixed top / bottom rows
This PR refactored the `<b-table>` helper code-base to support lightweight table components.
When importing individual components, this will help consumers reduce their bundle size if they don't need the full `b-table` feature set.
**If adding a new feature, or …

feat(b-table-lite): new `<b-table-lite>` lightweight table component

---

src/components/pagination-nav/package.json

fix(pagination-nav): fix incorrect name in component package.json file (closes #3458)

---

src/utils/get.js

Handles cases where values in table rows are getters (and/or when properties in the row are inherited)
Closes #3463

fix(utils/get): handle edge case with inherited object getters (fixes #3463)

---

yarn.lock

Reverts bootstrap-vue/bootstrap-vue#3456

Revert "chore(deps): bump handlebars from 4.1.1 to 4.1.2"

---

yarn.lock

Reverts bootstrap-vue/bootstrap-vue#3460

Revert "chore(deps): bump js-yaml from 3.13.0 to 3.13.1"

---

src/components/form-textarea/form-textarea.js

Update comments in form-textarea height computations for clarity

chore: minor comment updates in form-textarea

---

docs/markdown/reference/utility-classes/README.md

There were 2 links to "Position" in the list of "Utility classes" in "Reference" docs.
Remove the link that breaks alphabetical order.

fix(docs): remove duplicate link to Position

---

src/components/input-group/index.d.ts

The `BInputGroup` component is missing in the TypeScript definitions file. This change adds the definition the the file.

fix(types): add BInputGroup to TypeScript definitions

---

src/components/modal/modal.js

In some instances the `ignoreBackdropClick` flag was not being cleared

fix(modal): ensure `ignoreBackdropClick` flag is cleared in `clickOutHandler`

---

docs/components/componentdoc.vue

Fix markup to remove prettier warning

chore(docs): fix prettier warning

---

src/components/modal/_modal.scss
src/components/modal/modal.js
src/components/modal/modal.spec.js

Fixes an issue when copy/pasting text from modal to MS Word when using IE 11.
MS Word appears to not look at all the classes applied to the modal, and pastes the content with the MS Word `hidden` attribute.
Fixes #3457 

fix(modal): fix IE11 issue with copy/paste from modal into MS Word (fixes #3457)

---

src/components/modal/helpers/bv-modal.js
src/components/modal/modal.js
src/components/toast/helpers/bv-toast.js

The `title-html`, `ok-title-html` and `cancel-title-html` props were being rendered as plain text.
Also added in minor adjustment to prevent `prop type check` warnings (in dev mode) when passing arrays of vNodes for msgBoxes and on demand toasts.
Closes #3491

fix(modal): properly render `*-html` props if provided (closes #3491)

---

docs/markdown/reference/validation/README.md

fixes typo in vee validate example
Closes #3494 

chore(docs): fix typo in vee-validate example (closes #3494)

---

src/components/pagination-nav/README.md
src/components/pagination/README.md

Clarifications to keyboard navigation section regarding https://www.w3.org/TR/wai-aria-practices-1.2/#kbd_roving_tabindex
Addresses #3496 

chore(docs): minor updates to pagination/pagination-nav docs

---

src/components/form-input/_form-input.scss

Bootstrap v4.3.2 SCSS will deprecate the `form-control-focus()` mixin (as they only use it once). https://github.com/twbs/bootstrap/pull/28262
Updates the custom range input group style to replace the mixin.
Will prevent SCSS deprecation warnings when Bootstrap 4.3.2 is released.

chore: update form-input custom range SCSS

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js

`b-table-lite` does not support the busy state, so do not check if localBusy is not available.

fix(b-table-lite): add checks to helper mixins for existence of stopIfBusy  (closes #3518)

---

docs/markdown/intro/README.md

Adds a small section on prerequisites in the getting started page.

docs(intro): add prerequisites section

---

src/components/tabs/tabs.js

Handle edge case when registered tabs change order in document.
Adds back in `observeDom` checking, just for detecting change in the order of the child tabs (not needed for new/removed tabs)
Addresses #3506

fix(tabs): add detection of when registered tabs change order

---

docs/markdown/reference/utility-classes/README.md

Adds a few extra links in the bootstrap Utility Class reference section

chore(docs): add a few more links to Utility Classes reference section

---

src/components/form-select/README.md

Notes that not all browsers support rendering inline elements inside an `<option>` element.

docs(b-form-select): add clarification about `html` limitations in options array

---

src/components/tabs/tabs.js

Includes watching for changes in child b-tab `id` attribute, to assist with detecting order change.
Will not handle all edge cases (as Vue could be re-using elements, and user doesn't provide an ID) and doesn't trigger a change in the DOM children detection.
Vue 2.6.x doesn't always trigger updates in parent component when children update.

chore(b-tabs): include attribute 'id' in observeDom config

---

src/components/table/helpers/mixin-thead.js

If the table has no fields/items, then do not render the `<thead>` and `<tfoot>` elements for accessibility reasons.
Closes #3547

feat(table): don't render `thead` or `tfoot` if no fields (closes #3547)

---

docs/components/codemirror.js
docs/components/componentdoc.vue
docs/components/importdoc.vue
docs/markdown/intro/README.md
docs/markdown/reference/spacing-classes/README.md
docs/nuxt.config.js
docs/pages/play.vue
docs/plugins/play.js
docs/utils/marked-loader.js

Prevent google translate from translating certain parts of the docs pages (such as examples, `<code>` spans, `<kbd>` spans, etc)
Allows users to translate the docs (via browser), but leaves examples and prop names, etc, alone, making the translated docs more usable (as some content editable sections were no longer editable because of google translation).
Google translate is supposed to honor the attribute `translate="no"` but for some reason doesn't always.  But it does respect class `notranslate` (as does MS Edge). This PR applies both.
**If adding a new feature, …

chore(docs): mark some elements as `translate="no"`

---

src/components/input-group/input-group.js
src/components/input-group/input-group.spec.js

fix(b-input-group): fix kebab-case prop names for `prepend-html` and `append-html` (fixes #3565)

---

CHANGELOG.md
docs/components/header.vue
docs/markdown/intro/README.md
docs/markdown/reference/accessibility/README.md
docs/markdown/reference/accessibility/meta.json
docs/pages/docs/reference/index.js
src/components/badge/README.md
src/components/form-input/README.md
src/components/pagination-nav/README.md
src/components/pagination/README.md
src/components/toast/README.md

Basically a port of Bootstrap V4's accessibility docs, tailored for BootstrapVue

docs: create accessibility reference section

---

src/components/tabs/package.json
src/components/tabs/tabs.js

Emits event `changed` whenever child tabs are added, removed, or re-ordered. event will receive two arguments: the new array of `b-tab` instances, and the old array of `b-tab` instances.
Closes #3575 

feat(b-tabs): emit `changed` event whenever tabs added, removed or re-ordered (closes #3575)

---

src/components/pagination-nav/pagination-nav.spec.js

Remove console errors/warning with JSDOM and URL click testing

chore: update pagination-nav.spec.js to prevent JSDOM errors.

---

scripts/docs-publish.sh

Fix docs publish script known_host perms.

chore: update docs-publish.sh

---

scripts/docs-publish.sh

Fix permissions on known_hosts file

chore: update docs-publish.sh (#3592)

---

src/components/form-group/README.md

chore(docs): fix typo in form-group docs (closes #3601)

---

docs/assets/scss/styles.scss
docs/pages/play.vue

Fixes a JS error when using babel transpiler for IE 11 in playground.

fix(playground): fix undefined variable error in IE 11

---

src/components/collapse/collapse.js

Use `listenenOnRoot` method for `$root` sync state requests event listener.
Fixes #3607

fix(b-collapse): fix memory leak from `$root` listener (fixes #3607)

---

docs/markdown/intro/README.md

Borrows from Bootstrap's getting started page regarding required doctype and meta tags and base styling.

docs(getting started): add section on required HTML tags

---

docs/assets/scss/styles.scss
docs/components/codemirror.js
docs/components/footer.vue
docs/components/header.vue
docs/components/importdoc.vue
docs/nuxt.config.js
docs/pages/docs/misc/_slug.js
docs/pages/index.vue
docs/pages/play.vue
docs/plugins/codemirror.js
docs/plugins/play.js
docs/utils/hljs.js

Adds a few cards to index page highlighting features, and minor adjustments for layout and style
Also reduces docs vendor bundles by importing only the `highlight.js` languages needed, and turning off eval-source-maps in prod mode (now enabled for dev mode only)

docs: add some pizazz to index page

---

CHANGELOG.md
docs/assets/scss/styles.scss
docs/components/footer.vue
docs/layouts/docs.js
docs/pages/index.vue
docs/pages/play.vue
src/components/list-group/README.md
src/components/popover/README.md
src/components/tooltip/README.md

docs: minor tweaks

---

docs/assets/scss/styles.scss
docs/nuxt.config.js
docs/pages/index.vue

Adds a few media queries for sizing sections/padding for smaller screens.

docs: add a few media queries to landing page

---

src/components/toast/index.d.ts

Adds `noCloseButton` to `BvToastOptions` type

feat(types): add `noCloseButton` property to `BvToastOptions` type declaration

---

docs/markdown/intro/README.md
docs/markdown/reference/starter-templates/README.md
package.json
scripts/rollup.config.js
src/components/nav/README.md
src/utils/array.js
src/utils/object.js
yarn.lock

This PR removes the default polyfills for:
- `Array.from()`
- `Array. isArray()`
- `Object.assign()`
- `Object.is()`
This should not be a breaking change since our polyfill recommendations in the docs should catch those anyway (for IE 11 and older android)

perf: remove default array/object polyfills

---

src/components/tabs/README.md

fix dynamic tabs example to work with IE 11.

docs(tabs): fix dynamic tabs example to work with IE 11

---

docs/pages/index.vue

docs: animate logo on load

---

src/components/table/README.md

On small screens, some of the examples were too wide causing the page to scale down and slightly break layout.
This PR adds the responsive prop to some of the wider examples.

docs(table): add `responsive="sm"` to some of the wider table examples

---

src/components/carousel/README.md

Docs update for carousel (requested on discord chat)

docs(carousel): document the `content-visible-up` property

---

src/components/carousel/carousel-slide.js
src/components/carousel/carousel-slide.spec.js

Do not render the `carousel-caption` `<div>` if there is no content (caption, text or default slot)
Issue raised on discord chat

fix(carousel-slide): do not render `carousel-caption` wrapper if no content

---

docs/markdown/reference/router-links/README.md

Add link to Vue router API reference. This will help user to know which property they have to set to change the default classes used.

docs(router support): add link to router api reference

---

src/components/tabs/README.md

`nav-item` in `extra (contentless) tab buttons should be a <b-nav-item> or have the class nav-item with a root element of <li> and class nav-item for proper rendering and semantic markup.` mentioned twice. Lets fix it.

chore(docs): remove duplication of "nav-item"

---

src/components/tabs/README.md

chore(docs): remove extra dot

---

src/components/tabs/README.md
src/components/tabs/package.json
src/components/tabs/tabs.js

Adds new slot `tabs-start` for placing extra tab button before the content buttons.
Deprecated the `tabs` slot in favour of the new `tabs-end` slot
Closes #3678

feat(tabs): new named slot `tabs-start` for prepending tab buttons, deprecates `tabs` slot in favour of `tabs-end` (closes #3678)

---

src/components/table/helpers/filter-event.js
src/components/table/table-tbody-row-events.spec.js

fix(b-table): IE11 edge case where custom inputs were not clickable in clickable/sortable cells (fixes #3693)

---

src/directives/popover/README.md
src/mixins/dropdown.js
src/utils/tooltip.class.js

Handles case where tooltip/popover is applied to a dropdown and when dropdown is open the tooltip/popover obscures the menu. Tooltip/popover should hide when menu opens.
Closes #3703 

fix(tooltip, popover): handle case where tooltips are applied to dropdown root elements (closes #3703)

---

src/components/toast/README.md

A few minor updates/fixes to the toast docs

chore(docs): minor updates to toast documentation

---

docs/pages/index.vue

Minor adjustment to docs landing page

chore(docs): minor tweak to landing page

---

src/components/form-textarea/README.md

Add note to `b-form-textarea` docs on auto-height implementation and it's limitations (when initially visually hidden via display: none`).
Closes #3716

chore(docs): add implemetation note on auto-height textarea (closes #3716)

---

src/components/form-file/README.md

Explicitly inform user about the area where a file should be dropped.

chore(docs): inform where a file should be dropped

---

src/components/toast/README.md
src/components/toast/package.json

Toasts have stabilized enough that we can remove the `beta` / `new` status on them

chore(toasts): remove beta status

---

src/components/carousel/carousel.js

Based on https://github.com/twbs/bootstrap/pull/28558

fix(carousel): reset `touchDeltaX` to prevent click transformed in swipe

---

docs/components/search.vue
docs/components/sidebar.vue
docs/layouts/docs.js

Similar to https://github.com/twbs/bootstrap/pull/28361 and https://github.com/twbs/bootstrap/pull/28983

chore(docs): add aria-labels to navigation regions, add role to search region

---

.github/renovate.json
package.json
renovate.json
yarn.lock

This PR prepares the `bootstrap` dependency range in `package.json` for Bootstrap releases before v5 drops.

chore: prepare for new Bootstrap versions

---

docs/markdown/intro/README.md

A few minor fixes to getting started docs

chore(docs): minor fixes to getting started docs

---

docs/markdown/intro/README.md
docs/pages/docs/index.js
docs/utils/index.js

Fix parse version util so that it doesn't match range versions (i.e. so that it doesn't pick bootstrap v5.0.0)
Also adds a few more bits of interpolation for minor version numbers

chore(docs/utils): don't match versions preceded by `<`

---

docs/components/section.js
src/components/table/README.md
src/components/table/package.json

Prevent needless page loads when markdown links are internal site links, by converting clicks on plain `<a href="...">` into `router.push()` (page to page links) or a `scrollIntoView` (for in-page anchor links). External links are left alone for default handling by the browser.

chore(docs): convert clicks on internal docs links to `$router.push()` or `scrollIntoView`

---

CONTRIBUTING.md
README.md
docs/markdown/reference/accessibility/README.md
docs/markdown/reference/utility-classes/README.md
docs/nuxt.config.js
src/components/table/README.md

Note: only converts links generated from markdown formatted links (i.e. `[text](url)`)

chore(docs):  automatically add `rel` and `target` attrs to external links + link formatting

---

src/components/table/helpers/text-selection-active.js

Ignore text selection active state when selection contents are empty (or string of whitespace)
Closes #3757

fix(table): better detection of active text selection during click events (closes #3757)

---

docs/components/section.js

minor tweak to in-page link handling

chore(docs): minor tweak to in-page link handling

---

src/components/modal/helpers/bv-modal.js
src/components/modal/index.d.ts

Moves `msgBox` method out of the Class definition, and renames it `makeMsgBox` (private closure method)
To prevent consumers from using this internal only method and getting confused as to how it works (i.e. https://github.com/bootstrap-vue/bootstrap-vue/issues/3765).
Similar to how `makeToast` is a private closure method in `this.$bvToast`

chore(bv-modal): make `msgBox` method private

---

src/utils/config-defaults.js

Add notes (for future devs) that the global config should not be used to override Boolean prop defaults, as changing a prop that is used only by presence (i.e. `split`, `centered` etc) would loose their semantic context/meaning when used by imported 3rd party components built upon BootstrapVue.

chore(config): add a few comment notes to the default config

---

src/_variables.scss
src/components/popover/_popover.scss
src/components/table/_table.scss
src/components/toast/README.md
src/components/toast/_toast.scss
src/components/tooltip/_tooltip.scss
src/utils/config-defaults.js

Allows users to define the default toast background opacity (background color alpha) via SCSS variable `$b-toast-background-opacity` (extracts the default value from the bootstrap toast background color SCSS variable)
Removes the BV global config for toast `solid` boolean prop (which wasn't used, as Toasts never accessed the config for `solid` default), in favour of the new SCSS variable (as we shouldn't be storing Booleans in the global config).
Cleans up a few BootstrapVue SCSS variable names for consistency (old values are deprecated):
- Flags start with `$bv-` (for enabling/disabling features)
- Variables start with `$b-`
Emits SASS `@warn` messages if using the older variable names
Adds in variable to enable/disable (enabled by default) generation of stacked table CSS
**What kind of …

feat(toast): add SCSS variable for default toast background opacity + standardize a few BootstrapVue SCSS variable names

---

src/components/popover/README.md

Fixes closing tag in popover example

chore(docs): correct end tag in example

---

docs/pages/index.vue

Minor alignment update to b-media, to align vertically for all viewports

chore(docs): minor alignment update to landing page

---

CHANGELOG.md
docs/assets/scss/styles.scss
docs/markdown/reference/accessibility/README.md
src/_variables.scss
src/components/form-select/README.md
src/components/form-textarea/README.md
src/components/modal/README.md
src/components/modal/package.json
src/components/toast/README.md
src/components/toast/_toast.scss
src/components/toast/package.json

A few updates to the Toast and Modal docs.
Adds `BVToastPlugin` and `BVModalPlugin` to the list of plugins included by `ToastPlugin` and `ModalPlugin`, respectively.
Adds additional verbiage to the notes section regarding the plugins.
Adds a note in the Form Select docs re iOS select issue

chore(docs): minor updates to the toast, modal and form-select docs

---

src/components/table/README.md

Minor updates to the table docs.

chore(docs): minor updates and clarification to table docs

---

docs/markdown/reference/theming/README.md
docs/pages/index.vue

A few minor adjustments to docs.
Added additional information to the theming reference section.

feat(docs): update to the theming reference section

---

src/components/index.esm.js
src/components/table/README.md
src/components/table/helpers/constants.js
src/components/table/helpers/default-sort-compare.js
src/components/table/helpers/mixin-busy.js
src/components/table/helpers/mixin-caption.js
src/components/table/helpers/mixin-stacked.js
src/components/table/helpers/mixin-table-renderer.js
src/components/table/index.d.ts
src/components/table/index.js
src/components/table/package.json
src/components/table/table-lite.js
src/components/table/table-simple.js
src/components/table/table-simple.spec.js
src/components/table/table.js

Renders a table element (with optional basic styles), which renders the users content in the default slot.
Provides no items, sorting, etc.  Just purely table styles (except stacked)
Requires users to place their own  `<thead>`, `<tfoot>`, `<tbody>` etc in the default slot.
This provides users the flexibility to create row and col spans as needed
Uses some shared code with b-table, so the extra foot print of this component is very lightweight.

feat(b-table-simple): new `<table>` wrapper component that allows users to render their own `<thead>`, `<tfoot>`, `<body>`

---

docs/markdown/intro/README.md

This PR corrects a typo on the intro page.
Closes #3826.

fix(docs): correct typo on intro page (closes #3826)

---

src/components/table/index.d.ts

Adds missing type declarations for `TableLitePlugin` and `TableSimplePlugin`

chore(types): add types for `TableLitePlugin` and `TableSimplePlugin`

---

src/components/table/README.md

Minor updates to teh table docs

chore(docs): minor updates to table docs

---

docs/markdown/intro/README.md
docs/pages/docs/index.js

Add a link to changelog on intro page

chore(docs): add link to changelog on intro page

---

src/index.js
src/utils/plugins.js

Adds an optional NAME property for plugins, which will be set on the `window` object when using `vueUse` (if `window` exists)
Mainly for the browser bundle build, to add in support for both `window.bootstrapVue` (current) and `window.BootstrapVue`
Closes #3849

chore(plugin): add NAME option to `vueUse` (closes #3849)

---

src/index.js

Removes top level, undocumented, `setConfig` export.
Consumers should only be able to pass a config when `Vue.use(plugin, config)`

chore: remove undocumented `setConfig` top level export

---

src/_variables.scss

This PR removes deprecations from the tooltip and popover styles.

feat(tooltip/popover): remove deprecations

---

src/components/modal/helpers/bv-modal-event.class.js
src/components/modal/helpers/bv-modal-event.class.spec.js
src/components/modal/index.d.ts

Remove the deprecated properties/methods from the `BvModalEvent`.

feat(modal): remove BvModalEvent deprecations

---

src/components/nav/README.md
src/components/nav/nav-item-dropdown.js
src/components/nav/nav.js
src/components/nav/nav.spec.js
src/components/navbar/README.md

This PR removes the deprecations from the `<b-nav>` and `<b-nav-item-dropdown>` components.

feat(b-nav, b-nav-item-dropdown): remove deprecated slot and props

---

src/components/dropdown/dropdown.js
src/components/dropdown/package.json

This PR removes the deprecations from the `<b-dropdown>` component.

feat(b-dropdown): remove deprecated slot `text`

---

src/components/tabs/README.md
src/components/tabs/package.json
src/components/tabs/tab.js
src/components/tabs/tabs.js

This PR removes the deprecations from the `<b-tabs>` and `<b-tab>` components.

feat(tabs): remove deprecations

---

src/components/form-checkbox/README.md
src/components/form-checkbox/form-checkbox.spec.js
src/components/form-file/README.md
src/components/form-group/README.md
src/components/form-input/README.md
src/components/form-input/form-input.spec.js
src/components/form-radio/README.md
src/components/form-radio/form-radio.spec.js
src/components/form-select/README.md
src/components/form-select/form-select.spec.js
src/components/form-textarea/README.md
src/components/form-textarea/form-textarea.spec.js
src/components/form/README.md
src/mixins/form-state.js

For all form control and form repated component that accept the state prop.
remove ability to pass string `'invalid'` or `'valid'` to prop state
Prop now only accepts `true`, `false`, or `null`

feat(b-form-*) remove supplying a string to `state` prop

---

src/components/form/form-invalid-feedback.js
src/components/form/form-invalid-feedback.spec.js
src/components/form/form-valid-feedback.js
src/components/form/form-valid-feedback.spec.js

A few minor cleanups to form-feedback components

chore: minor updates to form feedback components

---

src/components/card/README.md
src/components/nav/README.md
src/components/nav/nav.js
src/components/nav/nav.spec.js
src/components/tabs/tabs.js
src/directives/scrollspy/README.md

Adds in support for placing  `b-nav` in card headers via a new `card-header` boolean prop. When placing in cards, the consumer must wrap in a `<b-card-header>` or place in the `<b-card>` slot `header`.
Has no effect if the nav has the `vertical` prop set.
Automatically applies the correct classes for pills and tabs mode

feat(b-nav): add card header support

---

src/components/table/helpers/mixin-stacked.js

fix(b-table, b-table-lite): render header when not always stacked mode (fixes #3886)

---

src/components/layout/README.md

Adds clarification to `order` and `order-{breakpoint}` section of layout docs

chore(docs): add clarification to `order` and `order-{breakpoint}` section

---

src/directives/toggle/toggle.js

Do not override role on toggle element if it already has an explicit role assigned.
- [] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

fix(v-b-toggle): don't override `role` if element has a `role` assigned

---

src/components/table/helpers/mixin-stacked.js
src/components/table/helpers/mixin-thead.js

A few minor optimization to computations for stacked mode

chore(table): minor code adjustments

---

src/components/progress/README.md

Correct variable typo.
Typo corrections.

chore(docs): fix type in progress example

---

docs/markdown/intro/README.md

This PR I removes a broken Twitter link from the docs.
Closes #3911.

fix(docs): remove broken Twitter link (closes #3911)

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js

Fixes an edge case where user conditionally renders content inside a scoped slot, which was causing the cell to be rendered with the raw value when the slot returned no vNodes. i.e. a `v-if` with no `v-else`:
```html
<template slot="cell[foo]" slot-scope="{ value }">
<template v-if="value !== 0">
{{ value }}
</template>
</template>
```
Fixes #3919

fix(b-table, b-table-lite): handle edge case where field slot returns no vNodes (fixes #3919)

---

src/components/modal/modal.js

When the modal was not in `static` mode, any additional attributes were not rendering on the modal wrapper div (instead they were being applied to the BTransporter component)
This PR ensures that the attributes are always transferred to the wrapper DIV.
Closes #3896.

fix(b-modal): ensure non-prop attributes are transferred to the modal outer wrapper `div` (closes #3896)

---

docs/markdown/reference/images/README.md
docs/plugins/play.js
src/components/button/button.js
src/components/form-group/form-group.js
src/utils/loose-equal.spec.js

chore: fix linting for PR #3913

---

CHANGELOG-OLD.md
CHANGELOG.md

This PR corrects all the typos in the current and old changelog.

fix(changelog): correct typos

---

src/components/toast/toast.js

Portalling typically removes the parent association, which in turn makes scoped styles not work.
This PR ensures that when portalled, the toast has the scoped style data attribute applied to the root element.

feat(toast): add support for scoped styles

---

src/components/breadcrumb/README.md
src/components/list-group/README.md
src/components/navbar/README.md
src/components/pagination-nav/README.md

Adds a link to the router-link reference section for router related props

chore(docs): add links to the router-link reference section to all components that support router-links

---

src/components/modal/README.md
src/components/toast/README.md
src/mixins/normalize-slot.js
src/utils/normalize-slot.js
src/utils/transporter.js

Adds a small section on advanced usage (using `$createElement`) section for modal message boxes.
Toasts already have a similar section. This should hopefully help reduce the number of "how to" issues.
Closes #3982

chore(docs): add an advanced usage section and example for modal message boxes (closes #3982)

---

src/components/table/README.md

Adds notes to the data, header/footer slot sections regarding limitations of slot names when using the new Vue 2.6 `v-slot` syntax (which is less flexible than the now deprecated `slot="name"` syntax)

chore(docs): add notes to table docs on slot name limitations when using `v-slot` syntax

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
src/components/table/README.md
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-thead.js
src/components/table/table-row-details.spec.js
src/components/table/table-tbody-row-events.spec.js
src/components/table/table-tfoot-events.spec.js
src/components/table/table-thead-events.spec.js

Merged dev in to tmorehouse/table-collapse

---

src/components/table/README.md
src/components/table/_table.scss
src/components/table/helpers/mixin-table-renderer.js
src/components/table/table.spec.js

Adds new Boolean prop `no-border-collapse` and associated SCSS.
Mainly for use with sticky header and/or column tables to prevent the header borders from scrolling away as the body scrolls. Defaults to `false`.

feat(table): add `no-border-collapse` prop and SCSS

---

src/components/pagination/pagination.js
src/components/pagination/pagination.spec.js

- If the number of pages changes, and is greater than the current page number, then retain the page number. Otherwise set the current page to 1
- If per-page changes (but total rows remains the same), then always reset to page 1
Closes #3716 

feat(b-pagination): if number of pages changes, try and keep current page active (closes #3716)

---

src/components/dropdown/README.md

Changes duplicate dropdown IDs in examples (found using lighthouse)

chore(docs): remove duplicate IDs from dropdown examples

---

src/components/pagination/pagination.spec.js
src/mixins/pagination.js

Clears up issues with A11Y and pagination components.
Google Lighthouse appears to be happy with just `role="presentation"`
Closes #2921 
Note: https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html#
ARIA Practices 1.1 show them using role `"none"` on the `<li>` elements

chore(pagination): change `role="none presentation"` to `role="presentation"` (closes #2921)

---

src/components/nav/README.md

Adds an example of using `<router-view>`/`<nuxt-child>` when combined with cards
Closes #3999 

docs(b-nav): add example markup for using vue-router/nuxt-child (closes #3999)

---

src/components/modal/modal.js

This PR fixes the order/timing of when `sctollTop = 0` happens,
Closes #4003

fix(b-modal): fix scroll to top issue when modal has `no-fade` set (closes #4003)

---

src/components/card/README.md
src/components/nav/README.md

chore(docs): better ARIA compliant `b-nav` + `b-card` examples

---

docs/markdown/reference/router-links/README.md

Minor updates to the router-link reference docs.
Closes #4012

docs(router-links): add more details to `active-class` and `exact-active-class` props (closes #4012)

---

src/components/table/README.md

A few minor adjustments to the table docs

chore(docs): minor adjustments to the table docs

---

docs/assets/scss/styles.scss

This PR corrects the heading before margin.
When clicking on an heading anchor the page will scroll to the correct position.

fix(docs): heading before margin

---

package.json
yarn.lock

Reverts bootstrap-vue/bootstrap-vue#4026

Revert "chore(deps): update devdependency @nuxtjs/pwa to ^3.0.0-beta.17"

---

src/components/modal/helpers/bv-modal.js
src/components/modal/helpers/modal-manager.js
src/components/modal/modal.js
src/components/pagination-nav/pagination-nav.js
src/components/table/helpers/mixin-provider.js
src/components/toast/toast.js
src/components/tooltip/helpers/bv-tooltip.js
src/mixins/pagination.js
src/utils/transporter.js

chore: coverage fixes for babel dep upgrades

---

src/components/table/package.json

Fies slot names listend in table package.json meta

chore(docs): fix slot names in table package.json

---

docs/nuxt.config.js

Update for new changes in Nuxt PWA version 3.0.0-beta.17

chore(nuxt.config.js): update `manifest` to `pwa.manifest`

---

docs/markdown/reference/validation/README.md

Fixed a dead link to the VeeValidate library

docs(validation): updated VeeValidate link

---

docs/markdown/reference/accessibility/README.md

Adds tips for testing user application for accessibility

docs(accessibility): add sub section on application a11y testing

---

src/components/form-select/README.md

docs(readme): Fixed typo

---

src/components/tooltip/README.md

Closing tag in the first exemple is 'b-popover' instead of 'b-tooltip'
Fix a closing tag in the first exemple of the tooltip documentation page

fix(docs): closing tag in the first example of the tooltip documentation page

---

docs/nuxt.config.js

It appears that the new NuxtJs PWA plugin is not populating the `og:image` tag by default (any more)
Added in config to explicitly enable them

chore(docs): ensure opengraph and twitter meta is provided

---

src/components/tooltip/helpers/bv-tooltip.js

fix(tooltip, popover): check `document.body` instead of `document` for IE11 support (fixes #4074)

---

src/components/popover/helpers/bv-popover-template.js
src/components/tooltip/helpers/bv-tooltip.js
src/directives/popover/README.md
src/directives/popover/popover.js
src/directives/tooltip/README.md
src/directives/tooltip/tooltip.js
src/directives/tooltip/tooltip.spec.js

For directive versions, if no content/title available, then don't show the tooltip or popover.
Handles special case when title/content is the number `0`
Closes #4064 

fix(v-b-tooltip, v-b-popover): don't show if no title/content provided (closes #4064)

---

src/components/table/README.md

There was a minor HTML syntax error in the following example:  "Example: Custom data rendering with scoped slots".

docs: Fix syntax error in table component's README

---

src/components/form-checkbox/README.md

Borrowed the wording from Vue official docs: https://vuejs.org/v2/guide/forms.html#Checkbox-1
Closes #4089

docs(b-form-radio): add note that `unchecked-value` is not submitted via native form submit (closes #4089)

---

src/components/table/README.md

Typo fix in table docs example

chore(docs): fix table example typo

---

src/components/modal/README.md

Fix small typo by removing repeated "the" word.

docs(typo): fix trivial typo

---

src/components/popover/package.json
src/components/popover/popover.js
src/components/tooltip/helpers/bv-tooltip.js
src/components/tooltip/package.json
src/components/tooltip/tooltip.js
src/directives/popover/popover.js
src/directives/tooltip/tooltip.js

Fixes #4131 
Also ensures `boundary-padding` and `offset` are converted to numbers (if passed as strings)

fix(b-popover, b-tooltip): ensure `boundary-padding` is passed to popper instance (fixes #4131)

---

src/components/dropdown/dropdown.spec.js
src/mixins/dropdown.js
src/utils/dom.js
src/utils/dom.spec.js

This PR fixes the `<b-dropdown>` and `<b-nav-item-dropdown>` (when vertical and inline menu is displayed) close handling when focus is lost by clicking an item below, and the item's click handler not firing due to the position of the item moving before the click handler gets a chance to be triggered.
Uses a setTimeout delay to postpone the drop down menu collapse (when in a navbar) when the menu looses focus.
Closes #4113.

fix(dropdown): focus-out handling when new focus comes from another `dropdown-toggle` (closes #4113)

---

src/components/form-checkbox/README.md
src/components/form-file/README.md
src/components/form-input/README.md
src/components/form-radio/README.md
src/components/form-select/README.md
src/components/form-textarea/README.md

Adds additional clarification regarding the `autofocus` prop.

docs: clarify the autofocus prop

---

src/components/table/_table.scss

Disable sticky header table max-height for print media.
Allows the full table to be printed on printers

fix(table): disable sticky header max-height on printers

---

docs/markdown/intro/meta.json
docs/pages/docs/index.js

update meta for getting started page (mainly for SEO)

chore(docs): update meta for getting started page

---

docs/components/componentdoc.vue
src/components/carousel/package.json
src/components/modal/package.json
src/components/nav/package.json
src/components/table/package.json

Adds a version badge to the prop tables to signify which version the prop is available in

docs(componentdoc.vue): add version badge to prop reference table

---

docs/plugins/play.js

Minor performance improvements on v-play directive for live examples.
Only destroy/rebuild example VM instance if there are changes to the content.

chore(docs): improve v-play performance and only recreate instance if changed

---

src/components/card/README.md

chore(docs): remove excess closing tags

---

src/components/carousel/carousel.js

Disable the previous / next controls when the slide is transitioning, to better align with Bootstrap v4's implementation.
Closes #4210

fix(carousel): disable the next/prev controls when the carousel is sliding (closes #4210)

---

docs/markdown/reference/theming/README.md

Minor updates to the theming reference section

chore(docs): minor updates to the theming reference section

---

docs/markdown/intro/README.md
package.json

This PR allows importing the sass index file via
```
@import '~bootstrap';
@import '~bootstrap-vue';
```
This is aligned with the `sass-loader` documentation:
https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
and how Bootstrap enables this feature:
https://github.com/twbs/bootstrap/blob/60559d44a2166708a4dc2f6ccb835052da08ab65/package.json#L74
Hardcoding `node_modules` is not necessary, since Webpack is needed here anyway and the `sass-loader` takes care of the module resolution.
**If adding a new feature, or changing the functionality of an …

chore(core): allow advanced scss import

---

docs/components/quick-links.vue

Minor style tweaks to the page toc quick-links

chore(docs): tweaks to page quick-links styling

---

src/components/dropdown/_dropdown-form.scss

`<b-dropdown-form>` was not being properly styled when placed in a `<b-nav-item-dropdown>`
Fixes #4220

fix(b-dropdown-form): fix SCSS styling when placed in a nav dropdown (fixes #4220)

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/table-sticky-column.spec.js

Improve performance of `<b-table>` and `<b-table lite>` by using native `td`/`th` in table `<tbody>` if the cell is not a sticky column (otherwise use a `b-th`/`b-td` where the instance intelligence is needed to handle cell variants for sticky columns)
This can dramatically reduce the number of Vue instances instantiated for extremely large tables (where overall cell counts are in the 1000's)
Closes #4211
Closes #4155
Might address #4150
Side note: if bootstrap v5 incorporates the proposed cell background inheritance, then our child helper components can be converted to functional components (which will further improve performance and remove the need for injection resolution)
**Does this PR introduce a breaking change?** …

perf(b-table, b-table-lite): improve render performance (closes #4211, #4155)

---

src/components/form-input/README.md

Minor update to `<b-form-input>` docs.  Show using a native HTML5 input

chore(docs): minor update to b-form-input docs

---

src/components/popover/README.md
src/components/tooltip/README.md
src/directives/popover/README.md
src/directives/tooltip/README.md

chore(docs): note about requiring BootstrapVue custom CSS for tooltips/popovers

---

CHANGELOG.md
docs/components/quick-links.vue
docs/markdown/intro/README.md
docs/markdown/reference/theming/README.md
package.json
src/components/card/README.md
src/components/card/index.d.ts
src/components/carousel/carousel.js
src/components/dropdown/_dropdown-form.scss
src/components/form-input/README.md
src/components/navbar/package.json
src/components/popover/README.md
src/components/table/helpers/mixin-tbody-row.js
src/components/table/table-sticky-column.spec.js
src/components/tooltip/README.md
src/directives/popover/README.md
src/directives/tooltip/README.md
yarn.lock

chore: release v2.0.4

---

CHANGELOG.md
docs/markdown/intro/README.md
docs/markdown/reference/theming/README.md

This PR prettifies all files and corrects some typos.

chore: prettify and correct typos

---

CONTRIBUTING.md

This PR makes some minor tweaks to the `CONTRIBUTING.md`.

feat: improve `CONTRIBUTING.md`

---

src/components/dropdown/README.md
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.spec.js
src/components/dropdown/package.json

This PR adds `block` support (similar to `<b-button>`) to the `<b-dropdown>`'s toggle.
TODO:
Closes #4266.

feat(b-dropdown): add `block` support to toggle button (closes #4266)

---

scripts/create-web-types.js
src/directives/popover/package.json
src/directives/scrollspy/package.json
src/directives/tooltip/package.json

Update web-types generation to match schema, improve descriptions on components and fix regular expressions. 

fix(web-types): update web-types code generation to match schema

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/package.json
src/components/table/table-row-details.spec.js

Adds a new prop for applying arbitrary an arbitrary class (or classes) to the details row `<td>`
Example usage would be adding class `p-0`to remove the cell's default padding to allow the content to be flush with the row's edges.

feat(b-table, b-table-lite): add prop `details-td-class` for applying classes to the details row `<td>`

---

src/components/collapse/README.md

Minor correction to v-model example usage for b-collapse

chore(docs): update b-collapse v-model example

---

docs/components/componentdoc.vue
src/components/table/package.json

Some "click" events could either be a MouseEvent or KeybardEvent, so set type to both (for web-types generation)
Also present arguments as ordered list in events reference table (for better accessibility)

chore(table): update event types for native events in package meta

---

docs/markdown/intro/README.md

docs(getting started): add note stating tree shaking only applies to JavaScript and not CSS (closes #4297)

---

src/components/pagination-nav/README.md
src/components/pagination/README.md

chore(docs): fix minor typos

---

src/components/pagination-nav/README.md
src/components/pagination/README.md
src/components/pagination/pagination.spec.js
src/mixins/pagination.js

Add <kbd>UP</kbd> and <kbd>DOWN</kbd> keyboard navigation support (for JAWS)
JAWS appears to announce keyboard navigation as vertical (instead of horizontal) for some reason with pagination. This PR adds in up/down arrow support.
Fixes #4322

fix(b-pagination, b-pagination-nav): add UP/DOWN keyboard navigation support for JAWS (fixes #4322)

---

src/directives/visible/README.md

This PR fixes the `once` and `once` with `offset` examples for the `v-b-visible` directive docs.

docs: fix visible directive examples

---

docs/pages/play.vue
docs/plugins/docs-mixin.js

Fixes eslint warning in docs, resulting from the latest eslint-plugin-vue update

chore(docs): fix eslint warnings

---

src/components/tabs/README.md

This PR fixes the `<b-tabs>` lazy examples.

chore(docs): update tabs lazy examples

---

src/components/modal/README.md
src/directives/modal/modal.js
src/directives/modal/modal.spec.js

Ensure that trigger element is accessible if not a link or button

fix(v-b-modal): ensure trigger element is keyboard accessible if not a link or button, for A11Y

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-tbody.js
src/components/table/tbody.js

When `<tbody>` is rendered as a `<transition-group>`, use `nativeOn` for delegated row events.
Ensure that a unique key is generated if the primary key field returns null, undefined or an empty string.
Also use the `get` utility to allow primary key to be a nested item field instead of just a top level field
Also fixes an issue when primary key supplied and row event handlers returned the wrong item reference
Fixes #4370

fix(b-table, b-table-lite, b-tbody): fix delegated event handlers when transition + minor adjustment to row `key` generation (fixes #4370)

---

src/mixins/form-options.js

This PR adds support for paths for the `valueField`, `textField`, `htmlField` and `disabledField` props.
Closes #4385.

feat(b-form-select): support paths for `valueField`, `textField`, `htmlField` and `disabledField` props

---

src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-tbody.js
src/components/table/helpers/mixin-thead.js
src/components/table/table-lite.js
src/components/table/table.js
src/mixins/has-listener.js

Create a mixin for determining if a custom event listener is registered on a component.
Handles both `v-on:event-name="handler"` and `vm.$on('event-name', handler)` cases (`this.$listeners` does not include the latter)
Related to: https://github.com/vuejs/vue/issues/10825

chore: create hasListener mixin

---

src/components/form-input/README.md

docs(form-input): fix prop name typo

---

src/components/popover/README.md
src/components/tooltip/README.md
src/directives/popover/README.md
src/directives/tooltip/README.md

Minor update to positioning examples

chore(docs): minor updates to tooltip/popover docs

---

docs/components/componentdoc.vue

Probably it was meant to be "vulnerable" not "vulerable".

chore(docs): fix typo in compontendoc.vue.

---

src/components/toast/toast.js

The method call was missing it's parenthesis.

fix(b-toast): fix ensureToaster method call when toaster name changes

---

src/components/toast/README.md

chore(docs): fix typo in toast

---

src/components/modal/README.md

Updated ok-only text formatting so that it is clear that it is a property, consistent with other modal props in the doc.

fix(docs): correct formatting of <b-modal> `ok-only` prop

---

src/components/table/README.md

Corrected typo in sticky header section from "pop" to "prop"

chore(table): correct typo in the sticky header section

---

docs/components/icons-table.vue

Adds attribute `autocomplete="off"` to the icon search widget text input.

chore(docs): disable autocomplete on the icons search field

---

src/icons/README.md

Minor updates to the icons docs.

chore(docs): minor updates to the icons docs

---

docs/pages/index.vue

Use new icons components on landing page where possible

chore(docs): use icons on landing page

---

src/utils/get.js
src/utils/normalize-slot.js

This PR corrects a spelling error for some `identity` util imports.

fix(utils): correct `identity` spelling error

---

docs/markdown/reference/validation/README.md

This PR improves the form validation examples in the docs reference section by adding live examples.
It also includes a new example form VeeValidate v3.
Closes #4550.

feat(docs): improve form validation examples (closes #4550)

---

src/components/form-tags/README.md

Adds an example of making a multi-select style tagged input using b-dropdown
Addresses https://github.com/bootstrap-vue/bootstrap-vue/issues/1794

chore(docs): add example of using dropdown in form-tags custom rendering (closes #1794)

---

.github/stale.yml

Configuration for the bot that marks and closes stale issues and pull requests.
https://probot.github.io/apps/stale/

chore: add configuration for the "Stale" GitHub app

---

src/components/modal/README.md

Minor update to the modal prevent closing example.

docs(modal): update modal prevent closing example

---

nuxt/index.js

Remove two unnecessary export statements from nuxt module, which were causing issues for some users.
Release target: **`v2.2.2`**
Bug reported via Discord channel and stackoverflow

fix(nuxt module): remove unnecessary export statements

---

docs/markdown/reference/color-variants/README.md

Consistent capitalisation in documentation for colour variants.

chore(docs): Fix variant text capitalisation

---

CHANGELOG.md
package.json

chore: bump version to 2.2.2 and update changelog

---

CHANGELOG.md
docs/markdown/reference/color-variants/README.md
nuxt/index.js
package.json
src/components/form-tags/README.md
yarn.lock

Maintenance/fix release
- nuxt module: remove unnecessary export statements (#4624)
- dev dependency updates

chore: release v2.2.2

---

docs/components/footer.vue
docs/nuxt.config.js

Add link to Netlify for deploy previews to comply with netlify OpenSource plan policy: https://www.netlify.com/legal/open-source-policy/

chore(docs): link to netlify

---

src/components/pagination/pagination.spec.js
src/mixins/pagination.js

Tweaks to PR #4622 for better aria handling of buttons.
To do:

chore(pagination): tweaks to pagination PR #4622

---

src/components/table/README.md

chore(docs): mention in table docs that `fixed` and `responsive` do not work well with each other (closes #4598)

---

src/icons/README.md

Add missing `</b-icon>` close tags in the BootstrapVue Icon docs.

fix(docs): add missing close tags for `<b-icon>` components

---

src/components/form-input/README.md
src/components/form-textarea/README.md
src/mixins/form-text.js

This PR brings back the changes from #3172 in a better way.
They were accidentally removed in #4169.
Closes #4695.

fix(b-form-input, b-form-textarea): properly handle out-of-sync values (closes #4695)

---

src/components/modal/README.md

Adds a bit more clarification re usage of the new `ignore-enforce-focus-selector` prop, just to help prevent usage question issues.

chore(docs): minor update to modal docs re TinyMCE

---

README.md

It appears that packagequality.com is down or dead... so commenting out for now on main repo README.md

chore(readme): comment out package quality link as it is broken

---

src/utils/bv-hover-swap.js
src/utils/bv-hover-swap.spec.js
src/utils/bv-transition.js

A private utility component for swapping content based on hover/unhover
For use in the BFormDate and BFormTime components (and potentially other future components) to swap icons when hovered
If prop `parent` is set, monitors hover state of the parent element (not component) instead of itself.
Default slot is the unhovered render, while slot `hovered` renders when the component is hovered

chore: create BVHoverSwap utility helper component

---

src/utils/events.js

This PR correct the `capture` value of `EVENT_OPTIONS_NO_CAPTURE` from `true` to `false`.

fix(events): correct `capture` value of `EVENT_OPTIONS_NO_CAPTURE`

---

scripts/build.sh

properly ignore `src/browser.js` and `src/browser-icons.js` files when transpiling to the esm module build directory

chore: properly ignore `browser.js` and browser-icons.js` during esm modular build

---

src/components/modal/modal.js

Minor adjustments to the modal show enter transition timing
Closes #4761

fix(b-modal): transition timing (closes #4761)

---

src/components/popover/README.md
src/components/tooltip/README.md
src/directives/popover/README.md
src/directives/tooltip/README.md

docs(popovers, tooltips): add info about focus only trigger and cross platform behaviour

---

src/components/button/button.js
src/components/button/button.spec.js
src/components/link/link.js

Adds role = button when href is `#`, and add the appropriate keydown (SPACE/ENTER) handlers for accessibility.

fix(b-button): when `href` is "#" add `role=button` and appropriate keydown handlers for A11Y

---

src/components/button/README.md

Adds an accessibility section to the `<b-button>` docs.

docs(b-button): add accessibility section

---

src/components/modal/modal.js

Minor adjustments to the modal show transition behaviour
Closes #4761

fix(b-modal): additional fixes for show transition behaviour (closes #4761)

---

src/components/form-spinbutton/form-spinbutton.js
src/components/form-spinbutton/package.json

Adds two missing props to b-form-spinbutton.
Also ensure mouse events listen for left (or main) mouse button only (i.e. ignore right or middle clicks)
Setting PR as a `chore` since b-form-spinbutton has not been released

chore(b-form-spinbutton): add two missing props

---

src/components/form-tags/package.json

removes the new flag from the package meta for b-form-tags

chore(b-form-tags): remove new tag from package.json meta

---

docs/components/anchored-heading.js
docs/nuxt.config.js

Improves the accessibility of anchored links.
Previously when tabbing into a heading `'#'` link, no context was given to screen reader users as to what the link destination is.

docs: improve anchored heading accessibility

---

src/components/tooltip/README.md

Fixed a mistake in the js code example.
The tooltip directive documentation had a mistake in the example where it showed how to hide a tooltip.
```
this.$root.$emit('bv::show::tooltip', 'my-trigger-button-id')
```
should have been
```
this.$root.$emit('bv::hide::tooltip', 'my-trigger-button-id')
```

fix(docs): error in tooltips directive example

---

src/components/form-datepicker/form-datepicker.js

Minor code optimizations for `b-form-datepicker`, which should improve minification

chore(b-datepicker): minor code optimizations for better minification

---

src/components/form/README.md

Adds links to the new form controls in the /docs/components/form page

docs: add links to new inputs in form docs

---

docs/components/contributors-container.js
docs/components/contributors.vue

Adjusts the algorithm for processing the backers section, to make sure backers who started before the tiers were set up are shown.
Also only links to donors website once a certain donation threshold is reached, to prevent questionable sites from getting cheap backlinks to their webpage.

chore(docs): tweak backers/donors

---

package.json
src/components/calendar/package.json
src/components/form-datepicker/package.json
src/components/form-spinbutton/package.json
src/icons/package.json

chore: minor tweaks to docs for SEO, etc.

---

src/components/form-tags/README.md
src/components/form/README.md
src/components/pagination-nav/README.md
src/components/pagination-nav/pagination-nav.spec.js
src/components/pagination/pagination.js
src/components/pagination/pagination.spec.js
src/mixins/pagination.js

Accessibility improvements to `b-pagination-nav` and `b-pagination`.
Switches roles and tabindexes when rendered as `<b-pagination-nav>`. `<b-pagination-nav>` pages are now rendered as regular links, compared to `role=menuitemradio` buttons used in `<b-pagination>`.
`<b-pagination-nav>` no longer supports left/right/up/down arrow key navigation, and falls back to regular browser <kbd>TAB</kbd> navigation, as would be expected for regular links
`<b-pagination>` now renders `<button>` elements instead of `<a href="#">` links.
Updates were tested using NVDA and ChromeVox screen readers
Closes: #4811
Closes: #4160
**If new …

feat(b-pagination, b-pagination-nav): improve aria accessibility (closes: #4811, #4160)

---

src/components/tabs/package.json
src/components/tabs/tab.js
src/components/tabs/tabs.js

I need somehow to assign custom attributes to the rendered button.
Closes: #4803
Issue: #4803

feat(b-tabs): add ability to provide custom tab button attributes (closes: #4803)

---

src/components/calendar/_calendar.scss
src/components/calendar/calendar.js
src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json

Adds prop `calendar-width` to `<b-form-datepicker>` to set the `width` on the calendar dropdown
Also adds class `text-truncate` to the weekday headings to prevent the row from wrapping, and adds a `min-width` in the CSS
Closes #4817

feat(b-form-datepicker): add calendar-width prop (closes #4817)

---

src/components/calendar/calendar.js
src/components/form-datepicker/form-datepicker.js

This PR adds `tabindex="-1"` to the dropdown menu to work around focus issues for Firefox and Safari on MacOS.
Closes #4814.

fix(b-form-datepicker): menu focus handling for Firefox and Safari on MacOS (closes #4814)

---

docs/components/componentdoc.vue

chore(docs): componentdoc - allow object prop defaults to wrap

---

src/components/form/README.md

This PR ensures that we always use the array format for `<b-form-select>` options.
Otherwise a deprecation warning is shown in the console.

docs: always use array format for `<b-form-select>` options

---

src/components/form-spinbutton/form-spinbutton.js

Since we need to preventDefault, we can't use passive in this instance
Fixes a browser warning/error from PR #4842 

chore(b-form-spinbutton): don't use pasive mode for mouseup/touchend

---

src/components/collapse/package.json

Corrects typo in documentation

chore(docs): Fix typo `bart` -> `part`

---

src/components/form-datepicker/form-datepicker.js

Minor test fix to prevent console warnings

chore(b-form-datepicker): fix typecheck during tests

---

src/components/popover/README.md
src/components/tooltip/README.md
src/directives/popover/README.md
src/directives/tooltip/README.md

Adds live examples of all tooltip/popover positioning options
Closes #4877

chore(docs): show live examples of all positioning for tooltip and popover directives (closes #4877)

---

src/components/form-spinbutton/form-spinbutton.js

Respect the step value when decrementing.
Closes #4884

fix(b-form-spinbutton): respect step value for initial decrement when `wrap` enabled (closes #4884)

---

src/components/calendar/README.md
src/components/form-datepicker/README.md

Make sure props are kebab-case, not camelCase

docs(b-calendar, b-form-datepicker): fix mistake in date formatting examples

---

src/components/calendar/README.md

chore(docs): fix typo in README

---

src/components/calendar/README.md
src/components/carousel/README.md
src/components/collapse/README.md
src/components/form-timepicker/package.json
src/components/modal/README.md
src/components/popover/README.md
src/components/progress/README.md
src/components/tooltip/README.md

docs(a11y): add references to reduced motion for certain component animations

---

docs/pages/play.vue

Minor CSS adjustment for playground carbon ad to reserve space for the ad, and prevent the lead paragraph from changing size once ad loads

chore(docs): minor CSS tweak for playground

---

src/components/form-spinbutton/package.json

Minor fixes to the form-spnbutton meta json data

docs: minor fixes to form-spinbutton meta json

---

src/components/form-file/form-file.js

fix(b-form-file): fix value prop validation when using directory mode (fixes #4912)

---

docs/markdown/misc/third-party/README.md
docs/markdown/reference/color-variants/README.md
src/components/overlay/README.md
src/components/overlay/package.json

Adds a few use case examples to b-overlay docs, which should give users ideas on how to use it, and reduce the number of "how do I..." issues on github.

docs(b-overlay): add additional usage examples

---

docs/components/header.vue
docs/nuxt.config.js

Better version dropdown content via use of Netlify EVN vars (https://docs.netlify.com/configure-builds/environment-variables/#read-only-variables)

docs: better PR detection for docs header

---

src/components/list-group/README.md

The current "utilities classes" link points to Bootstrap 4.0.

docs(list-group): update utility classes link to 4.4

---

src/components/overlay/README.md

Adds a note on usage in b-modal to obscure the entire modal.

chore(b-overlay): add notes on using in `<b-modal>`

---

src/components/form-file/form-file.js

This PR adds the hole reset handling for the file input into a try/catch block.
Closes #4837.

fix(b-form-file): make sure to catch all errors when resetting the input (closes #4837)

---

src/_variables.scss
src/icons/README.md
src/icons/_icons.scss
src/icons/helpers/icon-base.js

Additional tweaks to the animations introduced in PR #4934
Allows for stacked icons to individually animate by targeting the first `g` (child icons only).
Added in `cylon-vertical` animation, `spin-reverse` (counter clockwise), and renames `pulse` to `spin-pulse` for clarity (and adds `spin-reverse-pulse`)
Note: IE 11 does not support animating child elements of SVGs. For IE 11, only the b-iconstack can be animated.

chore(icons): updates to CSS animations

---

README.md

chore(readme): packagequality is back online now

---

CODE_OF_CONDUCT.md
README.md
src/components/breadcrumb/README.md
src/components/dropdown/README.md
src/components/form-file/README.md
src/components/form-file/form-file.js
src/components/form-group/README.md
src/components/table/README.md
src/components/toast/README.md
src/utils/observe-dom.js

This PR makes sure we use `https://` for links wherever possible.

chore: use `https://` for links wherever possible

---

scripts/create-icons.js
yarn.lock

This PR regenerates the `yarn.lock` file and ensures a trailing new line is added to icons `package.json` when it get's generated.

chore: regen `yarn.lock` and ensure new line in icons `package.json`

---

docs/content/index.js
docs/markdown/intro/README.md
docs/pages/docs/index.js

Adds the recommended version of Popper.js to getting started docs
https://deploy-preview-4954--bootstrap-vue.netlify.com/docs/

chore(docs): add popper version to getting started

---

src/components/overlay/README.md

Fix a typo on the overlay component documentation specifically the accessibility section.

chore(docs): fix typo in b-overlay docs

---

src/components/calendar/calendar.js
src/components/form-datepicker/form-datepicker.js
src/components/form-timepicker/form-timepicker.js

- Uses the new double chevron icon for prev/next year buttons
- Adjust icon size in b-form-datepicker and b-form-timepicker

chore(b-calendar): use new double chevron icons

---

src/components/overlay/README.md

Adds an example for usage of the `no-center` prop.
Added due to a question/comment from twitter

docs(b-overlay): add no-center example

---

src/components/avatar/avatar.js
src/components/avatar/package.json

feat(b-avatar): add `alt` prop for adding alt attribute to image and icon avatars (closes #4990)

---

docs/pages/index.vue

Use the puzzle piece icon for the modular card

chore(docs): minor update to homepage icons

---

src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json
src/components/form-timepicker/form-timepicker.js
src/components/form-timepicker/package.json

Emit the `shown` and `hidden` events when the date/time pickers open/close

feat(b-form-datepicker, b-form-timepicker): emit `shown` and `hidden` events

---

src/components/form-datepicker/README.md

Minor adjustments to datepicker button only example

chore(docs): fix a few minor issues with some examples

---

.github/ISSUE_TEMPLATE/DOCS_ISSUE_TEMPLATE.md
docs/components/feedback.js

Update the `report issue` button link in the docs to use the docs issue template

chore(docs): use docs issue template when reporting docs issue

---

src/components/aspect/README.md
src/components/aspect/aspect.js
src/components/aspect/aspect.spec.js
src/components/aspect/index.d.ts
src/components/aspect/index.js
src/components/aspect/package.json
src/components/embed/README.md
src/components/form-spinbutton/README.md
src/components/form-spinbutton/package.json
src/components/index.d.ts
src/components/index.js
src/index.js

New component `<b-aspect>` for maintaining arbitrary aspect ratios for content.
Would be handy for content inside of `<b-carousel-slide>` (via the `img` slot), and other uses where the shape of content should remain the same.

feat(b-aspect): new custom component `<b-aspect>`

---

src/components/avatar/avatar.js

Removes duplicated button variant when rendering a button avatar

fix(b-avatar): remove duplicate button variant class

---

docs/components/header.vue

Update the URL used for the dev docs
> A reminder that starting April 14, 2020, sites without a custom domain are being moved from `your-site.netlify.com` to `your-site.netlify.app`. New websites will also have URLs ending with netlify.app, unless you specify a custom domain.

chore(docs): update dev docs url to `bootstrap-vue.netlify.app`

---

src/components/sidebar/README.md

Minor update to the sidebar docs

chore(docs): minor update to the sidebar docs

---

src/components/avatar/README.md
src/components/avatar/avatar.js
src/components/avatar/avatar.spec.js
src/components/avatar/package.json

Reverts bootstrap-vue/bootstrap-vue#5064
Wait for release 2.11.0, as we need to release 2.10.1 patch version

Revert "feat(b-avatar): if img `src` fails to load, show icon or text or fallback icon"

---

src/components/avatar/_avatar.scss

Remove the default padding when in button mode, which was causing image avatars to get distorted aspects an inconsistent border padding.
Fixes #5073

fix(b-avatar): remove default padding when in button mode (fixes #5073)

---

src/components/form-datepicker/README.md

Expands the button only example to show optional use of context event

chore(docs): expand button-only example to show use of context event

---

yarn.lock

This PR regenerate the `yarn.lock` file to fix potential security vulnerability.

chore: regenerate `yarn.lock` to fix potential security vulnerability

---

src/components/tooltip/helpers/bv-tooltip.js

Ensures that the trigger element gains focus when clicked.
iOS webkit does not focus an element when it is clicked (touched) (https://bugs.webkit.org/show_bug.cgi?id=22261)
Fixes #5099

fi(tooltip/popover): handle `click blur` on iOS webkit browsers (fixes #5099)

---

docs/components/header.vue
src/components/card/README.md
src/components/tabs/README.md

Add aria roles to contentless tabs examples

chore(docs): update tabs docs examples for additional ARIA markup

---

src/components/link/link.js

When provided a `router-tag` of anything other than '`a'` or `'area'`, do not render the `rel` or `target` attributes

fix(b-link): don't render `target` or `rel` attrs when `router-tag` other than `a` or `area` provided

---

src/directives/hover/README.md

This pull request simply contains 2 grammar fixes for the Hover directive in the documentation.

docs: fixed documentation typos for Hover directive

---

src/components/form-file/form-file.js
src/components/form-file/form-file.spec.js

chore(b-form-file): additional unit tests

---

src/components/layout/README.md

Minor tweak to the layout and grid docs

chore(docs): minor tweaks to the layout and grid docs

---

src/components/form-rating/_form-rating.scss

remove the focus outlines on stars when clicking (due to `tabindex="-1"`)

chore(b-form-rating): remove focus outline from icons

---

src/components/calendar/package.json
src/components/form-datepicker/package.json
src/components/form-timepicker/package.json
src/components/overlay/package.json
src/components/time/package.json

Removes the new tag from some components that are not so new anymore

chore(docs): remove new tags from things that aren't so new any more

---

src/mixins/form-options.js

Handle edge case where null or other falsey non array/plain object is passed to the `options` prop, and fallback to an empty array.

chore(form-options-mixin): handle edge case where null/falsey passed to options prop

---

src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json

Adds `date-info-fn` pass-through prop which is provided to the child b-calendar component
Closes #4826

feat(b-form-datepicker): add pass through prop `date-info-fn` (closes #4826)

---

src/components/avatar/README.md
src/components/avatar/avatar.js

When variant is an empty string, remove the spacing around image avatars.
Closes #5154
To Do:

feat(b-avatar): if variant is empty string, then remove spacing around image (closes #5154)

---

.github/workflows/test.yml

This PR ensures we set the `CI_BRANCH_BASE` env variable for BundleWatch to pick up the correct compare branch.

chore: set `CI_BRANCH_BASE` for BundleWatch to pick up the correct compare branch

---

src/components/alert/alert.js

This PR fixes a memory leak in `b-alert` since we used `clearInterval()` to clear the countdown timout.

fix(b-alert): memory leak by using the correct method to clear the countdown timeout

---

src/components/form-datepicker/form-datepicker.js

`no-highlight-today` prop was not being passed to `b-calendar`, so it wasn't being set.

fix(b-form-datepicker): make datepicker respect `no-highlight-today` prop

---

src/components/avatar/_avatar.scss

Bootstrap v4 buttons do not inherit font size.  This fix adds in that CSS rule.

fix(b-avatar): fix button type font size inheritance

---

docs/components/footer.vue
docs/components/header.vue
docs/nuxt.config.js

Additional ENV var tests for detecting deployment of Zeit Now previews
To Do:
Possible future change:
- conditionally render the `CNAME` static file only for master builds
https://medium.com/ax2-inc/use-nuxts-build-templates-property-to-contextually-generate-files-587761251f78
- Also similar: generating robots.txt file that denies search engines on dev docs and deploy previews

chore(docs): handle Zeit Now deploy previews

---

src/components/calendar/README.md
src/components/calendar/calendar.js
src/components/calendar/package.json
src/components/form-datepicker/README.md
src/components/form-datepicker/form-datepicker.js
src/components/form-datepicker/package.json

Add prop `weekday-header-format` to control length of formatted weekday header. Default is `'short'` (current behaviour), and can be set to `'long'` (full weekday name), `'short'` (typically a 3 letter abbreviation), and `'narrow'` (typically the first letter of the weekday name).
Note that some locales may not respect this setting (i.e `'ar'` or `'fa'`, always shows the full weekday name when `'short'` is selected, but do show a single character when `'narrow'` is used)
Closes #5171
To Do:
**If adding a new feature, or changing the functionality of an existing …

feat(b-calendar, b-form-datepicker): add prop `weekday-header-format` to specify weekday header length (closes #5171)

---

src/components/calendar/calendar.js

For the date "buttons", switch to `Intl.NumberFormat` instead of `Intl.DateTimeFormat` to get rid of extra (redundant) symbol chars in some locales (such as `'zh'`)
Closes #5171

fix(b-calendar): use `Intl.NumberFormat`  for formatting the number in the date buttons (closes #5171)

---

.eslintignore
.github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
.gitignore
.prettierignore
CHANGELOG-OLD.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/components/header.vue
docs/markdown/reference/starter-templates/README.md
docs/nuxt.config.js
docs/static/CNAME
package.json
scripts/icons.scss
scripts/index.scss
src/utils/plugins.js

This PR makes all required adjustments to migrate to our new domain https://bootstrap-vue.org/.

chore: migrate to new domain

---

.github/workflows/test.yml
README.md
docs/assets/scss/styles.scss

This PR improves the cache handling of our GitHub Actions.

chore: improve CI workflow

---

src/components/sidebar/sidebar.js

Ensures that the tab traps are not in document sequence when the sidebar is closed when new backdrop feature is used

chore(b-sidebar): only render the tab traps when the sidebar is open

---

src/components/form-rating/README.md
src/components/form-rating/package.json

Minor update to the b-form-rating docs

chore(docs): minor tweaks to the b-form-rating docs

---

.github/workflows/test.yml

This PR removes the redundant `docs` publish workflow.

chore: remove redundant `docs` workflow

---

docs/constants.js
docs/layouts/default.js
docs/layouts/docs.js

Adds the canonical URL link tag, as well as Google Webmaster site verification meta tag codes to the head section

chore(docs): add head meta and link tags to master branch

---

docs/constants.js
docs/layouts/default.js

For old dev site bootstrap-vue.netlify.app

chore: additional GWT site verification

---

src/components/form/README.md
src/components/input-group/README.md

Minor updates to the form docs

chore(docs): minor adjustments to the form docs

---

src/_custom-controls.scss

Prevents duplicate validation icons on b-form-datepicker and b-form-timepicker by making selectors have more specificity
Fixes #5237

fix(b-form-datepicker, b-form-timepicker): prevent duplicate validation icons (fixes #5237)

---

src/components/input-group/README.md

minor update to input-group docs

chore(docs): minor update to input-group docs

---

src/utils/date.js
src/utils/date.spec.js

Allows an inputted `YYYY-MM-DD` string to have (an ignored) time value at the end.
Supports:
- `2000-01-02`
- `2000-01-02 03:04:05` 
- `2000-01-02T03:04:05.678Z` (ISO Date String)
- `2000-01-02 Trailing Garbage`
In all cases, only the date portion of the string is extracted, with the remainder ignored.
Closes #5232

feat(b-calendar, b-form-datepicker): relax `YYYY-MM-DD` string parsing (closes #5232)

---

docs/components/componentdoc.vue
src/components/media/README.md
src/components/table/package.json

Fixes the b-media example so that it will fit on a small screen.
Adds a bottom margin (on smaller screens only) on the functional component badge (otherwise it is too close to the View Source button)

chore(docs): minor tweaks for mobile friendliness

---

.eslintignore
.gitignore
.prettierignore
now.json

This PR overwrite the default `X-Robots-Tag: noindex` header for Vercel now deployments.

chore: overwrite Vercel now default headers

---

src/components/form-select/helpers/mixin-options.js
src/mixins/form-options.js

This PR ensure that nested form options get normalized like the "root" options are.
Closes #5245.

fix: handle nested form options normalization (closes #5245)

---

src/_custom-controls.scss
src/components/form-datepicker/form-datepicker.spec.js
src/components/form-timepicker/form-timepicker.spec.js
src/utils/bv-form-btn-label-control.js

Corrects the SCSS menu padding for button only mode for `b-form-datepicker` and `b-form-timepicker`
Fixes #5251

fix(b-form-datepicker, b-form-timepicker): fix menu padding in button only mode (fixes #5251)

---

src/components/table/tbody.js
src/components/table/td.js
src/components/table/tfoot.js
src/components/table/th.js
src/components/table/thead.js
src/components/table/tr.js

Handle case where sticky column does not preserve `head-variant` (or `foot-variant`)
Fixes #5278 
Also increases covered line/branches due to removal of old istanbul ignores

fix(b-table, b-table-lite, b-table-simple): handle header variant for sticky columns (fixes #5278)

---

src/components/table/README.md

Adds an example of using async/await with provider functions
Closes #4849

chore: show example of `b-table` provider `async/await` (closes #4849)

---

tests/components/TransitionGroupStub.js
tests/components/TransitionStub.js

Ignore test utils stub components for coverage

chore: ignore test utils/stub components for coverage

---

src/components/layout/README.md
src/components/layout/package.json

Documents all values for alignment (horizontal and vertical).
Closes #5332

chore(docs): update grid layout docs (closes #5332)

---

src/components/input-group/README.md

This PR fixes a broken link in the docs.

chore(docs): fix broken link

---

src/components/button-toolbar/button-toolbar.js
src/components/calendar/calendar.js
src/components/carousel/carousel.js
src/components/form-datepicker/form-datepicker.js
src/components/form-group/form-group.js
src/components/form-input/form-input.js
src/components/form-rating/form-rating.js
src/components/form-select/form-select.js
src/components/form-spinbutton/form-spinbutton.js
src/components/form-tags/form-tags.js
src/components/form-timepicker/form-timepicker.js
src/components/link/link.js
src/components/modal/modal.js
src/components/pagination-nav/pagination-nav.js
src/components/pagination/pagination.js
src/components/sidebar/sidebar.js
src/components/table/helpers/mixin-tbody.js
src/components/tabs/tabs.js
src/components/time/time.js
src/components/tooltip/helpers/bv-tooltip.js
src/mixins/dropdown.js
src/mixins/form-radio-check.js
src/mixins/form-text.js
src/mixins/form.js
src/mixins/pagination.js
src/utils/bv-form-btn-label-control.js
src/utils/dom.js

This PR adds the following new DOM utils for focus and blur handling:
- `getActiveElement()` - Get the currently active HTML element
- `isActiveElement()` - Determine if an HTML element is the currently active element
- `attemptFocus()` - Attempt to focus an element
- `attemptBlur()` - Attempt to blur an element

chore(utils/dom): add new utils for focus/blur handling

---

docs/nuxt.config.js

Updates docs config to handle new features of sitemap module

chore(docs): update sitemap module config

---

src/components/collapse/README.md
src/directives/toggle/README.md

Updates the accordion example in the collapse docs to not set `href="#"` on the toggle buttons,
as `v-b-toggle` directive now checks to see if `evt.defaultPrevented` is true before dispatching the toggle event. `<b-link>` (which is the base building block for `<b-button>`) does call `evt.preventDefault()` when `href="#"` to prevent the browser from scrolling to the top of the page.
Closes #5352
To Do:

chore(docs): fix collapse accordion example to not use `href="#"` on buttons (closes #5352)

---

docs/common-props.json
docs/components/header.vue
docs/markdown/reference/router-links/README.md
src/components/avatar/avatar.js
src/components/link/link.js
src/components/pagination-nav/README.md
src/components/pagination-nav/pagination-nav.js

This PR adds support for `<nuxt-link>`'s `prefetch` property.
Closes #5187.

feat: support `<nuxt-link>`'s `prefetch` property (closes #5125)

---

docs/common-props.json
docs/markdown/reference/router-links/README.md
src/components/badge/badge.js
src/components/breadcrumb/breadcrumb-link.js
src/components/button/button.js
src/components/dropdown/dropdown-item.js
src/components/link/link.js
src/components/list-group/list-group-item.js
src/components/nav/nav-item.js
src/components/navbar/navbar-brand.js

Vue coerces Boolean props to be `false` when the default is `undefined`.
This tweaks the BLink prop to default to `null`, and coerces it to `undefined` when passing it to `<nuxt-link>`
Also adds the `"version"` property to the common props meta json file.
This is an augment to PR #5355

fix(b-link): default new `<nuxt-link>` prop `prefetch` to `null` for true tri-state prop

---

src/components/calendar/index.d.ts
src/components/time/index.d.ts

Adds declarations for Calendar and Time context event objects
Closes #5366 

feat(types): create declarations for `<b-calendar>` and `<b-time>` context event objects (closes #5366)

---

.codesandbox/ci.json
docs/pages/play.vue

This PR fixes the CodeSandbox export on the Playground and the template to use for CI deployments.

chore: fix CodeSandbox export from playground and CI template

---

src/components/navbar/navbar-toggle.js
src/components/navbar/navbar-toggle.spec.js
src/components/navbar/package.json

Adds a `disabled` prop to `<b-navbar-toggle>`

feat(b-navbar-toggle): add `disabled` prop

---

package.json
yarn.lock

This PR bumps the suggested Bootstrap version to v4.5.
TODO:

feat: update Bootstrap to v4.5

---

docs/markdown/reference/validation/README.md

chore(docs): updated VeeValidate v3 documentation url

---

.bundlewatch.config.json

Bootstrap Icons 1.0.0.alpha4 has introduced many new icons which has increased bundle sizes

chore: bump bundlewatch thresholds due to new icons

---

README.md

Change Bootstrap v4.3.x to 4.5.x in README (since v2.15 Bootstrap-Vue supports Bootstrap v4.5)

chore(docs): Change Bootstrap v4.3.x to 4.5.x in README

---

src/components/sidebar/README.md

Fixes a typo in the Sidebar README (fixes #5494)

chore(docs): fix typo in sidebar README (fixes #5494)

---

package.json

Since `lint-staged v10` modified files are automatically added to the `git commit index`.

chore: update auto format config

---

yarn.lock

This PR regenerates `yarn.lock`.

chore: regenerate `yarn.lock`

---

src/components/form-tags/form-tags.spec.js

This PR fixes a failing unit test for `<b-form-tags>`.

fix(b-form-tags): unit test

---

README.md

This PR replaces the `packagequality` badge with `codacy` in the README.

chore: replace `packagequality` badge with `codacy` in README

---

yarn.lock

This PR updates `yarn.lock` fo fix security issues.

chore: update `yarn.lock`

---

src/components/card/README.md

chore(docs): fix typo in card docs

---

src/components/dropdown/dropdown-item.js
src/components/dropdown/dropdown-text.js
src/components/dropdown/dropdown-text.spec.js
src/components/dropdown/package.json

Adds a `text-class` prop to `<b-dropdown-text>`, which allows passing classes to the rendered child element.
Closes #5669 

feat(b-dropdown-text) adds `text-class` prop (closes #5669)

---

.bundlewatch.config.json
src/components/table/helpers/sanitize-row.js
src/components/table/table-filtering.spec.js

This PR makes sure to apply all formatters of the field configuration for a row before filtering out only the allowed keys in the `sanitizeRow()` method. This ensures that we add formatted values for keys that may not exist in the row itself.
Closes #5672.

fix(b-table): make sure to apply all formatters of field configuration (closes #5672)

---

src/components/avatar/_avatar.scss

This PR fixes the scaling animation of a `<b-avatar>` button with an image and enhances the fit of non-square images.
**Note:** The scaling enhancements are not supported for IE11 and Edge <16 (https://caniuse.com/#feat=object-fit).
Closes #5610, #5655.

fix(b-avatar): image fit and scale (closes #5610, #5655)

---

src/components/table/README.md

chore(docs): fix a small typo in `b-table` docs

---

package.json
scripts/create-web-types.js
src/components/form-file/form-file.js
yarn.lock

This PR enhances the handling when dropping huge amounts of files/directories on the `<b-form-file>` component.
**See:** https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree/53058574#53058574
Closes #5615.

fix(b-form-file): drop handling for huge amounts of files (closes #5615)

---

docs/markdown/reference/color-variants/README.md

Fix misspelling of 'theme' in Color Variants documentation

chore(docs): fix minor typo in color variants documentation

---

src/components/sidebar/README.md
src/components/sidebar/package.json
src/components/sidebar/sidebar.js

This PR adds a `noEnforceFocus` prop to `<b-sidebar>`. Which similarly to `<b-modal>`, disables the internal focus management to allow users full control over focus, to avoid it being stolen by the sidebar.
Closes #5707

feat(b-sidebar): add `noEnforceFocus` prop (closes #5707)

---

yarn.lock

This PR regenerates the `yarn.lock` file to fix security issues in some dependencies.

chore: regenerate lockfile

---

src/mixins/pagination.js

This PR makes sure to don't set `aria-posinset` and `aria-setsize` attributes for `<b-pagination-nav>` page links.
This is a follow-up changes to the accessibility improvements made in #4810.
Closes #5449.

fix(b-pagination-nav) don't set `aria-posinset` and `aria-setsize` attributes for page links (closes #5449)

---

src/components/pagination-nav/README.md
src/components/pagination-nav/package.json
src/components/pagination-nav/pagination-nav.js
src/components/pagination-nav/pagination-nav.spec.js
src/components/pagination/README.md
src/components/pagination/package.json
src/components/pagination/pagination.js
src/components/pagination/pagination.spec.js
src/mixins/pagination.js

This PR adds a `page-change` event to the `<b-pagination>` and `<b-pagination-nav>` components which is emitted when a page button/link is clicked.
It emits a `BvEvent` object which is cancelable.
The second argument is the page that is going to be selected.
Closes #5679.

feat(b-pagination/b-pagination-nav): allow page change to be prevented (closes #5679)

---

docs/markdown/reference/settings/README.md
src/components/pagination/pagination.js
src/components/tooltip/helpers/bv-tooltip.js
src/components/tooltip/tooltip.spec.js
src/utils/env.js

This PR makes sure to don't show any BootstrapVue warning messages when in production mode.
Closes #5598.

fix: don't display warning messages when in production (closes #5598)

---

src/_variables.scss
src/components/avatar/_avatar.scss
src/components/avatar/avatar-group.spec.js
src/components/avatar/avatar.js
src/components/avatar/avatar.spec.js

This PR switches the default size handling to SCSS/CSS and size classes.
Inline styles are only uses when the user provides a custom size (e.g. `6rem`).
Closes #5592.

feat(b-avatar): add size classes for `sm` and `lg` sizes (closes #5592)

---

src/components/collapse/README.md
src/components/form-textarea/form-textarea.js
src/components/modal/helpers/modal-manager.js
src/directives/toggle/toggle.js
src/utils/bv-collapse.js
src/utils/dom.js
src/utils/dom.spec.js

This PR prevents the browsers scroll anchoring behavior when using `v-b-toggle` with the `<b-collapse>` component as a `accordion` by setting the `overflow-anchor` style property to  `none`.

fix(v-b-toggle): prevent scroll anchoring behavior (closes #5715)

---

src/components/modal/helpers/modal-manager.js
src/utils/dom.js

This PR fixes an issue where the `padding-right` applied to the `<body>` wasn't being properly removed because `getStyle()` returned `null` combined with `setAttr()` applied `data-padding-right="null"`.
- [] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)

fix(b-modal): solve body padding not being removed

---

src/components/table/README.md
src/components/table/helpers/mixin-filtering.js
src/components/table/helpers/sanitize-row.js
src/components/table/table-filtering.spec.js

This PR resolves an issue (introduced with #5674) where an empty array of `filter-included-fields` and/or `filter-excluded-fields` would not be ignored.
Closes #5775.

fix(b-table): properly handle empty included/excluded filter fields (closes #5775)

---

.github/renovate.json
package.json
yarn.lock

This PR locks `postcss` to `<8.0.0` and `autoprefixer` to `<10.0.0` until `postcss-cli` is compatible with PostCSS 8:
https://github.com/postcss/postcss-cli/issues/344
Closes #5774.

chore: lock `postcss` and `autoprefixer` for now (closes #5774)

---

CHANGELOG.md
package.json

Bump the version to v2.17.1 and update changelog.

chore: bump version to v2.17.1

---

src/components/tooltip/helpers/bv-tooltip.js
src/components/tooltip/tooltip.spec.js

This PR fixes a bug where the target's `title` would not be properly saved because of a change which was introduced in #5677.
This PR changes it to the previous way of checking if the `title` has content before adding it to `data-original-title`.

fix(b-tooltip, b-popover): fix `title` not being reset on hide

---

docs/common-props.json
src/components/nav/nav-item-dropdown.js
src/components/nav/nav-item-dropdown.spec.js
src/components/nav/package.json
src/mixins/dropdown.js

This PR ensures that the `boundary` handling for `<b-nav-item-dropdown>` is completely disabled when inside a `<b-navbar>`.
While at it, the property descriptions for `<b-nav-item-dropdown>` related to the toggle were improved.
Closes #5789.

fix(b-nav-item-dropdown): `boundary` handling in `<b-navbar>` (closes #5789)

---

src/components/form-tags/README.md

Fixes a mismatched single/double quote in the form-tags wrapper component example code.

chore(docs): fix unmatched quote in form-tags wrapper example

---

src/components/form-rating/README.md

Fix a typo in the docs where `b-form-rating` was written as `b-from-rating`

chore(docs): fix typo in `b-form-rating` docs

---

src/components/skeleton/index.js
src/index.js

This PR adds the missing component exports for the `<b-skeleton-icon>`, `<b-skeleton-img>`, `<b-skeleton-table>` and `<b-skeleton-wrapper>` components.
Closes #5804.

fix(b-skeleton): add missing component exports (closes #5804)

---

src/components/popover/package.json
src/components/tooltip/package.json

chore(docs): correct `placement` description

---

CHANGELOG.md
package.json

Bump version to v2.17.2 and update `CHANGELOG.md`.

chore: bump version to v2.17.2

---

src/components/carousel/carousel.js

This PR fixes the glitchy behavior when changing between certain slides too fast.
The behavior should now align with how Native Bootstrap handles the changing of slides.
Closes #5810 

fix(b-carousel): fix glitching when switching slides fast (closes #5810)

---

src/components/sidebar/README.md

chore(docs): fix sidebar documentation typo

---

src/components/skeleton/_skeleton.scss

This PR fixes the animation overflow issue for `<b-skeleton>` components in Safari.
The fix is the same one used to resolve #5655.
Closes #5809.

fix(b-sekelton): animation overflow issue for Safari (closes #5809)

---

src/components/toast/README.md

This PR adds a example for a custom close button to the `<b-toast>` docs.
Closes #5837. 

chore(docs): add example for `<b-toast>` with custom close button (closes #5837)

---

src/components/form-group/README.md

This PR simplifies the example code for `<b-form-group>`'s `valid-feedback` and `invalid-feedback` props.
Closes #5850.

chore(docs): simplify `<b-form-group>` validation message example (closes #5850)

---

src/components/card/card.js

This PR fixes an issue for `<b-card>` when using the `overlay` option in combination with a header or footer by wrapping the image and body in a relation positioned container.
Closes #5828.

fix(b-card): properly support header/footer with body image overlay (closes #5828)

---

src/components/navbar/README.md
src/components/navbar/navbar-toggle.js
src/components/navbar/package.json

Specifies that the `target` prop supports both a `string` and `array` as a value.
While also adding a mention that it supports targeting a sidebar, instead of only a collapse.

docs(b-navbar): specify support of sidebar + array

---

src/components/table/README.md

chore(docs): capitalize all descriptions for table provide function props

---

src/components/form-datepicker/README.md

chore(docs): fix `<b-form-datepicker>` locale typo

---

src/components/avatar/README.md

Fix closing span tag in avatar/README.md

chore(docs): fix closing span tag

---

.github/dependabot.yml

This allows dependabot to submit PRs automatically with version bumps to any GitHub action which this project uses.
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot

chore(deps): allow dependabot to check GitHub actions daily

---

src/components/calendar/calendar.js

This PR fixes the current month formatting in `<b-calendar>` for certain dates.
Closes #5818.

fix(b-calendar): month formatting for certain dates (closes #5818)

---

CHANGELOG.md
package.json

This PR bumps the version to v2.18.0 and updates the `CHANGELOG.md`.

chore: bump version to v2.18.0

---

docs/markdown/intro/README.md

This PR adds an example to how to alias Vue.js in  `vue.config.js` when using Vue CLI.

chore(docs): add example on how to alias Vue.js with Vue CLI

---

src/icons/icon.js

This PR fixes the local icon component lookup for `<b-icon>`.
Closes #5937.

fix(b-icon): local component lookup (closes #5937)

---

CHANGELOG.md
package.json

This PR bumps the version to v2.18.1 and updates the `CHANGELOG.md`.

chore: bump version to v2.18.1

---

src/components/carousel/README.md

chore(docs): fix missing ` in carousel documentation

---

src/components/avatar/_avatar.scss

Add `flex-shrink: 0` to `<b-avatar />` to prevent the avatar from being squished when combined with flexed content.
Closes #5962.

fix(b-avatar): prevent avatar from being squished (fixes #5962)

---

docs/markdown/reference/theming/README.md

Corrected grammar:
from: certain features of BootstrapVue uses ...
to: certain features of BootstrapVue use ...
certain features is the noun, and its plural, so it can't be uses, has to be use.

chore(docs): correct typo in theming section

---

src/components/avatar/README.md
src/components/avatar/_avatar.scss

This PR fixes the `z-index` handling of `<b-avatars>` with a badge in other components.
Closes #5964.

fix(b-avatar): badge `z-index` handling (closes #5964)

---

scripts/rollup.config.js

This PR correct a typo in a comment in `rollup.config.js`.

chore: correct typo in `rollup.config.js`

---

.github/workflows/build.yml
.github/workflows/test.yml

This PR bumps the default Node.js versions for tests to `14` and makes sure to test for all current active LTS versions.

chore(ci): update Node.js versions

---

SECURITY.md

This PR adds a `SECURITY.md` file.

chore: add `SECURITY.md`

---

docs/components/componentdoc.vue
docs/components/importdoc.vue
docs/utils/index.js

This PR improves and unifies the component name formatting.

chore(docs): improve component name formatting

---

docs/plugins/docs-mixin.js
src/components/alert/alert.js
src/components/toast/toast.js
src/components/toast/toast.spec.js

This PR unifies the `setInterval()` and `setTimeout()` usage across the codebse.

chore: unify interval/timeout handling

---

src/components/table/README.md

I updated the documentation of the b-table component to show another example of `pageOptions` featuring a custom text like this:
```javascript
pageOptions: [5, 10, 20, 50, {
value: Number.MAX_SAFE_INTEGER,
text: "show all"
}],
```
Found initially from <https://stackoverflow.com/questions/61655076/vue-b-table-customize-pagination-to-show-all-rows> and it is not mentioned in the official documentation prior to this pull request.
This is verified with the latest version (`2.18.1`).
I joined another minor commit to correct a sentence in the b-table documentation mentioning `five properties` to describe a table of 6 properties. …

chore(docs): add another `pageOptions` setting example

---

CHANGELOG.md
package.json

This PR bumps the version to v2.19.0 and updates the `CHANGELOG.md`.

chore: bump version to v2.19.0

---

docs/markdown/reference/router-links/README.md
src/components/avatar/_avatar.scss
src/components/form-file/README.md
src/components/form-input/README.md
src/components/form-textarea/README.md
src/components/table/README.md

This PR updates the [canisuse.com](https://caniuse.com/) links in the docs to their latest scheme.

chore(docs): update "Can I use" links

---

package.json
yarn.lock

This PR removes the deprecated and now unused `eslint-plugin-standard`.

chore(deps): remove deprecated `eslint-plugin-standard`

---

src/mixins/form-text.js

This PR ensures the internal v-model value always is modified (modifiers applied).
Closes #6078.

fix(b-form-input/b-form-textarea): v-model handling (closes #6078)

---

yarn.lock

This PR regenerates the `yarn.lock` file.

chore(deps): regenerate lockfile

---

src/components/form-spinbutton/form-spinbutton.js

This PR removes the `<div>` wrapper element around the content of `<b-form-spinbutton>`'s buttons.
Closes #6099.

fix(b-form-spinbutton): button markup (closes #6099)

---

src/components/form-tags/form-tags.js
src/components/form-tags/form-tags.spec.js

This PR adds the missing `required` attribute handling for `<b-form-tags>`.
Closes #6094.

fix(b-form-tags): required handling (closes #6094)

---

src/components/form-tags/README.md
src/components/form-tags/form-tags.js
src/components/form-tags/form-tags.spec.js
src/components/form-tags/index.d.ts
src/components/form-tags/package.json

This PR adds a `reset()` method to `<b-form-tags>` to fully reset the input.
`<b-form-tags>` will also get reset when on a `form` or `input` reset event.

feat(b-form-tags): add `reset` method

---

CHANGELOG.md
package.json

This PR bumps the version to v2.20.0 and updates the `CHANGELOG.md`.

chore: bump version to v2.20.0

---

src/components/calendar/calendar.js
src/components/calendar/calendar.spec.js
src/components/form-file/form-file.js
src/components/form-spinbutton/form-spinbutton.js
src/components/form-tags/form-tags.js
src/components/table/helpers/mixin-filtering.js
src/mixins/form-text.js

This is a follow-up PR to #6070 that implements a more robust user supplied prop function detection.
Closes #6112.

fix: user supplied prop function detection (closes #6112)

---

CHANGELOG.md
package.json

This PR bumps the version to v2.20.1 and updates the `CHANGELOG.md`.

chore: bump version to v2.20.1

---

.github/dependabot.yml
docs/nuxt.config.js
docs/utils/hljs.js
package.json
yarn.lock

This PR updates `highlight.js` to v10 since v9 has several bugs and security issues.
Since v10 drops legacy browser support we need to transpile it for the legacy build.

chore(docs): update `highlight.js` to v10

---

src/components/alert/alert.js
src/components/avatar/avatar.js
src/components/table/helpers/default-sort-compare.spec.js
src/utils/inspect.js
src/utils/inspect.spec.js

This PR fixes a bug in the default sort-compare logic for ISO date strings for `<b-table>` items.
It was introduced in #6105 because the `isNumeric()` util detected the date strings as numeric.
Closes #6129.

fix(table): default sort compare logic for date strings (closes #6129)

---

src/components/form-datepicker/form-datepicker.js

This PR fixes the internal `valueAsDate` prop handling of `<b-form-datepicker>`.
The issue was introduced with #5981 which passed down the `valueAsDate` prop to `<b-calendar>`.
We don't want this to happen since we internally always want the `value` to be a string.
Closes #6138.

fix(b-form-datepicker): `valueAsDate` prop handling (closes #6138)

---

src/components/form-tags/README.md
src/components/form-tags/form-tag.js
src/components/form-tags/form-tag.spec.js
src/components/form-tags/form-tags.js
src/components/form-tags/form-tags.spec.js
src/components/form-tags/package.json

This PR adds a `no-tag-remove` prop to `<b-form-tags>` and a `no-remove` prop to `<b-form-tag>`.
Closes #6162.

feat(b-form-tags): add `no-tags-remove` prop (closes #6162)

---

src/components/sidebar/README.md
src/components/sidebar/package.json
src/components/sidebar/sidebar.js
src/components/sidebar/sidebar.spec.js
src/mixins/normalize-slot.js

This PR adds optionally scoped `header` slot to `<b-sidebar>`.
It also enhances the detection wether the sidebar has a title.
Closes #6177.

feat(b-sidebar): add `header` slot (closes #6177)

---

src/components/list-group/README.md

This PR fixes a typo in the `<b-list-group>` documentation.

chore(docs): correct typo in `<b-list-group>` documentation

---

CHANGELOG.md
package.json

This PR bumps the version to v2.21.0 and updates the `CHANGELOG.md`.

chore: bump version to v2.21.0

---

src/components/modal/modal.js
src/components/tooltip/helpers/bv-tooltip.js
src/mixins/dropdown.js

This PR fixes an error that was introduced in #6141 that prevented the event that should be emitted on `$root` to be actually emitted.
It also makes sure to emit the `$root` event before the equivalent on the instance.
Closes #6197.

fix(b-dropdown): root events (closes #6197)

---

src/components/pagination/pagination.js

This PR makes sure we don't set the initial page count for `<b-pagination>` twice.
Closes #6199.

fix(b-pagination): don't set initial page count twice (closes #6199)

---

src/components/form-timepicker/README.md

This PR fixes the markup of the "Button only mode" example on the `<b-form-timepicker>` docs.

chore(docs): fix `<b-form-timepicker>` "Button only mode" example markup

---

src/components/badge/badge.js

#6141 accidentally introduced a change that prevented attribute inheritance from `<b-badge>`.
This PR correct the changes.
Closes #6209.

fix(b-badge): attribute inheritance (closes #6209)

---

CHANGELOG.md
package.json

This PR bumps the version to v2.21.1 and updates the `CHANGELOG.md`.

chore: bump version to v2.21.1

---

src/constants/env.js

#6141 introduced a change that broke the environment detection based on `navigator.userAgent`.
This PR fixes the issue.
Closes #6225.

fix: environment detection based on `userAgent` (closes #6225)

---

.codesandbox/ci.json

This PR adds the [BootstrapVue Nuxt.js Starter Project](https://codesandbox.io/s/bootstrapvue-nuxtjs-starter-project-xblbj) to our CodeSandbox CI configuration.

chore: add Nuxt.js CodeSandbox CI template

---

docs/markdown/intro/README.md

The original version was a little confusing because it was repetitive and missed the opportunity to make clear at the outset that there are potentially 3 SCSS files and they must be imported in order.
Simplify the documentation making clear the importance of the order, and exactly how to import
- [    ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)

chore(docs): improve Bootstrap/BootstrapVue style import guide in "Getting started" docs

---

src/components/dropdown/README.md

This fixes the headings for `b-dropdown-divider`, `b-dropdown-group`, and `b-dropdown-header` in the Dropdown docs.

chore(docs): fix typos in `<b-dropdown>` docs

---

src/components/form-file/README.md

This PR removes the `label-for` prop from `<b-form-group>`'s with `<b-form-file>` component since the `<b-form-file>` component already generates a `label` element itself.
Closes #6229.

chore(docs): remove `label-for` from `<b-form-group>`'s with `<b-form-file>` component (closes #6229)

---

src/icons/helpers/icon-base.js

This PR makes sure to completely remove the `title` from render handling, when empty.
Closes #6223.

fix(b-icon): title render handling (closes #6223)

---

src/components/form-select/package.json
src/components/form-textarea/package.json

Fixes some minor typos in the documentation for `<b-form-select>` and `<b-form-textarea>` components.

chore(docs): fix typos in `<b-form-select>` and `<b-form-textarea>` docs

---

src/components/form-btn-label-control/_form-btn-label-control.scss
src/components/form-btn-label-control/bv-form-btn-label-control.js

This PR fixes the control size of `<b-form-datepicker>` and `<b-form-timepicker>`.
Closes #6246.

fix(b-form-datepicker/b-form-timepicker): control size (closes #6246)

---

src/components/table/helpers/mixin-caption.js
src/components/table/helpers/mixin-table-renderer.js

This PR makes sure the `aria-describedby` attribute is only applied to `<b-table>` when a caption really exist.
Closes #6250.

fix(b-table): only set `aria-describedby` when caption really exists (closes #6250)

---

docs/markdown/reference/theming/README.md

This PR corrects some typos and improves wording in the themes docs.

chore(docs): correct typos and improve wording in theming section

---

src/components/collapse/helpers/bv-collapse.js
src/components/dropdown/dropdown-item.js
src/components/nav/nav-form.js
src/components/nav/nav-item.js
src/icons/helpers/make-icon.js
src/icons/icon.js
src/icons/iconstack.js

This PR is a follow-up to #6141 and cleans up the props inheritance in some components.

fix: clean up props inheritance

---

src/components/table/README.md
src/components/table/helpers/mixin-table-renderer.js
src/components/table/table-lite.spec.js
src/components/table/table.spec.js

This PR allows the use to use the `responsive` and `stacked` props for `<b-table>` and `<b-table-lite>` together.
Closes #6261.

fix(b-table): allow `responsive` and `stacked` props together (closes #6261)

---

src/components/dropdown/dropdown-group.js
src/components/dropdown/dropdown-header.js

This PR makes sure to only apply `heading` role to `<b-dropdown>` header when not a `header` tag.

fix(b-dropdown): only apply `heading` role to header when not a `header` tag (closes #6273)

---

src/components/table/README.md

This PR fixes a typo in the `<b-table>` documentation.

chore(docs): fix typo in `<b-table>` docs

---

src/components/button-group/README.md

add code format to the content 'size' of the 'size' prop.

chore(docs): fix typo in `<b-button>`section

---

src/components/image/img-lazy.js

This PR makes sure that `<b-img-lazy>` prefers it's own computed props over the user supplied ones.

fix(b-img-lazy): prefer computed props over user supplied ones

---

docs/components/footer.vue
docs/content.js

This PR makes sure to use title case for any reference to the "Getting Started" section in the docs.

chore(docs): correct title case for references to "Getting Started" section

---

src/mixins/form-text.js
src/utils/props.js

This PR fixes the legacy browser support for `<b-form-input>` and `<b-form-textarea>`.
Closes #6283.

fix(b-form-input/b-form-textarea): legacy browser support (closes #6283)

---

src/components/form-tags/form-tags.js
src/components/form-tags/form-tags.spec.js
src/components/form-tags/package.json

This PR adds a `feedback-aria-live` prop to the `<b-form-tags>` component (similar to `<b-form-group>`) which defaults to `assertive`.

feat(b-form-tags): add `feedback-aria-live` prop

---

src/components/image/img-lazy.js

This PR fixes the `blank` placeholder support for `<b-form-img>` on Firefox.
Closes #6320.

fix(b-img-lazy): `blank` placeholder for Firefox (closes #6320)

---

src/components/table/index.d.ts

This PR adds missing the missing `sortKey` field option to the `<b-table>` types and correct a typo.
Closes #6352.

fix(b-table): add missing `sortKey` field type and correct a typo (closes #6352)

---

src/components/collapse/collapse.js
src/components/modal/README.md
src/components/modal/helpers/bv-modal.js
src/components/modal/modal.js
src/components/navbar/navbar-toggle.js
src/components/pagination-nav/pagination-nav.js
src/components/pagination/pagination.js
src/components/table/helpers/mixin-tbody-row.js
src/components/table/helpers/mixin-tbody.js
src/components/tabs/tabs.js
src/components/toast/toast.js
src/components/tooltip/helpers/bv-tooltip.js
src/mixins/click-out.spec.js
src/mixins/focus-in.spec.js

This PR unifies the event variable names across the codebase.
This is a follow-up to #6141.

chore(refactor): unify event variable names

---

src/components/table/helpers/mixin-sorting.js
src/components/table/helpers/mixin-thead.js

This PR positions the `<b-table>` header cell (`<b-th>`) relative when it contains a  `.sr-only` sort label to work around overflow issues.
Closes #6326.

fix(b-table): header cell overflow for `.sr-only` sort label (closes #6326)

---

src/components/link/link.js

This PR removes the default values from props that are passed down to `<router-link>` to avoid deprecation warnings.
Ref: https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link
Closes #6373.

fix(b-link): remove default values from `vue-router` pass-down props (closes #6373)

---

src/components/table/helpers/mixin-selectable.js
src/components/table/table-selectable.spec.js

This PR makes sure to add `role="grid"` to `<b-table>` when in selectable mode.
Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role
Closes #6305.

fix(b-table): add missing `role="grid"` when selectable (closes #6305)

---

src/components/calendar/calendar.js
src/components/calendar/calendar.spec.js
src/components/calendar/package.json
src/components/modal/modal.js
src/components/modal/modal.spec.js
src/components/modal/package.json
src/components/sidebar/package.json
src/components/sidebar/sidebar.js
src/components/sidebar/sidebar.spec.js
src/components/time/package.json
src/components/time/time.js
src/components/time/time.spec.js
src/components/toast/package.json
src/components/toast/toast.js
src/components/toast/toast.spec.js

This PR adds `header-tag` and `footer-tag` props to all components with header and footer.
Closes #6321.

feat: add `header-tag` and `footer-tag` props to all components with header and footer (closes #6321)

---

src/components/form-tags/form-tags.js
src/components/modal/helpers/modal-manager.js
src/components/modal/modal.js
src/components/toast/toaster.js
src/mixins/form-text.js
src/mixins/listen-on-document.js
src/mixins/listen-on-root.js
src/mixins/listen-on-root.spec.js
src/mixins/listen-on-window.js

This PR moves away from lifecycle hook listeners where easily possible.

chore(refactor): move away from lifecycle hook listeners

---

src/components/table/helpers/mixin-selectable.js

This PR makes sure to prefer the user-provided `role` attribute and only apply `aria-multiselectable` when it is `'grid'`.
Ref: https://github.com/bootstrap-vue/bootstrap-vue/issues/6305#issuecomment-770120010
> @jackmu95: food for thought (possible enhancement): if user provides a `role` for the element, BV should not override it. The default one should only be applied when no role (even if invalid by today's standard) was provided. I'll look deeper into this.
description …

fix(b-table): prefer user-provided `role` attribute

---

src/components/form-tags/_form-tags.scss

fix(b-input-tags): not respecting custom `$input-color` (closes #6388)

---

package.json
yarn.lock

This PR updates dependencies and regenerates the `yarn.lock` file.
Closes #6401.
Closes #6404.
Closes #6405.

chore(deps): update dependencies an regenerate `yarn.lock`

---

src/components/table/README.md

This PR corrects the closing tag on `<b-table-simple>` code example.
Closes #6528.

chore(docs): correct closing tag on `<b-table-simple>` code example (closes #6528)

---

src/components/form-tags/package.json

Fixes "can not added" typos in form-tags reference package.json by
changing text to "cannot be added".

chore(docs): fix typos in `<b-form-tags>`'s `tag-state` event argument descriptions

---

src/components/form-timepicker/package.json

This really seems like merge/copy-paste error :) 

chore(docs): remove duplicate `<b-form-timepicker>` parameter

---

src/components/table/package.json

Fix grammar error in b-table description

chore(docs): fix grammar in `<b-table>` parameter description

---

.eslintrc.js
.github/dependabot.yml
package.json
yarn.lock

This PR updates all dependencies and resolves breaking changes caused by the updates.
Closes #6584.
Closes #6586.

chore: update dependencies (closes #6584, #6586)

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/test.yml

This PR updates the CI workflows to the newest Node.js versions.

chore(ci): update workflows to new Node.js versions

---

src/components/carousel/README.md

Fix capital on the attribute value of `<b-carousel-slide>`.
Closes #6593.

chore(docs): fix typo in `<b-carousel>` docs (closes #6593)

---

src/components/table/README.md

Change `table-classes` to `table-class` in the `b-table-simple` section of the documentation.

docs(table): correct table-class prop name

---

src/icons/helpers/make-icon.js

I observed that doing a simple import of bootstrap-vue:
```js
import BootstrapVue from 'bootstrap-vue';
```
takes hundreds of milliseconds (give or take, depending on user's CPU).
I tried to do some profiling and found out that most of the time is spent in `icons` module, specifically in `makeIcon`:
When zoomed it, you can see that most of the time is spent in functions `omit` and `Vue.extend`:
Each call is just a few milliseconds, but there are hundreds of icons, so it takes hundreds of milliseconds. That's already a noticeable delay that I observed in these two situations:
- starting an app that uses bootstrap-vue (worse score in https://web.dev/vitals/)
- each re-run of tests (run with `jest --watch`) of code that uses bootstrap-vue
Don't call `omit` in each `makeIcon` call, but only …

perf(icon) Speed up slow icons module import

---

src/components/toast/README.md

The Toast documentation recommends an auto-hide-delay of `4 seconds plus 1 second per 100 words`. That implies people read at 100 words per second, which is definitely incorrect. A quick google search indicates the number lies between 200 and 250 _per minute_.
I've adapted the documentation based on an average reading speed of 200 wpm.

Fix average reading speed in toast guidelines

---

docs/markdown/intro/README.md

docs(intro): fix typo in README

---

docs/common-props.json
docs/markdown/reference/router-links/README.md
src/components/link/link.js

This PR makes b-link support `exact-path` and `exact-path-active-class` props for router link.
Vue Router introduced these [new props in 3.5.0](https://github.com/vuejs/vue-router/commit/cbb552c946af4ff0946e5e2f0091c8877850befd#diff-ac0e4a04bf399f08df2307f91b7bc14c4763ff122d3b03f0f6da6e3fdae6b801).

feat(b-link): support `exact-path` and `exact-path-active-class` props for router link (fixes #6434)

---

.github/workflows/build.yml
.github/workflows/test.yml

chore(ci): bump node version

---

src/directives/tooltip/package.json

There where some missing modifiers in the tooltip package.json.

chore(docs): added some missing modifiers to the tooltip package.json

---

scripts/create-web-types.js

Improve Web Types metadata generation around icons.
1. The Web Types file is generated according to the newest version
2. Icon components are created using pattern - better autocompletion, smaller Web Types file
3. In WebStorm 2022.3 all icons will render in code completion and documentation
4. File size is reduced from 7.7MB to 3.2MB, while including all SVGs.
Highlights of the new icons support:

chore(web-types): improve Web Types metadata generation around icons.

---

src/components/media/README.md

Fix typos and improve wording in Components > Media docs.  

chore(docs): fix typos and improve wording in media component docs

---

docs/markdown/intro/README.md

Add a missing oxford comma to the Getting Started documentation page for clarity.

chore(docs): add missing oxford comma to docs

---

docs/components/header.vue
docs/markdown/intro/README.md
docs/pages/index.vue
docs/pages/vue3.vue

chore(docs): add vue3 related info

---

src/components/transporter/transporter.spec.js
src/utils/create-new-child-component.js

v2.23.0 broke `provide - inject` or other similar (Vuex) relation for modals, transporters, etc.
Here we're fixing this behavior

fix(util): retain parent-child relationship for Vue 2
